### ISSUE TITLE
[BUG] в обработке Тесты_ОткрытиеФормКонфигурации не работает отбор по префиксу

### ISSUE THREAD

**Issue by akademik1986** [silverbulleters/add#1008]
В обработке Тесты_ОткрытиеФормКонфигурации не работает отбор метаданных по заданному префиксу.

**Comment by LazarenkoA** [comment]
Попробовал с такой настройкой 
![image](https://user-images.githubusercontent.com/15386101/152308280-a9b685f0-42bd-4001-bde4-cf651ea1b1fa.png)
все работает корректно

**Comment by LazarenkoA** [comment]
раньше если был задан префикс и подсистема работало это по ИЛИ, передел по И
