### ISSUE TITLE
Не открывается некоторый перечень тестов

### ISSUE THREAD

**Issue by PeresadaMY** [silverbulleters/add#1026]
## Контекст

-     Техническая информация:
	- Версия Vanessa-ADD: ver 6.8.0
	- Имя конфигурации: БухгалтерияПредприятия
	- Синоним конфигурации: Бухгалтерия предприятия, редакция 3.0
	- Версия конфигурации: 3.0.42.73
	- Платформа 1С: 8.3.18.1289
	- Режим запуска: Управляемое приложение (Тонкий клиент)
	- Тип базы: Файловая ИБ
    - Операционная система: Windows Server 2009

-     Описание проблемы:
	Не открываются тесты через обработку xddTestRunner.epf.
Список тестов:
	- Тесты_ПроверкаАвтоРегистрацииПлановОбмена
	- Тесты_ПроверкаВключенияОбъектовВКомандныйИнтерфейс
	- Тесты_ПроверкаОбъектовМетаданныхКонфигурацииПоставщика
	- Тесты_ПроверкаПериодичностиНумерацииДокументов
	- Тесты_ПроверкаПривилегированногоРежимаОбъектов
	- Тесты_ПроверкаРегламентныхЗаданий
	- Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный
	- Тесты_ПроверкаСтандартныхРолей
	
## Запрос поддержки

Объяснение почему не открываются. По возможности описание функциональности тестов, так как на вики подробной информации по каждому дымовому тесту я не нашел.

## Критичность запроса

Средняя

**Comment by akademik1986** [comment]
@PeresadaMY  чтобы они открывались, они должны быть прописаны в json настройке
![image](https://user-images.githubusercontent.com/19662685/160141192-e2bf79aa-d8fb-48f0-bba2-c52976bc7b25.png)

**Comment by PeresadaMY** [comment]
Спасибо, я со старой версией работал, теперь все отлично!
