### ISSUE TITLE
[BUG] При запуске тесты_ЗаписьЭлементовСправочников критическая ошибка, если модуль справочника не компилируется

### ISSUE THREAD

**Issue by akademik1986** [silverbulleters/add#1034]
**Описание ошибки**
При запуске тесты_ЗаписьЭлементовСправочников интерактивно или через CI, если в проверяемом справочнике будет ошибка компиляции модуля, то прогон тестов зависнет с красной ошибкой.

**Сценарий воспроизведения**
В любом справочнике в модуле объекта сохранить например обращение к несуществующему модулю и функции, сохранить и запустить тесты_ЗаписьЭлементовСправочников на выполнение.
Даже нажатии OK тестирование не продолжается.

- ВАЖНО: хотя бы один элемент в справочнике уже должен существовать!

**Скриншоты**
![image](https://user-images.githubusercontent.com/19662685/162171111-bd3df1f8-7c88-41ad-a1c8-081f29799459.png)

Версия Vanessa-ADD: ver 6.8.0

**Comment by LazarenkoA** [comment]
и попытка / исключение не помогает, видимо так себя платформа ведет в таких случаях

**Comment by artbear** [comment]
https://t.me/vanessa_opensource_chat/6396
Artur, [09.04.2022 16:31]
А вот еще веселая проблема - баг, который вернулся через 8 лет? ))

Artur, [09.04.2022 16:31]
[Forwarded from Artur]
предварительно очень похоже на [старый баг платформы, задокументированный в Ванесса-АДД](https://github.com/vanessa-opensource/add/blob/develop/doc/KNOWN-PROBLEMS.md#%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2-%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%B0%D0%B2%D0%BB%D0%B8%D0%B2%D0%B0%D0%B5%D1%82%D1%81%D1%8F)но проблема была до версии 8.3.4 )
8 лет назад!!

неужели опять проявилась? я проверил на 8.3.20.1789
контекст 
- в своем коде на сервере обращаемся к объекту, в модуле которого есть синтакс-ошибка
  - Ссылка.ПолучитьОбъект()
- и даже если код заключен в блок попытку-исключение и на сервере, и на клиенте
```bsl
//на клиенте
Попытка
  КодНаСервере(Ссылка);
Исключение
  ИнфоОшибки = ИнформацияОбОшибке();
КонецЕсли;
// код на сервере
Попытка
  Объект = Ссылка.ПолучитьОбъект();
Исключение
  ИнфоОшибки = ИнформацияОбОшибке();
КонецЕсли;
```

внутри обоих исключений (на клиенте или сервере) точка останова не сработает, сразу получаем модальное окно 1С в режиме Предприятия.
А код не поймает исключение (

ps ссылка на "новый-старый" баг https://github.com/vanessa-opensource/add/issues/1034

Artur, [09.04.2022 16:31]
[Forwarded from Artur]
да, простейшее подтверждение
```bsl
&НаСервереБезКонтекста
Процедура Команда1НаСервере(Ссылка)
  Попытка                              
    // в модуле этого справочника простая синтакс-ошибка
    // например, пустой текст модуля и какой-нибудь не программный текст
    Объект = Ссылка.ПолучитьОбъект();
    
    Объект = Вычислить("Это не код, а ошибка");// а такая ошибка штатно ловится!
  Исключение
    ИнформацияОбОшибке = ИнформацияОбОшибке();
  КонецПопытки;
КонецПроцедуры

&НаКлиенте
Процедура Команда1(Команда)
  Попытка
    Команда1НаСервере(Ссылка);
  Исключение
    ИнформацияОбОшибке = ИнформацияОбОшибке();
  КонецПопытки;
КонецПроцедуры
```

Artur, [09.04.2022 16:31]
[Forwarded from Artur]
[ Photo ]

Artur, [09.04.2022 16:31]
[Forwarded from Artur]
[ File : ТестИсключения.epf ]

Artur, [09.04.2022 16:33]
[ Photo ]
скрин этого исключения, которое не ловится (

Artur, [09.04.2022 16:45]
[In reply to Artur]
аналогично нельзя отловить ошибку, возникающую на
```bsl
    Объект = Справочники.Справочник1.СоздатьЭлемент();
```

**Comment by artbear** [comment]
Обновил доку "Известные проблемы".
Другого пока предложить нечего.
Проблема наблюдается в разных платформах.

Закрываю (
