### ISSUE TITLE
[BUG] В новом релизе 6.9.0 не работают исключения  по "ИсключенияПоИмениМакетов" для теста тесты_ПроверкаМакетовСКД

### ISSUE THREAD

**Issue by beefree86** [silverbulleters/add#1068]
тест тесты_ПроверкаМакетовСКД из новой версии ванессы адд 6.9.0 не видит исключения из массива "ИсключенияПоИмениМакетов"

Пример настроек:

    "МакетыСКД": {
        "Используется": true,
        "ИсключенияОбщихМакетов": [],
        "ИсключенияПоИмениМетаданных": [],
        "ИсключенияПоИмениМакетов": [
                "СКД_УппКа",
                "СКДПереченьДокументов",
                "РасшифровкаРасходыОтносящиесяКСтоимостиРеализованногоИмущества",
                "РасшифровкаПрямыеРасходыЕНВД",
                "РасшифровкаПрочиеРасходыРаспределяемые"
        ]
    }

![image](https://user-images.githubusercontent.com/100960841/212693743-956c037d-a2b4-4b47-acef-d6f005bee5bc.png)

Указанные в исключениях макеты падают в ошибку, на тесте из прошлой поставки исключения виделись и работали корректно.

Техническая информация:
	- Версия Vanessa-ADD: 6.8.0
	- Имя конфигурации: БухгалтерияДляБеларуси
	- Синоним конфигурации: Бухгалтерия для Беларуси, редакция 2.1
	- Версия конфигурации: 2.1.46.3
	- Платформа 1С: 8.3.21.1624
	- Тип базы: Клиент-серверная ИБ
	- Режим запуска: Управляемое приложение (Тонкий клиент)
	- Режим совместимости (для TestManager): Версия8_3_14
	- Режим совместимости интерфейса (для TestManager): Такси
 	- Режим синхронности: включен
 	- Защита от опасных действий: выключен
	- Язык (для TestManager): Русский
	- Локализация (для TestManager): ru_RU
	- Операционная система (клиент): Windows x86-64 Microsoft Windows 10 version 10.0  (Build 17763)
	- Операционная система (сервер): Windows x86-64 Microsoft Windows 10 version 10.0  (Build 17763)
	- Активные расширения:
	- - Расширение: InfostartToolkitPROF -- Infostart Toolkit PROF (2022.4.03) - Безопасный режим не задан

**Comment by artbear** [comment]
После реализации https://github.com/vanessa-opensource/add/pull/948 нужно использовать другое имя настройки 

вместо "МакетыСКД" нужно указывать "Тесты_ПроверкаМакетовСКД"
