### ISSUE TITLE
Верните шаг загрузки из макета

### ISSUE THREAD

**Issue by allustin** [silverbulleters/add#112]
Нужно вернуть в поставку часть шагов формата

* я загружаю макет из ...

**Comment by artbear** [comment]
Подтверждаю!

Проблема в том, что шаг `И я загружаю макет "ТысячаЭлементовСправочника1"` находится в файле features\libraries\VB\step_definitions\Load1000ItemsfromMxl.epf
а `features\libraries\VB` у нас не входит в поставку, т.к. он содержит фичи, актуальные только для тестирования VB и клиентам они не нужны.

**Comment by artbear** [comment]
@pumbaEO Самое простое - перенести файл в  другое место, которое входит в поставку, верно?

**Comment by artbear** [comment]
- [ ] Также  нужно посмотреть на весь каталог `features\libraries\VB` и фичи/сценарии из него, чтобы выявить шаги, не относящие к VB, а являющиеся универсальными.

- [ ] И затем перенести их в другой каталог

**Comment by artbear** [comment]
- [ ] Описать шаг таким образом, чтобы он был виден в `Известные шаги`

**Comment by artbear** [comment]
@pumbaEO Тут какой-то странный баг :(
каталог `features\libraries\VB` почему-то не появляется в финальном архиве opsx
хотя в логах видно, что вроде бы собирается

**Comment by artbear** [comment]
Ага, все понятно.

в packagedef явно указано удалить файлы из каталога :(
```bsl
УдалитьФайлы("./features/libraries/VB", "*.*");
```

@pumbaEO

**Comment by artbear** [comment]
Вместо явного удаления `УдалитьФайлы("./features/libraries/VB", "*.*");`
лучше сделать спец.ключ `opm_build_exclude` в `ospx/settings.json` и удалять все каталоги/файлы, указанные в массиве внутри этого ключа

**Comment by yaksonia** [comment]
когда ждать релиза? (пишу под давлением, @allustin заставил)

**Comment by artbear** [comment]
@yaksonia Релиз будет на днях - сегодня, завтра или бодрящий пятничный релиз :)

ЗЫ спасибо за авторизацию. @allustin плохого не посоветует :)

**Comment by artbear** [comment]
@allustin @yaksonia Исправлено, уже в ветке develop, затем войдет в релиз.
