### ISSUE TITLE
[BUG] не считывается настройка ИмяФайлаЛогВыполненияСценариев, snapshot 6.9.5

### ISSUE THREAD

**Issue by lo0p3r** [silverbulleters/add#1126]
При пакетном запуске версии **snapshot 6.9.5** (`vrunner xunit`) получаю ошибку "Не указано имя лог-файла в параметре <ИмяФайлаЛогВыполненияСценариев>". На версии **6.8.0** такая ошибка не возникает.

Подробный текст ошибки:
Не указано имя лог-файла в параметре <ИмяФайлаЛогВыполненияСценариев>
{ВнешняяОбработка.ВыводВЛогФайл.Форма.Форма.Форма(55)}:ВызватьИсключение "Не указано имя лог-файла в параметре <ИмяФайлаЛогВыполненияСценариев>";
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(1937)}:ПлагинВыводВЛогФайл.Вывести(Сообщение);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(1927)}:ВывестиСообщениеВЛогФайл(ТекстСообщения);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(1422)}:ВывестиСообщение(ОписаниеОшибки, СтатусСообщения.ОченьВажное);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(98)}:ВыполнитьПакетныйЗапуск(ПараметрЗапуска);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(399)}:ПриОткрытииЗавершение();
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(392)}:ЗагрузкаПлагиновЗавершение();
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(320)}:ПодключитьНайденныеКлиентскиеПлагины(ПомещенныеФайлы, ИдентификаторыПлагинов);
[ОшибкаВоВремяВыполненияВстроенногоЯзыка, ИсключениеВызванноеИзВстроенногоЯзыка]

Ошибка возникает в процедуре **ПодготовитьВыводВЛогФайл()** (причина ошибки в процедуре **ПервичнаяНастройка()**) формы **УправляемаяФорма** обработки **xddTestRunner.epf**

**Скриншоты**
**snapshot 6.9.5**, где ошибка возникает
![add-snapshot_6 9 5](https://github.com/vanessa-opensource/add/assets/12407761/770f0d0a-b8de-45d4-8a1b-cbd75b933851)

**6.8.0**, где ошибка не возникает
![add-6 8 0](https://github.com/vanessa-opensource/add/assets/12407761/e9857e2b-3876-4757-9a75-fc4f1cc8c856)

**Comment by artbear** [comment]
Исправлено в ПР

**Comment by artbear** [comment]
@lo0p3r Большое спасибо!

И поздравляю с первым ПР в проекте Ванесса-АДД - нашего полку прибыло! УРА!
