### ISSUE TITLE
При `opm run cepf` не удаляются старые epf-бинарники, если для них нет соответствующего каталога с исходниками

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#113]
При `opm run cepf` не удаляются старые epf-бинарники, если для них нет соответствующего каталога с исходниками.

Соответственно, при запуске bdd/tdd используется устаревший бинарник, для которого нет исходников.

Например, 
+ раньше был файл `features\libraries\UITestRunner\step_definitions\ВТаблицеЯПерехожуКСтрокеСодержащейПодстроки.epf`
+ и его исходники в каталоге `features\libraries\UITestRunner\step_definitions\ВТаблицеЯПерехожуКСтрокеСодержащейПодстроки`
+ затем исходники удалили, а вот бинарник остался в каталоге

@pumbaEO @nixel2007 Правильно я помню, что у нас сейчас прямое соответствие между именем бинарники и именем каталога его исходников?
т.е. если бинарник `Обработка1.epf`, то его каталог с исходниками называется `Обработка1`, верно?

Если это верно, тогда предложение:
+ в `opm run cepf` сверяем список каталогов исходников и бинарников
+ все бинарники, для которых нет соответствия, удаляются

/cc @pumbaEO @nixel2007

**Comment by artbear** [comment]
@pumbaEO Возможно, что эта проблема и есть причина того, что сейчас падают девелоп сборки
http://ci.silverbulleters.org/job/ADD%20test/job/develop/57/allure/
Упали те фичи, файлы которых и их epf-шаги я переносил в другое место.

У меня подозрение, что старые epf-файлы остались в workspace и мешают, путая BDD-Раннер

Что скажешь?

**Comment by artbear** [comment]
@pumbaEO Похоже, что эта проблема и есть причина того, что неожиданно стали падать тесты девелоп.
http://ci.silverbulleters.org/job/ADD%20test/job/develop/57/allure/

Упали как раз фичи, перенесенные мной из каталога fea*/lib*/VB

У меня подозрение, что старые epf-файлы от перенесенных исходников остались в каталоге workspace ноды и мешают BDD-раннеру

**Comment by artbear** [comment]
Что скажешь?

**Comment by nixel2007** [comment]
дык добавить в настройки чекаута `clean before checkout`, не?

**Comment by pumbaEO** [comment]
Надо просто на ci удалить папку build, т.к. clean before checkout не добавлял для ускорения при работе с кэшем и сборки внешних обработок.

**Comment by artbear** [comment]
сделали - удалили на обеих нодах

**Comment by artbear** [comment]
Еще был баг https://github.com/silverbulleters/add/issues/184#issuecomment-398320393

**Comment by artbear** [comment]
выполнено.
Теперь перед установкой нового пакета старые файлы удаляются
