### ISSUE TITLE
[BUG] Метод объекта не обнаружен (ПолучитьФормуЛкс)

### ISSUE THREAD

**Issue by johnnyshut** [silverbulleters/add#1140]
**Описание ошибки**
"Метод объекта не обнаружен (ПолучитьФормуЛкс)" при запуске дымовых тестов из ОФ группой

**Сценарий воспроизведения**
1. Открыть обработку "xddTestRunner.epf"
2. Выделить несколько тестов (открытие форм)
3. Нажать "Выполнить выделенные"
4. Ждать
5. Все кроме первого теста не пройдут с ошибкой "Метод объекта не обнаружен (ПолучитьФормуЛкс)"

**Ожидаемое поведение, если бы ошибки не было**
Тест должен попытаться открыть форму

**Окружение:**
    Техническая информация:
	- Версия Vanessa-ADD: ver 6.8.0
	- Имя конфигурации: Управление производственным предприятием, редакция 1.3
	- Версия конфигурации: 1.3
	- Платформа 1С: 8.3.23
	- Режим совместимости (для TestManager): Версия8_3_1
	- Режим запуска: Обычные формы (Толстый клиент)
	- Тип базы: Клиент-серверная ИБ
	- Язык (для TestManager): Русский
	- Локализация (для TestManager): ru

**Дополнительный контекст**

Не типовая
Защита от опасных действий отключена

**Comment by artbear** [comment]
выполнено
