### ISSUE TITLE
Ошибка при запуске bddRunner, если режим совместимости "Не использовать"

### ISSUE THREAD

**Issue by komkov23** [silverbulleters/add#1142]
**Описание ошибки**
``При открытии обработки bddRunner возникает ошибка при загрузке плагина: C:\Program Files\OneScript\lib\add\plugins\ЗагрузчикРасширения.epf
Преобразование значения к типу Число не может быть выполнено
{ВнешняяОбработка.bddRunner.МодульОбъекта(2251)}:Если Число(Элем2) > Число(Элем1) Тогда
{ВнешняяОбработка.bddRunner.МодульОбъекта(2270)}:Возврат ВерсияПриложенияБольшеИлиРавнаЧемЗаданная(ВерсияРежимаСовместимости, НеобходимаяВерсияПриложения);
{ВнешняяОбработка.ЗагрузчикРасширения.МодульОбъекта(155)}:Если Не КонтекстЯдра.ПодходящийРежимСовместимостиПлатформы("8.3.13") Тогда
{ВнешняяОбработка.bddRunner.Форма.УправляемаяФорма.Форма(19140)}:ОписаниеПлагина = ОбъектОбработки.ОписаниеПлагина(ЭтотОбъектНаСервере, Объект.ТипыПлагинов);
[ОшибкаВоВремяВыполненияВстроенногоЯзыка, ОшибкаИспользованияВстроенногоЯзыка]
``
**Сценарий воспроизведения**
1. Устанавливаю по инструкции Vanessa
2. Запускаю 1С версии 8.3.23.2040
3. Открываю обработку bddRunner.epf
4. В сообщениях показывается ошибка

**Ожидаемое поведение, если бы ошибки не было**
нет ошибки

**Скриншоты**
![2024-04-26_101655](https://github.com/vanessa-opensource/add/assets/169043686/2a565cfd-c603-459c-9ee7-f0d5b659f1ce)

**Окружение:**
![2024-05-07_111525](https://github.com/vanessa-opensource/add/assets/169043686/7bf4cd50-6c9f-47c8-a365-0aa0bf4d68d9)
![2024-05-07_131736](https://github.com/vanessa-opensource/add/assets/169043686/fd528534-c062-4b52-837b-401cf07fb3d6)
![2024-05-07_131626](https://github.com/vanessa-opensource/add/assets/169043686/14426fd4-1cfc-41f5-80b9-b40d97667033)

**Дополнительный контекст**
скрины переписки в телеграмм в группе Vanessa OpenSource chat
![IMG_1635](https://github.com/vanessa-opensource/add/assets/169043686/93c3ea90-57e1-4c67-9e51-43cb7566ea3b)
![IMG_1636](https://github.com/vanessa-opensource/add/assets/169043686/b773aaaf-78b2-46bb-a98f-c08e84120f19)
![IMG_1637](https://github.com/vanessa-opensource/add/assets/169043686/41a309db-48ff-4c5a-9afd-5e8f072aa368)
![IMG_1638](https://github.com/vanessa-opensource/add/assets/169043686/c6dfce37-b2af-4342-bfbd-07f3ee048a8f)
![IMG_1639](https://github.com/vanessa-opensource/add/assets/169043686/5f9d36d7-6d5c-4d77-bdc9-61fc23db93a3)
![IMG_1640](https://github.com/vanessa-opensource/add/assets/169043686/57239262-a0e7-4fd1-9239-bbdb26709903)
![IMG_1641](https://github.com/vanessa-opensource/add/assets/169043686/7b76c0f7-c4d0-4945-b3b0-b5b0cd6c89d7)
![IMG_1642](https://github.com/vanessa-opensource/add/assets/169043686/87b7c1ca-cde9-45b9-92bd-3bdb7df8998e)
![IMG_1643](https://github.com/vanessa-opensource/add/assets/169043686/516c06c9-05fe-4358-a321-f924e5cc9b2b)
![IMG_1644](https://github.com/vanessa-opensource/add/assets/169043686/889956c8-cbf8-4ef0-bdc0-ccbaf355d991)
![IMG_1645](https://github.com/vanessa-opensource/add/assets/169043686/4c333d14-24dd-4c40-a70c-d9d5ab93284b)
![IMG_1646](https://github.com/vanessa-opensource/add/assets/169043686/6f6aaf82-2c53-4af8-bea1-0de71e69ea4c)
![IMG_1647](https://github.com/vanessa-opensource/add/assets/169043686/153e71d5-e251-4e79-ae99-b3dee94dce30)
![IMG_1648](https://github.com/vanessa-opensource/add/assets/169043686/79a5a76a-89a1-4a1c-870e-c759317c33ce)
![IMG_1649](https://github.com/vanessa-opensource/add/assets/169043686/4aa4a95a-902a-480a-9261-5dd52970e111)
![IMG_1650](https://github.com/vanessa-opensource/add/assets/169043686/3349ea6a-bec7-409e-97c5-2e718c8d2d9b)
![IMG_1651](https://github.com/vanessa-opensource/add/assets/169043686/9420e2d1-064b-4ecf-a7f8-8d9d6ebf2d3b)

<!-- - Типовая или не типовая конфигурация ?
- Режим защиты от опасных действий выключен

**Comment by artbear** [comment]
Исправлено.
