### ISSUE TITLE
[BUG] bddRunner и xddTestRunner не работают с конфигурациями на английском коде

### ISSUE THREAD

**Issue by ava1c** [silverbulleters/add#1146]
**Описание ошибки**

При попытке открыть обработки bddRunner и xddTestRunner в базе, для которой выбран английский вариант встроенного языка, появляются сообщения об ошибках. Обработки не открываются.

**Причина**

Платформа возвращает свою версию на английском языке, а в модулях обработок анализируется только русский вариант.

**Comment by artbear** [comment]
Реализовано
