### ISSUE TITLE
xddTestRunner - синхронен

### ISSUE THREAD

**Issue by allustin** [silverbulleters/add#138]
если в конфигурации отключен синхронный режим - xddRunner не отрывается

**Comment by artbear** [comment]
Эта проблема уже зарегистрирована https://github.com/silverbulleters/add/issues/5

**Comment by allustin** [comment]
спасибо - буду знать, надо ребятам сказать - у них база с нуля и без синхронного режима

**Comment by artbear** [comment]
В следующем релизе я запланировал поддержка асинхронного режима в xdd
