### ISSUE TITLE
Добавить в FAQ описание Ванесса.ПроверитьХХХ() и хдд.ПроверитьХХХ() в удобочитаемом виде

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#140]

**Comment by allustin** [comment]
Очень просят такую доку - можно воспользоваться наработками Хорева и генерироваться сразу по вхождению `Проверить` в виде markdown, а потом встроенную справку в виде html в макет.

Если такой вариант принимается - я попробую сделать.

**Comment by artbear** [comment]
Хорошее предложение.

А что за наработки от @khorevaa по документированию? разве уже есть решение?

**Comment by allustin** [comment]
@artbear https://xdd.silverbulleters.org/t/avtomaticheskoe-formirovanie-dokumentaczii-iz-ishodnikov/2052/21?u=lustin

**Comment by khorevaa** [comment]
@allustin @artbear  там не то что много наработок.. только парсер  os  файла пока.... я вернусь к нему позже сейчас таки хочу выпустить гитсинк3 в бету... уже все готово. Релизить буду во вторник.

**Comment by artbear** [comment]
Полезный комментарий от @pumbaEO из https://github.com/silverbulleters/add/issues/185#issuecomment-398045240

>В расширение впихнуть, и пусть подсказкой от 1С пользуются

**Comment by artbear** [comment]
Документация дополнена.
Также исправлены различные неверные ссылки.

наконец-то утверждения задокументированы.
УРА!

**Comment by artbear** [comment]
Залил сразу и в девелоп, и в мастер
