### ISSUE TITLE
УФ: не загружается тест в интерактивном режиме

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#144]
В новом сеансе, сначала открываю раннер из add, он выдает ошибку
```
{ВнешняяОбработка.ЗагрузчикФайла.Форма.Форма.Форма(140)}: Ошибка при вызове метода контекста (ПолучитьФорму)
        ФормаОбработки = ПолучитьФорму("ВнешняяОбработка." + ФайлОбработки.ИмяБезРасширения + ".Форма");
по причине:
Неизвестное имя формы. Имя: "ВнешняяОбработка.GetContractAttachements_v2.Форма"
```
Если потом открыть раннер их xUnit, он откроет тест и после этого в этом сеансе раннер из add тоже этот тест открывает

Ветка develop
Автор @yadimetrio

**Comment by yadimetrio** [comment]
Сделал простой тест по аналогии с теми, которые вызвали ошибку. Сразу после создания он открывался в repo\add\build\ib без проблем. Потом после закрытия всех сеансов и чистки кэша 1С, он так же перестал открываться с ошибкой:
`{ВнешняяОбработка.ЗагрузчикФайла.Форма.Форма.Форма(140)}: Ошибка при вызове метода контекста (ПолучитьФорму)
        ФормаОбработки = ПолучитьФорму("ВнешняяОбработка." + ФайлОбработки.ИмяБезРасширения + ".Форма");
по причине:
Неизвестное имя формы. Имя: "ВнешняяОбработка.ТестВМодуле.Форма"`
[ТестВМодуле.zip](https://github.com/silverbulleters/add/files/2035128/default.zip)

**Comment by yadimetrio** [comment]
на 8.3.10.2753 и на 8.3.10.2772 проверял.

**Comment by artbear** [comment]
@yadimetrio Твоя проблема исправлена.
Смотри #146

**Comment by artbear** [comment]
@yadimetrio Нет, не полностью исправлено :(
Тесты такой обработки-теста не выполняются

```
{ВнешняяОбработка.xddTestRunner.МодульОбъекта(817)}: 
Ошибка при вызове метода контекста (Создать)
ОбъектПлагина = ВнешниеОбработки.Создать(Идентификатор, Ложь);
по причине:Ошибка подключения внешних метаданныхпо причине:
Файл не обнаружен 'ТестВМодуле'
```

**Comment by artbear** [comment]
@yadimetrio А вообще для тебя простое и быстрое исправление :)
сделай имя файла и имя обработки одинаковым.
Файл называется `ИмяМодуля.epf`, обработку назови также `ИмяМодуля`, а не как у тебя `Тест__Test`

**Comment by artbear** [comment]
Окончательно исправлено в #182
