### ISSUE TITLE
При первом запуске bdd в базе получаем ошибку

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#154]
```
{ВнешняяОбработка.LoadSettings.Форма.Форма.Форма(110)}: 
Метод объекта не обнаружен (СброситьКешИзвестныхStepDefinition)
			ОбъектЗагрузки.СброситьКешИзвестныхStepDefinition(Неопределено);
```

![image](https://user-images.githubusercontent.com/2920817/40665320-9ebdd854-6365-11e8-93f1-1e08c5a8929b.png)

**Comment by artbear** [comment]
Проблема исправлена в https://github.com/silverbulleters/add/commit/4a496109626d5deda215349a08d97cd20425b73c

**Comment by artbear** [comment]
@leemuar Исправлено.
Будет в релизе.
Сейчас в спец.ветке

**Comment by leemuar** [comment]
Спасибо, оперативно
