### ISSUE TITLE
Обработка для создания файла настроек в формате json для дымовых тестов

### ISSUE THREAD

**Issue by EvgeniyPlevako** [silverbulleters/add#158]
Создал обработку для создания файлов настроек для дымовых тестов.

Ссылка на обработку https://cloud.mail.ru/public/FAqA/iDfcSsFuU

Краткая инструкция по созданию файла настроек для дымовых тестов
1.	Для заполнения таблицы метаданных необходимо нажать кнопку «Заполнить дерево метаданных»
 
![image](https://user-images.githubusercontent.com/22676142/40837759-34b9d0de-65a4-11e8-85db-fde849e60f18.png)

Для того чтобы исключить формы из проверки необходимо поставить галочки у таких форм (пока не реализована возможность указывать конкретные формы, такие как форма группы,форма выбора и т.д.)
Если необходимо заполнить значение реквизитов новых, встаем на нужный справочник или документ и в нижней таблице указываем нужные реквизиты
 
![image](https://user-images.githubusercontent.com/22676142/40837769-44821ca6-65a4-11e8-9a25-65ed75a13e0c.png)

При создании файла настроек значение реквизита, будет заменено на наименование для ссылочных реквизитов или значение перечисления.
 После того как все настройки сделаны, жмем на кнопку Создать файл настроек.
Если нужно отредактировать существующий файл, нажимаем «Загрузить файл настроек», дерево метаданных и значения реквизитов новых будут заполнены данными из файла, после чего их можно отредактировать и сохранить в файл.

[СозданиеФайлаНастроекДляДымовыхТестов.zip](https://github.com/silverbulleters/add/files/2067511/default.zip)

**Comment by artbear** [comment]
Нужная вещь, спасибо!
Обязательно добавлю в проект.

**Comment by artbear** [comment]
@EvgeniyPlevako Взял в работу, скоро выложу.
Сделал более универсальным, т.к. у тебя зависит от конфигураций на БСП
загрузку настроек меняю и т.п.

**Comment by artbear** [comment]
Выполнено.
@EvgeniyPlevako большое спасибо!
