### ISSUE TITLE
Ошибка открытия xddTestRunner на 8.2 - ЭтотОбъект

### ISSUE THREAD

**Issue by leemuar** [silverbulleters/add#159]
платформа 8.3.7.2027
режим совместимости 8.2.16
---

Когда я открываю интерактивно обработку xddTestRunner.epf
Тогда появляет окно ошибки с текстом "Переменная не определена (ЭтотОбъект)"

Возможно связано с https://infostart.ru/public/263289/

![image](https://user-images.githubusercontent.com/5869791/40840847-071c505e-65b1-11e8-8bf1-658e82f67f0c.png)

![image](https://user-images.githubusercontent.com/5869791/40840899-3d37bed0-65b1-11e8-93cc-4e3bd12a41c5.png)

**Comment by artbear** [comment]
Исправлено в ветке девелоп
