### ISSUE TITLE
Ошибка: Класс не зарегистрирован

### ISSUE THREAD

**Issue by bessonovevgen** [silverbulleters/add#163]
Windows server 2012 r2

Платформа x64

> Платформа: 1С:Предприятие 8.3 (8.3.12.1440)
Конфигурация: 1С:ERP Управление предприятием 2 (2.4.2.144) (http://v8.1c.ru/erp/)
Copyright © ООО "1C-Софт", 2004-2018. Все права защищены
(http://www.1c.ru)
Режим: Серверный (сжатие: усиленное)
Приложение: Тонкий клиент
Локализация: Информационная база: русский (Россия), Сеанс: русский (Россия)
Вариант интерфейса: Такси

> Ошибки:
> --------------------------------------------------------------------------------
> 05.06.2018 18:03:58
{ВнешняяОбработка.ТестКлиенты.Форма.Форма.Форма(137)}: Ошибка при вызове конструктора (COMОбъект)
			Scr = Новый COMОбъект("MSScriptControl.ScriptControl");
по причине:
-2147221164(0x80040154): Класс не зарегистрирован 

![2018-06-05_18-11-56](https://user-images.githubusercontent.com/18403194/40985202-4722be66-68ec-11e8-8a5c-df6c986fdfe8.png)
![2018-06-05_18-11-07](https://user-images.githubusercontent.com/18403194/40985203-4747e7d6-68ec-11e8-8bdb-cef57192d98d.png)

**Comment by artbear** [comment]
https://github.com/silverbulleters/add/pull/589
