### ISSUE TITLE
HELP: smoke - Общие формы и формы отчетов

### ISSUE THREAD

**Issue by allustin** [silverbulleters/add#167]
Сейчас часто появляется вот такая конструкция при выполнении дымовых тестов

"{ОбщаяФорма.ФормаНастроекОтчета.Форма(31)}: Не передан служебный параметр ""НастройкиОтчета"".

нужно задокументировать как тестировать подобное в стиле дымовых тестов

**Comment by artbear** [comment]
исправлено в 6.4.0 https://github.com/silverbulleters/add/pull/589
