### ISSUE TITLE
Проблема с подстановкой правильных путей к шага фич, проблема с кешем

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#17]
что-то новая версия ВБ из девелопа очень хреново работает с шагами фич.

один раз открываешь фичу, шаги показаны как реализованные или не реализованные, нажимаешь Перезапустить или вручную переоткрываешь ВБ, состояние шагов меняется на обратное.
Иногда при каждом переоткрытии, иногда не сразу.

это касается как библиотечных шагов, так и своих шагов.
Пару раз мне даже сгенерился файл шагов со вставкой нереализованных библиотечных шагов в мой файл :(

Чистка кеша помогает не всегда :(

вчера реально задолбало такое поведение

**Comment by artbear** [comment]
Исследовал проблему, практически выяснил
У меня каталог библиотек ВБ указаны как `$instrumentsRoot/features/libraries`

Это значение никак не преобразовывается и далее используется в коде в разных местах.

Например, при поиске кеша идет попытка искать файл как раз по пути `$instrumentsRoot/features/libraries`, которого, естественно, не существует :(

**Comment by pumbaEO** [comment]
Сохранение в настройках именно instrumentsRoot/features/libraries сделано специально, т.к. если развернуть путь и потом скопировать базу, тогда в библиотеках будет по умолчанию какой-то абсолютный путь к неизвестной папке. 
Поэтому именно для библиотек при загрузке не сделанно разворачивание в полный путь, а везде где используются библиоетки сделано преобразование конечное. 

Поэтому я бы советовал тогда именно при поиске кеша сделать преобразование к нормальному пути.

**Comment by artbear** [comment]
Естественно, так и сделано в моем исправлении, которое я сейчас проверяю

**Comment by artbear** [comment]
Исправлено.
