### ISSUE TITLE
Тех.долг - ненужные циклы по Объект.КаталогиБиблиотек

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#18]
В модуле Упр.формы ВБ есть много кусков кода с циклом по Объект.КаталогиБиблиотек
~~а внутри цикла элемент цикла не используется~~
~~т.е. ты цикл на самом деле не нужен :(~~
уточнение https://github.com/silverbulleters/add/issues/18#issuecomment-341400323

```bsl
		Для каждого Библ Из Объект.КаталогиБиблиотек Цикл
			Ном = Ном + 1;
			
			МассивДляПоискаДублейФайлов = ПолучитьМассивДляПоискаДублейФайлов(МассивФайлов);
			
			МассивФайловБиблиотека = ПолучитьЗначениеПоРанееСобраннойИнформации(ДополнительныеПараметры, "БиблиотекаФич" + Ном, "НайденныеФайлы");
			Для каждого Элем Из МассивФайловБиблиотека Цикл
				Если МассивДляПоискаДублейФайлов.Найти(Элем.Файл.ПолноеИмя) <> Неопределено Тогда
					Продолжить;
				КонецЕсли;	 
				
				МассивФайлов.Добавить(Элем);
				
			КонецЦикла;
		КонецЦикла;
```

**Comment by nixel2007** [comment]
> т.е. ты цикл на самом деле не нужен :(

как это не нужен? Библиотек может быть несколько же

**Comment by artbear** [comment]
@nixel2007  а ты код посмотрел??
В нем переменная `Библ` (счетчик цикла) вообще не юзается.
Тогда зачем эта переменная и этот цикл вообще нужны?

**Comment by artbear** [comment]
выполнено
