### ISSUE TITLE
Ошибка при выполнении части тестов xddTestRunner

### ISSUE THREAD

**Issue by 1cgh** [silverbulleters/add#182]
Ситуация: сейчас используется xUnitFor1C 4.1.0.1
Проверяю имеющиеся unit-тесты на 5.1.0.0 из ADD.
ADD установлена через opm install add
Запуск пока тупо руками: открываем
Платформа 1С 8.3.10.2667

В дерево подгружаются все тесты, которые и должны.
Но при выполнении на части тестов получаем ошибку вида
`{ВнешняяОбработка.xddTestRunner.МодульОбъекта(866)}: Ошибка при вызове метода контекста (Создать)			ОбъектПлагина = ВнешниеОбработки.Создать(Идентификатор, Ложь);по причине:Ошибка подключения внешних метаданных по причине:Файл не обнаружен 'тесты_ИмяТеста'`

Причем, повторюсь, это не на всех тестовых обработках, а только на части из них.

**Comment by artbear** [comment]
@1cgh Подозреваю, что у тебя имя файла и имя обработки отличаются.
сделай имя файла и имя обработки одинаковым.

Например, у коллеги была проблема
`Файл называется ИмяМодуля.epf, обработку назови также ИмяМодуля, а не как у тебя Тест__Test`

**Comment by artbear** [comment]
@1cgh А ты проверял на новом релизе add 5.1, выпущен 15.06  ?
Там подобная ошибка уже исправлена

**Comment by artbear** [comment]
Вот исходный и решенный баг https://github.com/silverbulleters/add/issues/144

**Comment by 1cgh** [comment]
@artbear проверял вчера, add свежая с хаба для opm

**Comment by artbear** [comment]
тогда сделай как в https://github.com/silverbulleters/add/issues/182#issuecomment-397946933

**Comment by 1cgh** [comment]
@artbear да, при совпадении имени файла и имени обработки всё ок. спасибо
но получается, что баг не решен, или в хабе что-то не то лежит

**Comment by artbear** [comment]
Да, значит, буду решать проблему для этого ишуза.

**Comment by artbear** [comment]
![image](https://user-images.githubusercontent.com/2920817/41529812-f9c92730-72f6-11e8-968f-96d8b6c41e22.png)

**Comment by artbear** [comment]
Пока что я добавил спец.подсказку https://github.com/silverbulleters/add/commit/f56fc05ed2a1175835cd49ec633c1a73497f76a4
о различии имени файла и имени обработки, чтобы пользователи сразу видели возможное решение проблемы.

На ближайшее время этой подсказки должно хватить :) 

Убираю ишуз из текущего  релиза, будем решать по мере поступления жалоб!

@1cgh @vladfrost если вас не устраивает такое решение, пишите, обсудим

**Comment by artbear** [comment]
Вот теперь эта проблема точно исправлена.

Аналогично исправлено поведение bdd #216 

@1cgh @VladFrost проверьте по возможности.
