### ISSUE TITLE
Задвоение шагов "втаблицеяперехожукстрокесодержащейподстроки"

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#184]
```
Обновил релиз ADD. 
При загрузке фичи выдает ошибку:
Снипет "втаблицеяперехожукстрокесодержащейподстроки" встречается 2 раз!
C:/Program Files (x86)/OneScript/lib/add/features/libraries/UITestRunner/step_definitions/ВТаблицеЯПерехожуКСтрокеСодержащейПодстроки.epf
C:/Program Files (x86)/OneScript/lib/add/features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом.epf
```
Автор @asheichenko
https://gitter.im/silverbulleters/vanessa-behavior?at=5b277d09f41ea926bc8bfd91

**Comment by artbear** [comment]
@asheichenko 12:58
>@artbear Пока закомментировал шаг в обработке ВТаблицеЯПерехожуКСтрокеСодержащейПодстроки.epf

**Comment by asheichenko** [comment]
Возможно это связано с ошибкой установки, в оригинальном репо нет этой обработки. При установке opm update -all у меня зависла установка библиотеки opm и сейчас выдает ошибку:
Script file is not found 'C:\Program Files (x86)\OneScript\lib\opm\src\opm.os'
Как это починить?

**Comment by artbear** [comment]
@asheichenko если ты еще не разобрался, 
посмотри обсуждение в https://gitter.im/EvilBeaver/oscript-library?at=5b275ac79a211e26bb6b4860 и далее
там аналогичная проблема.

Кратко - скорее всего, тебе нужно переустановить/установить новый/последний движок и сделать штатное обновление библиотек

**Comment by artbear** [comment]
>Возможно это связано с ошибкой установки, в оригинальном репо нет этой обработки. 

А ты прав, что-то у тебя не так.

Сбрось кеш в bddRunner (на закладке сервис) и снова перезапусти bddRunner

**Comment by asheichenko** [comment]
Попробовал обновить весь пакет, обработка **ВТаблицеЯПерехожуКСтрокеСодержащейПодстроки.epf** осталась в этом каталоге. Поэкспериментировал: убрал эту обработку и **ФильтрФормыСпискаЭкспорт.epf**, запустил команду opm update add, обработка **ВТаблицеЯПерехожуКСтрокеСодержащейПодстроки** не появилась, а **ФильтрФормыСпискаЭкспорт** добавилась. Может тогда при обновлении предусмотреть очистку каталогов, возможно по  какому то флагу, чтобы такие артефакты как **ВТаблицеЯПерехожуКСтрокеСодержащейПодстроки** не оставались?

**Comment by artbear** [comment]
>Может тогда при обновлении предусмотреть очистку каталогов, возможно по какому то флагу, чтобы такие артефакты как ВТаблицеЯПерехожуКСтрокеСодержащейПодстроки не оставались?

@asheichenko Да, спасибо за кейс и его решение.

Не помню поведение `opm install add` или `opm update add`, связанное с очисткой.
Уточняю.

**Comment by artbear** [comment]
Да, есть проблема при установке с очисткой файлов.
Связано с https://github.com/oscript-library/opm/issues/116

Будем исправлять.
Создал новый ишуз https://github.com/silverbulleters/add/issues/192, в рамках которого и будем решать.
А текущий связываю с созданным и закрываю
