### ISSUE TITLE
Задокументировать ассерты

### ISSUE THREAD

**Issue by allustin** [silverbulleters/add#185]
люди жалуются что неудобно искать в модулях и плагинах

**Comment by allustin** [comment]
@artbear генератор може какой применить ?

**Comment by artbear** [comment]
Может быть, присматривался к разным, пока ничего не нашел подходящего.

Может быть, @nixel2007 @evilbeaver @pumbaEO @khorevaa @dmpas подскажут правильный ?

**Comment by pumbaEO** [comment]
В расширение впихнуть, и пусть подсказкой от 1С пользуются

**Comment by artbear** [comment]
Дубль https://github.com/silverbulleters/add/issues/140
