### ISSUE TITLE
Перенести документацию на новые возможности дымовых тестов в УФ - группировки и вот это все

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#186]
@kuntashov

**Comment by artbear** [comment]
@kuntashov Саша, мне казалось, что я переносил :(

**Comment by kuntashov** [comment]
@artbear так и есть, нашел здесь: https://github.com/silverbulleters/add/tree/master/tests/smoke

Просто в xUnitFor1C на нее ссылка на заглавной вики стоит, и я из-за этого думал, что и сама документация в вики, а у ADD вики пустая.

Подправлю пост в телеграме (ты же из-за него issue сделал?).
Закрывай )

**Comment by allustin** [comment]
@kuntashov телеграм ?

**Comment by kuntashov** [comment]
@allustin про мой канал, конкретно вот про этот пост https://t.me/kuntashov_devnotes/145

**Comment by allustin** [comment]
@kuntashov подписался - не знал.

**Comment by artbear** [comment]
Ага, спасибо.
Закрываю.

Да, узнал через телеграм
