### ISSUE TITLE
Ошибка: реквизит недоступен для группы

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#188]
Ошибка выявлена на 5.1.0.0

![image](https://user-images.githubusercontent.com/2920817/41581952-eb332f06-73a8-11e8-8701-6d6fd12816ed.png)

**Comment by allustin** [comment]
ситуация воспроизводится когда

* вначале ревизит был доступен для группы
* потом его заполнили
* после чего поменяли режим на "Для элемента"
* платформа его не очищащет из базы и старое значение сохраняется
* генератор макетов его может выгрузить
* загрузить уже невозможно
* очистить в базе невозможно

прикольное поведение

**Comment by pumbaEO** [comment]
Ну так стандарты для того и придуманы, что-бы назвать "УдалитьКомментарий",  добавить Комментарий для элемента, перезаполнить и т.д.

**Comment by artbear** [comment]
Леша, интересный кейс, не знал о таком поведении.

**Comment by artbear** [comment]
Выполнено
