### ISSUE TITLE
Отсутствует экранирование "\n" в снипете ТаблицаСталаРавной(Парам01,ТабПарам)

### ISSUE THREAD

**Issue by kuzyara** [silverbulleters/add#196]
При сравнении табличного поля на форме с эталоном, в эталоне съедается \n и \\".

> 21.06.2018 11:11:41 {ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(4280)}: Таблица Список. Строка № 1. Колонка Сообщение. Ожидали <{
>     "ДатаВремяОшибки": "2018-06-21T10:11:23.000Z",
>     "КлючМаршрутизации": "discount.goods",
>     "ТочкаПубликации": "flood.fit.adviser",
>     "ТекстОшибки": "42P10: нет уникального ограничения или ограничения-исключения, соответствующего указанию ON CONFLICT",
>     "Сообщение": "{\r
> "CodeNSI": "NSIN0013720356",\r
> "CodeGroopGoods": "2120",\r
> "Brand": "504",\r
> "DateBegin": "2015-03-16T17:00:00",\r
> "DateEnd": "",\r
> "Price": "561.99",\r
> "SaleType": "1",\r
> "isDeleted": "false",\r
> "SaleCode": "ОТ000000801",\r
> "headers": {\r
> "timestamp": 1518089482735\r
> }\r
> }"
> }>, а получили <{
>     "ДатаВремяОшибки": "2018-06-21T10:11:23.000Z",
>     "КлючМаршрутизации": "discount.goods",
>     "ТочкаПубликации": "flood.fit.adviser",
>     "ТекстОшибки": "42P10: нет уникального ограничения или ограничения-исключения, соответствующего указанию ON CONFLICT",
>     "Сообщение": "{\r\n\"CodeNSI\": \"NSIN0013720356\",\r\n\"CodeGroopGoods\": \"2120\",\r\n\"Brand\": \"504\",\r\n\"DateBegin\": \"2015-03-16T17:00:00\",\r\n\"DateEnd\": \"\",\r\n\"Price\": \"561.99\",\r\n\"SaleType\": \"1\",\r\n\"isDeleted\": \"false\",\r\n\"SaleCode\": \"ОТ000000801\",\r\n\"headers\": {\r\n\"timestamp\": 1518089482735\r\n}\r\n}"
> }>
> 
> Технические данные:
>         ИмяФайла: C:\git\add_\features\libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf
>         ИмяПроцедуры: ТаблицаСталаРавной
>         ВерсияVB: ver 5.1.0.0
>         ВерсияПлатформы: 8.3.12.1469
>         РежимСовместимостиTestManager: НеИспользовать

Решил заменой "\\" на "\\\\"
![2018-06-21_11-59-48](https://user-images.githubusercontent.com/2604430/41698837-bee28a02-754a-11e8-8d57-bea8df079481.png)

То же и в Исследователе формы.

**Comment by artbear** [comment]
Спасибо!

Очень интересно, воспользуюсь такой доработкой.

**Comment by artbear** [comment]
@kuzyara Смотрю на твой пример и вижу, что оба примера данных ущербны

Приведи пример исходных данных и пример, как они выглядят в табличном поле.
Желательно текстом.

Думаю, станет понятней и я включу эту доработку в ближайший релиз, который хочу выпустить на этой неделе.

**Comment by artbear** [comment]
Почему закрыл? Что не так?
