### ISSUE TITLE
Найти и перенести файлы, которые различаются в VB и VB2

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#20]
- [x] Проверить `md`
- [ ] Проверить `feature`
- [ ] Проверить `bsl`
- [ ] Проверить `json`
- [x] Проверить файлы из корня репозиториев

**Comment by pumbaEO** [comment]
Проверить json - можно и не проверять, там однозначно біли изменения с учетом ./build/*

**Comment by artbear** [comment]
Т.е. все json-файлы ты проверил, верно?

**Comment by pumbaEO** [comment]
нет, я их практически все менял. diff не поможет понять, что там изменилось.

**Comment by artbear** [comment]
устарело.
