### ISSUE TITLE
Инструкция по ручной установке не актуальна/ошибочна

### ISSUE THREAD

**Issue by kuntashov** [silverbulleters/add#210]
В инструкции "Ручная установка" написаны шаги:

> Перейти в раздел релизы
> Скачать архив с последним стабильным релизом - прямая ссылка Releases
> Распаковать архив.

При этом там не указано, что скачивать нужно *.ospx (а не файлы с исходниками, которые нужно будет собирать), а распаковывать, нужно дважды: сначала ospx, затем content.zip

Не каждый пользователь догадается, что ospx - просто архив.
Нужно либо дополнить документацию информацией о том, какой файл скачивать и как распаковывать, а лучше в состав релизов включить традиционный (не ospx) архив с готовым к использованию инструментом.

**Comment by artbear** [comment]
Спасибо, Исправим

**Comment by artbear** [comment]
Добавлено создание файла релиза add-x.x.x.zip при сборке пакета продукта
