### ISSUE TITLE
Непроходят тесты на серверных базах

### ISSUE THREAD

**Issue by KrapivinAndrey** [silverbulleters/add#214]
Платформа: 8.3.10.2580
Конфигурация: УТ 11.3.2.218
VRunner 1.2.0

База на сервере предприятий.
Ошибка вот здесь https://github.com/silverbulleters/vanessa-runner/blob/eda518f54edda15f418fae5fd1b7971fca0c5d06/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B0.os#L299

Процесс создается и сразу имеет статус Завешен. Поэтому не дожидается завершения тестов, не формируется BuildStatus.log. Выполнение помечается как ошибочное.

**Comment by artbear** [comment]
очень странная проблема.

Не наблюдал такой проблемы.

@KrapivinAndrey Можешь включить полную отладку скриптов OneScript и запустить еще раз vanessa-runner.
и лог выложи.
можно лог в личку.

**Comment by KrapivinAndrey** [comment]
Есть подозрение что эта ошибка тоже самое:
https://xdd.silverbulleters.org/t/pri-paketnom-zapuske-ne-zagruzhayutsya-i-ne-vypolnyayutsya-fichi-otkryvaetsya-tolko-bddrunner/2132

Сейчас придет владелец тестов и проверим

**Comment by artbear** [comment]
Удалось проверить?

чт, 5 июл. 2018 г., 9:29 Andrey <notifications@github.com>:

**Comment by KrapivinAndrey** [comment]
Пока нет... он уже поменял инфраструктуру на файловые базы.

**Comment by artbear** [comment]
Я проверил последнюю текущую версию из develop на серверной базе, клиент и сервер находятся на  разных машинах.

все в порядке, работает и  bdd, и tdd

Закрываю ишуз!

PS @KrapivinAndrey Для подтверждения проблемы дай еще информации.
Тогда возобновлю работу по ишузу

**Comment by ArtemKarsakov** [comment]
Отмечусь здесь как владелец тестов)
Попробовал сегодня воспроизвести, не удалось, тесты на серверной базе запустились и прошли успешно. С момента первых тестов мы обновили add и vrunner.

**Comment by artbear** [comment]
@ArtemKarsakov Отлично.

Спасибо за добрые вести :)
