### ISSUE TITLE
Генерация обработки для шаго не согласуется с подключением обработки в режиме выполнения

### ISSUE THREAD

**Issue by pumbaEO** [silverbulleters/add#216]
```Gherkin
Функционал: Генерация фичи из воздуха
   Как Прогрммист
   Я хочу генерить файл epf для подключения шагов

Сценарий: Генерация epf и последующее его выполнение с исключением, т.к. нет реализации кода шагов
  Допустим есть файл feature с наименованием "Моя супер фича из воздуха.feature'
  Когда Нажимаем сгенирить файл epf
  Тогда создается в файл epf с именем "Моя супер фича из воздуха.epf" и внутреннем именем "Моя_супер_фича_из_воздуха"
  И не получаем список шагов, т.к. обработку подключает по имени "Моя супер фича из воздуха"
```
Необходимо дать возможность управлять нормально флагом асинхронного помещения внешней обработки, т.к. не всегда даже если сервер и клиент на одной машинке, у пользователя сервера не может біть прав на доступ к обработке пользователя клиента.

**Comment by artbear** [comment]
Подробное описание проблемы есть также в https://xdd.silverbulleters.org/t/bddrunner-ne-vidit-shag-realizovannyj-vo-vneshnej-obrabotke/2147/5

**Comment by artbear** [comment]
Проблема исправлена.

Аналогично исправлено поведение xdd #182 

@pumbaEO  проверь по возможности.

**Comment by pumbaEO** [comment]
Немного не согласен с решением, вроде как достаточно правильно было файл назвать при генерации и ошибка была-бы для последующих случаев исправленна.

**Comment by artbear** [comment]
Остается вопрос с совместимостью для уже сгенерированных файлов.

Мой вариант решает проблему с совместимостью.
Твое дополнение улучшает работу с новыми файлами,

но человеку все-таки проще работать с именами файлов без спец.символов типа подчеркиваниями

Может быть, оставим вариант "человеческих" имен файлов обработок?

@allustin @nixel2007 @kuntashov что скажете?

**Comment by artbear** [comment]
PR #239 принят.
Текущий ишуз выполнен.

**Comment by nixel2007** [comment]
Я вообще не понимаю, зачем для обычных шагов требовать совпадение имени обработки и имени файла. Есть какое-то разумное объяснение? Кроме использования макетов?

**Comment by artbear** [comment]
в связи с особенностями поведения 1С - при подключении внешних обработок по умолчанию их идентификатором является имя обработки, а не файла.
Часто это вызывает проблемы - в АДД ранее, в ЕДТ и т.п.

сейчас в АДД мной это исправлено.
А Женя еще усилил это правило - генерирует нормализованное имя файла, чтобы никогда больше не возникло подобных проблем :)

**Comment by nixel2007** [comment]
Ааа, я не правильно понял. Я думал, что сравнивается имя файла фичи, а не имя файла обработки. Вопрос снимается
