### ISSUE TITLE
Ошибка при загрузке элемента справочника у которого есть реквизит со свойством "Использовать - для группы"

### ISSUE THREAD

**Issue by asheichenko** [silverbulleters/add#218]
Версия генератора макета данных 5.1.1.0
Платформа 8.3.10.250
       При загрузке элемента справочника у которого есть реквизит с установленным свойством "Использовать - Для группы" выдает ошибку:
`{ВнешняяОбработка.СериализаторMXL.МодульОбъекта(1333)}: Ошибка при вызове метода контекста (ЗаполнитьЗначенияСвойств)
		ЗаполнитьЗначенияСвойств(Рез, НовыйПустойОбъект, , СтрокаРеквизитов);
по причине:
Ошибка установки значения свойства 'РеквизитДляГруппы'
по причине:
Реквизит недоступен для элемента` 
Видимо надо такие реквизиты для элементов добавлять в список пропускаемых реквизитов.

**Comment by asheichenko** [comment]
Нашел исправлено для ветки develop

**Comment by artbear** [comment]
Да, исправлено.
В ближайшее время выпущу релиз.
