### ISSUE TITLE
Возможно ли данные созданные на шаге "И я создаю fixtures по макету..." сохранять в контекст?

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#224]
**Существует проблема**
Нельзя переиспользовать данные, созданные из макета, в других шагах.
Приходится делать доп.поиск созданных данных

**Хотелось бы иметь следующую функциональность**
Варианты реализации  
- автоматически сохранять созданные данные из этого шага в контекст
- сделать доп.шаг `И я загружаю данные из макета и помещаю их в контекст`

**Comment by yadimetrio** [comment]
Для себя делал шаг "я загружаю данные из макета "ИмяМакета" и запоминаю как "ИмяПеременной"" это если макет для какой то одной сущности, типа "КонтрагентБезДоговоров", "СчетНаОплатуСОднойСтрокой" и т.д. В самом макете может быть любое количество переменных, но обязательно должна быть переменная "Ссылка", именно она и сохраняется в контексте. Но для общих случаев, наверное, не удобно будет такое требование.

**Comment by asheichenko** [comment]
Может добавить для макета колонку типа "СохранятьВКонтекст", в которой заполнять имя переменной, которую мы хотим помещать в контекст?

**Comment by artbear** [comment]
Выполнено в #279
