### ISSUE TITLE
add\features\libraries\Макеты\step_definitions\СуществованиеЭлементов.epf - ошибка в процедуре Процедура ЯУдаляюВсеЭлементыСправочникаСервер

### ISSUE THREAD

**Issue by PavelVir** [silverbulleters/add#230]
**Описание ошибки**

Шаг "Когда я удаляю все элементы Справочника" в котором нет иерархии выдает ошибку:
"Поле не найдено ЭтоГруппа"

**Сценарий воспроизведения**
Шаги по воспроизведению:
Сделать сценарий с удалением элементов справочника без иерархии

**Ожидаемое поведение если бы ошибки не было**
 
очевидно - удаление элементов

**Скриншоты**

![default](https://user-images.githubusercontent.com/40602668/42424007-af7d8c9a-830c-11e8-89b2-3c14e4170543.png)

![default](https://user-images.githubusercontent.com/40602668/42424010-c39eef8e-830c-11e8-9eeb-d2d682e1e84a.png)

**Окружение:**
 - Версия операционной системы: win 10
 - Редакция 1С платформы [например 8.3.12.1542]
 - Версия ADD последняя
 - Версия OScript последняя

**Дополнительный контекст**

Конфигурация ERP 2.2 Справочник нетиповой

**Comment by artbear** [comment]
выполнено
