### ISSUE TITLE
В библиотечном шаге "И я буду выбирать внешний файл "ИмяФайла"" хотелось бы использовать переменный контекста для удобства создания тестов

### ISSUE THREAD

**Issue by PavelVir** [silverbulleters/add#238]
**Описание ошибки**
В библиотечном шаге "И я буду выбирать внешний файл "ИмяФайла"" хотелось бы использовать переменный контекста для удобства создания тестов

**Сценарий воспроизведения**

Шаги по воспроизведению:
1. Добавить шаг "И я буду выбирать внешний файл  '"'E:/DOCUMENTS/' + $ИмяФайла$"
2. И я нажимаю на кнопку 'Выбрать файл'

Выбивает ошибку что путь E:/DOCUMENTS/$ИмяФайла$ не найде, т.е. не происходит замена переменной контекста

**Ожидаемое поведение если бы ошибки не было**

Выбрался файл по указанному пути с подстановкой значения из переменной

**Скриншоты**

Предлагаю заменить конструкцию в процедуре 
ЯБудуВыбиратьВнешнийФайл (\add\features\libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf) на вызов функции из Ванесссы
![default](https://user-images.githubusercontent.com/40602668/42685229-1796f6ae-869b-11e8-800c-6c204dd6b16b.png)

	Если СтрНайти(ИмяФайла,"$") <> 0  Тогда //есть переменные
		ИмяФайла = Ванесса.ВычислитьВнутреннееВыражение(ИмяФайла);	
	КонецЕсли;
			

**Окружение:**
 - Версия операционной системы: [например WIN 10]
 - Редакция 1С платформы [например 8.3.12.1542]
 

**Дополнительный контекст**

**Comment by artbear** [comment]
@PavelVir Согласен с твоим предложением.

Сделаешь пулл-реквест?

**Comment by PavelVir** [comment]
Чтобы Вы понимали - я гит поставил дня 4 назад :) поэтому это может занять немного больше времени :) 
Особенно если это еще покрыть тестом надо

**Comment by artbear** [comment]
Выполнено в #240
