### ISSUE TITLE
ОФ: Запуск конкретных фич ADD в обычных формах

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#252]
**Хотелось бы иметь следующую функциональность**
Сейчас для УФ это реализовано, а вот в ОФ не работает
При запуске команды
```cmd
vrunner vanessa --settings tools\json\vrunner.json --ordinaryapp 1
--path features\libraries\Пауза\СделатьПаузу.feature
```
Запускаются все фичи из файла `vrunner.json`, а не одна фича

Связано с https://github.com/silverbulleters/add/issues/129

**Comment by ZhdanovR** [comment]
@artbear Изучил проблему. Дело заключается в том, что обычная форма не умеет подтягивать настройки из LoadSettings, а именно нужно уметь читать праметры окружения, а переопределение каталогаФич производится именно таким способом
Решения 2: 
- Копипастить клиентский код из управляемой формы в модуль объекта.
- Писать отдельный плагин по работе с параметрами окружения, причем затачивать его на одновременную работу как с обычными так и с управляемыми формами.

**Comment by artbear** [comment]
@ZhdanovR Да, проблема именно в отсутствии чтения переменных окружения.
лучший способ - сделать код модуля объекта плагина аналогичным модулю УФ

**Comment by artbear** [comment]
устарело.неактуально.закрываю.
