### ISSUE TITLE
Скопировать описание создания видео-инструкций из справки bddRunner в markdown-документацию

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#253]
в файл MakeAutoVideo

**Comment by ZhdanovR** [comment]
@artbear готово.

**Comment by ZhdanovR** [comment]
Хотя есть спорные моменты. В мануале говориться о установке VLC версии 2.1.5 - почему?
Я установил актуальную с choco - полет нормальный

**Comment by artbear** [comment]
уже выполнено
