### ISSUE TITLE
Исправить важные проблемы, выявленные Сонаром

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#255]
+ Все важные https://opensonar.silverbulleters.org/project/issues?id=add&resolved=false&types=BUG
+ или добавленные важные https://opensonar.silverbulleters.org/project/issues?id=add&resolved=false&sinceLeakPeriod=true&types=BUG

**Comment by allustin** [comment]
проект перенесен на opensonar

http://opensonar.silverbulleters.org/dashboard?id=add

**Comment by allustin** [comment]
перевел на jenkins сборку с поддержкой нового сервера - master и develop

@artbear - картина кстати в целом не сильно радужная, в том числе и с новым кодом.

вот мастер и его динамика за месяц https://opensonar.silverbulleters.org/dashboard?id=add

вот develop относительно мастера https://opensonar.silverbulleters.org/project/issues?branch=develop&id=add&resolved=false

**Comment by allustin** [comment]
![default](https://user-images.githubusercontent.com/55323/44500469-3b4a6480-a691-11e8-9341-4697b20d5b91.png)

@artbear @pumbaEO @KrapivinAndrey @ZhdanovR 

Я пока не докрутил issue report - sonarQube его перевел в Developer Edition, мне понадобится время чтобы разобраться как его прикручивать в новой редакции. Поэтому просьба - посматривайте периодически https://opensonar.silverbulleters.org/project/issues?authors=zhdanovr%40users.noreply.github.com&id=add&resolved=false

с отбором по автору ;-)

**Comment by JohnyDeath** [comment]
А вот кстати почему сонар так и ругается на, например, "ПриСозданииНаСервере"
![image](https://user-images.githubusercontent.com/5936030/44545371-9164e980-a71d-11e8-9b72-bab62e56efd3.png)

**Comment by JohnyDeath** [comment]
Аналогично обработчики команд формы:
![image](https://user-images.githubusercontent.com/5936030/44545447-bd806a80-a71d-11e8-8ece-b296464eb453.png)

Сколько сразу лишних (=ложных) срабатываний уйдет

**Comment by allustin** [comment]
@JohnyDeath а я контекст исполнения НЕ настроил - пока только закончил CI

**Comment by artbear** [comment]
Исправлено очень много ошибок.
например, в основном проекте (ветка мастер) на Сонаре ОЧЕНЬ много ошибок
![image](https://user-images.githubusercontent.com/2920817/45511370-85f96100-b7a5-11e8-8539-4afc5e3cbb14.png)

А вот состояние ветки девелоп - немного в другом виде из-за особенностей реализации модулей в Сонаре
![image](https://user-images.githubusercontent.com/2920817/45511463-bb9e4a00-b7a5-11e8-98bc-908b2cf3b68e.png)

Видно, что общее число проблем *меньше почти на порядок* !
