### ISSUE TITLE
Ошибка в обработке РаботаСВидео.epf 

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#257]
Ошибка в обработке РаботаСВидео.epf 
вызывается скрипт 
`oscript "c:\Program Files (x86)\OneScript\lib\add\tools\onescript\StopVideoRec.os" 127.0.0.1:8082` без кавычек.
Источник @JohnnyViper

**Comment by ZhdanovR** [comment]
@artbear Имеется в виду это
`"oscript " + ПараметрыВидео.КаталогИнструментов + "\tools\onescript\StopVideoRec.os """ + АдресСокета + """";`
изменить на это?
`"oscript """ + ПараметрыВидео.КаталогИнструментов + "\tools\onescript\StopVideoRec.os"" " + АдресСокета;`

**Comment by artbear** [comment]
Исправлено в https://github.com/silverbulleters/add/pull/259
