### ISSUE TITLE
Не загружаются наборы записей регистра накопления из макета

### ISSUE THREAD

**Issue by asheichenko** [silverbulleters/add#258]
**Описание ошибки**
При попытке генерации данных из макета в котором содержатся записи регистра накопления, выдает ошибку: 
26.07.2018 9:06:27 {ВнешняяОбработка.СериализаторMXL.Форма.УправляемаяФорма.Форма(26)}: Ошибка при вызове метода контекста (СоздатьДанныеПоТабличномуДокументуСервер): Ошибка передачи данных между клиентом и сервером. Значение недопустимого типа.: Ошибка преобразования данных XDTO:
НачалоСвойства: ret Форма: Элемент  Тип: {http://www.w3.org/2001/XMLSchema}anyType: Ошибка преобразования данных XDTO:
НачалоСвойства: Value   Форма: Элемент  Тип: {http://www.w3.org/2001/XMLSchema}anyType: Ошибка преобразования данных XDTO:
НачалоСвойства: {http://v8.1c.ru/8.1/data/enterprise/current-config}Filter  Форма: Элемент  Тип: {http://www.w3.org/2001/XMLSchema}anyType

Технические данные:
        ИмяФайла: D:\Repository\SillverBulleters\add\features\libraries\Макеты\step_definitions\СозданиеFixturesПоМакетуОбработкиФичи.epf
        ИмяПроцедуры: ЯСоздаюFixturesПоМакету
        ВерсияVB: ver 5.1.1.0
        ВерсияПлатформы: 8.3.10.2580
        РежимСовместимостиTestManager: НеИспользовать

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Создать макет данных документа вместе с движениями по регистру накопления.
2. Запустить шаг "я создаю fixtures по макету"

**Ожидаемое поведение если бы ошибки не было**
Если оставить записи регистра сведений, а регистра накопления удалить загружается без проблем.

**Окружение:**
 - Версия операционной системы: Windows 10
 - Редакция 1С платформы 8.3.10.2580
 - Версия VB 5.1.1.0
 - Генератор макетов данных 

**Дополнительный контекст**
Обнаружил что в модуле объекта обработки "СериализаторMXL.epf" в процедуре СоздатьДанныеПоТабличномуДокументу есть код преобразующий регистр сведений в массив, а для регистра накопления такого кода нет.
```
	Если ВызываемИзУФ Тогда
		ЗначениеСоответствия = ВернутьЗначениеСоответствия( "РегистрСведенийНаборЗаписей" );
		Для каждого Элем Из Данные Цикл
			Стр = Строка(Элем.Значение);
			Если Найти(Стр, ЗначениеСоответствия) > 0 Тогда
				ИмяРС = Сред(Стр, СтрДлина( ЗначениеСоответствия ) + 2);
				Данные[Элем.Ключ] = ПолучитьКлючиЗаписиРСПоНаборуЗаписейРС(Элем.Значение, ИмяРС);
			КонецЕсли;
		КонецЦикла;
		
	КонецЕсли; 
```

**Comment by artbear** [comment]
@asheichenko Интересно!
сделаешь PR ?

**Comment by asheichenko** [comment]
Попробую, только там надо сервисную базу дорабатывать, так как нету регистра накопления. Не знаю как ее разложить на исходники. Может как то руководство для контрибьютеров по этому поводу дополнить.

**Comment by artbear** [comment]
Я обновил описание для контрибьютора в ветке девелоп
https://github.com/silverbulleters/add/blob/develop/.github/CONTRIBUTING.md
@asheichenko посмотри в тексте раздел `Изменения в конфигурации`

**Comment by asheichenko** [comment]
При запуске opm run depf выдает такие ошибки:
27.07.2018 9:26:27: ОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\fs\Модули\ФС.os / Ошибка в строке: 79 / Внешнее исключение (System.IO.PathTooLongException): Слишком длинный путь или имя файла. Полное имя файла должно содержать меньше 260 знаков, а имя каталога - меньше 248 знаков.}
27.07.2018 9:26:27: ОШИБКА - {Модуль D:\Repository\SillverBulleters\add\tools\runner.os / Ошибка в строке: 2192 / Значение не является значением объектного типа}
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\opm\oscript_modules\asserts\src\bdd-asserts.os / Ошибка в строке: 303 / [Failed] Ожидали, что проверяемое значение (1) МЕНЬШЕ ИЛИ РАВНО (0).
Ожидали, что код возврата <1> команды <oscript ./tools/runner.os decompileepf ./features features --ibname /F./build/ibservice> совпадет с ожидаемым <0>, а это не так!
Лог команды:
vanessa-runner v0.6.0
Обработано 10%
27.07.2018 9:26:27: ОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\fs\Модули\ФС.os / Ошибка в строке: 79 / Внешнее исключение (System.IO.PathTooLongException): Слишком длинный путь или имя файла. Полное имя файла должно содержать меньше 260 знаков, а имя каталога - меньше 248 знаков.}
27.07.2018 9:26:27: ОШИБКА - {Модуль D:\Repository\SillverBulleters\add\tools\runner.os / Ошибка в строке: 2192 / Значение не является значением объектного типа}
, вывод vanessa-runner v0.6.0
Обработано 10%
27.07.2018 9:26:27: ОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\fs\Модули\ФС.os / Ошибка в строке: 79 / Внешнее исключение (System.IO.PathTooLongException): Слишком длинный путь или имя файла. Полное имя файла должно содержать меньше 260 знаков, а имя каталога - меньше 248 знаков.}
27.07.2018 9:26:27: ОШИБКА - {Модуль D:\Repository\SillverBulleters\add\tools\runner.os / Ошибка в строке: 2192 / Значение не является значением объектного типа}
}

**Comment by artbear** [comment]
@asheichenko а ты на какой ветке проверяешь? на девелоп или все-таки на мастере?
правильно, в девелоп собирать

**Comment by artbear** [comment]
@asheichenko На всякий случай обнови все пакеты 
`opm update -all`

**Comment by asheichenko** [comment]
Вроде как на develop, делал по инструкции https://github.com/silverbulleters/add/blob/develop/.github/CONTRIBUTING.md 
После обновления opm ошибки остались.

**Comment by asheichenko** [comment]
Буду разбирать вручную.

**Comment by artbear** [comment]
Пожалуйста, 
+ включи отладочные логи `set LOGOS_LEVEL=DEBUG`
+ запусти `opm run depf >a.txt`
+ после завершения работы приложи файл a.txt к ишузу или пришли мне в личку (например, через гиттер)
+ потом отладочные логи можно отключить `set LOGOS_LEVEL=`

я смогу точно понять, что не так

**Comment by asheichenko** [comment]
Оказывается я не обновил Add у меня была версия 5.1.1. Сейчас попробовал все сделать заново. Я так понимаю, bddRunner сейчас находится в папке add\epf\ . Открываю и получаю ошибку {ВнешняяОбработка.bddRunner.Форма.УправляемаяФорма.Форма(5996)}: Неизвестный идентификатор плагина: <LoadSettings>
		ВызватьИсключение НСтр(ТекстСообщения);

**Comment by asheichenko** [comment]
Вообще странные ошибки, сейчас перезапустил конфигурацию, ошибка ушла, но теперь не грузиться фича в дерево.

**Comment by asheichenko** [comment]
Дерево стало загружаться при указании каталогов инструментов, но может надо как то сообщать что не заполнен каталог.

**Comment by artbear** [comment]
@asheichenko ух :(
странные у тебя проблемы.
Каталог инструментов заполняется автоматически :)

какая сейчас у тебя версия АДД?
+ удали старую версию 
+ установи 5.4.0 через opm install 
+ запусти новый bddRunner в своей конфигурации и убедись, что версия в заголовке формы именно 5.4.0
+ проверь нужное тебе поведение
+ сообщи результаты

**Comment by asheichenko** [comment]
Да, но я же запускаю обработку из своего репозитория, т.е. из ветки develop. Там же у меня находится плагин СериализаторMXL, который я дорабатываю. Версия запускается именно 5.4.0.

**Comment by asheichenko** [comment]
Так немного разобрался. Если запускать bddRunner.epf из каталога add\epf, то плагины пытается искать в папке add\epf\plugins из-за этого, выдает ошибку. Скопировал обработки в add, стало запускаться. Может тоже как то пересмотреть сборку бинарников, ведь не все будут пользоваться инструментом через opm.

**Comment by asheichenko** [comment]
Продолжаю прыгать по граблям, запустил opm run depf, разобрался на исходники СериализаторMXL, который я дорабатывал, а вот обработка проверки фичи не разобралась.

**Comment by asheichenko** [comment]
Похоже конфигурацию разобрал не в тот каталог. Выгружал в \add\lib\CF\83NoSync\ , так как в сервисной базе add режим использования модальности стоял в "Не использовать". Выходит надо разбирать в \add\lib\CF\83\   ?

**Comment by artbear** [comment]
Лучше пользоваться штатными командами `opm run depf` и `opm run cepf` согласно инструкции контрибьютора
тогда все раскладывается и собирается верно

Каталог epf - исключительно служебный, не нужно в нем собирать файлы обработок.

Разобрался с `обработка проверки фичи не разобралась.` ?

**Comment by artbear** [comment]
Выполнено

**Comment by asheichenko** [comment]
> Разобрался с обработка проверки фичи не разобралась. ?
  
Нет свою обработку разбирал вручную, в следующий раз попробую обратить внимание на этот момент. 
  Рефакторинг с исправлением копипаста может сделать в рамках вот [этой issue](https://github.com/silverbulleters/add/issues/272l) ?
