### ISSUE TITLE
Ошибка при попытке загрузить настройки для записи видео по умолчанию

### ISSUE THREAD

**Issue by ZhdanovR** [silverbulleters/add#265]
**Описание ошибки**
ADD Выдает ошибку при поа=пытке загрузить настройки для видео по умолчанию, так как файл "\tools\JSON\VBParams836UF.json" отсутствует в каталоге ADD

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть Vanessa-ADD
2. Перейти в 'Сервис - > Автоинструкции'
3. Нажать кнопку "ЗагрузитьНастройкиПоУмолчанию"

**Ожидаемое поведение если бы ошибки не было**
'....'

**Скриншоты**
если применимо приложите скриншот

**Окружение:**
 - Версия операционной системы: [например Ubuntu 18.04]
 - Редакция 1С платформы [например 8.3.12.1542]
 - Версия ADD [например 5.1.10]
 - Версия OScript [например 1.0.20]

![image](https://user-images.githubusercontent.com/26283990/43626214-b85662f0-9712-11e8-8ef9-d0f09d7fdae2.png)

Причина: https://git.silverbulleters.org/open-source/silverbulleters/add/blob/develop/epf/bddRunner/bddRunner/Forms/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl?expanded=true&viewer=simple#L553

Решений несколько:

1. Либо добавить файл с конфигом в V-ADD
2. Конфиг выбирать в ручную с диска
3. Качать конфиг с гитхаба и его уже подгружать.

**Comment by ZhdanovR** [comment]
ИМХО, лучший вариант 3-й

**Comment by 1cgh** [comment]
@ZhdanovR тогда придется обеспечивать, чтобы версия конфига соответствовала используемой версии ADD

**Comment by artbear** [comment]
Исправлено в https://github.com/silverbulleters/add/commit/40231fe313e018f2216787ecbcd906a4e534debf

**Comment by artbear** [comment]
И как реализовано 1-й вариант - файлы tools/json добавлен в поставку Vanessa-ADD

**Comment by artbear** [comment]
Просто релиз еще не выпущен :)
