### ISSUE TITLE
Декомпиляция базы разработки не происходит

### ISSUE THREAD

**Issue by allustin** [silverbulleters/add#27]
Когда я закончил кодинг - я могу только декомпилировать шаги и BBDRunner, а сервисная базы если она поправлена выгружается вручную

**Comment by pumbaEO** [comment]
Ну имхо, это лишний шаг. Она не часто меняется и можно вручную выгрузить. А так придется для каждого запуска еще и декомпиляцию базы запускать, а если в ней сидишь, то ошибка соответственно будет.

**Comment by allustin** [comment]
Ок - тогда закрою пока. Если что переоткроем
