### ISSUE TITLE
Не загружаются наборы записей регистров бухгалтерии и регистров расчета

### ISSUE THREAD

**Issue by asheichenko** [silverbulleters/add#272]
**Описание ошибки**
Не загружаются наборы записей регистров бухгалтерии и регистров расчета.
Аналогична [issue 258](https://github.com/silverbulleters/add/issues/258)

**Сценарий воспроизведения**
Шаги по воспроизведению:

1. Создать макет данных документа вместе с движениями по регистрам бухгалтерии и регистрам расчета
2. Запустить шаг "я создаю fixtures по макету"

**Ожидаемое поведение если бы ошибки не было**
Ожидаем, что в движениях загруженного документа будут записи по регистру бухгалтерии и регистру расчета

**Окружение:**
- Версия операционной системы: Windows 10
- Редакция 1С платформы 8.3.10.2580
- Версия VB 5.4.0
 - Генератор макетов данных 5.4.0

**Comment by asheichenko** [comment]
А как вы смотрите на то, чтобы для этой фичи перенести часть метаданных из \ibservicexdd , а именно ПланСчетов1, РегистрБухгалтерии1 и ПланВидовРасчета1 ? Возможно тогда бы это упростило решение задачи [#61](https://github.com/silverbulleters/add/issues/61) . Или сделать отдельные объекты?

**Comment by artbear** [comment]
Да, можно перенести, конечно.
Все равно когда-нибудь обе конфы объединим, даже ишуз на это зарегистрирован вроде бы.

**Comment by artbear** [comment]
Выполнено в #282
