### ISSUE TITLE
Неверная обработка выбора типа данных

### ISSUE THREAD

**Issue by KrivickyA** [silverbulleters/add#273]
**Описание ошибки**
В конфигурации имеет поле ввода данных составного типа.
Для платформы 8.3.10.2252 в управляемой форме в Vanessa Behavior 1.1.067 срабатывал вот такой сценарий:
```
	И в таблице "Таблица" я нажимаю кнопку выбора у реквизита "Реквизит"
	Тогда открылось окно "Выбор типа данных"
	И в таблице "" я перехожу к строке:
	| ''                            |
	| 'Тип реквизита N' |
	И я нажимаю на кнопку "ОК"
```
Актуальная версия  Vanessa 5.4.0 при попытке выполнить подобный код возвращает ошибку вида:

```
{ВнешняяОбработка.bddRunner.Форма.УправляемаяФорма.Форма(2708)}: Таблица формы с именем <> не найдена.

Технические данные:
        ИмяФайла: D:\OneScript\lib\add\features\libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf
        ИмяПроцедуры: ВТаблицеЯПерехожуКСтроке
        ВерсияVB: ver 5.4.0
        ВерсияПлатформы: 8.3.10.2252
        РежимСовместимостиTestManager: НеИспользовать
```

При попытке выполнить запись действий получаем следующий сценарий:
	Когда открылось окно 'Окно (создание) *'
	И в таблице "Таблица" я нажимаю кнопку выбора у реквизита "Реквизит"
	Тогда открылось окно 'Выбор типа данных'
	И я нажимаю на кнопку 'ОК'

Если по сценарию необходимо выбрать не первый по порядку тип данных получаем проблему.
**Скриншоты**
Пример диалогового окна:
![2018-08-06_14h38_20](https://user-images.githubusercontent.com/23094215/43714680-7b58ac2a-9986-11e8-9902-e19525ef1f9a.png)
Желаемый порядок действий:
- Нажимаем кнопку выбора (1)
- Выбираем нужный тип данных (2)
- Подтверждаем выбор (3)

**_Вопрос, как именно в сценарии нужно описать выбор типа данных?
Есть специальная команда или нужно перейти на другую версию платформы?_**

**Окружение:**
 - Версия операционной системы: Windows 10
 - Редакция 1С платформы: 8.3.10.2252
 - Версия ADD: 5.4.0
 - Версия OScript: 1.0.20

**Дополнительный контекст**

Не типовая конфигурация.
Режим защиты от опасных действий выключен.

**Comment by artbear** [comment]
Реализовано и задокументировано в FAQ

Подробнее в https://github.com/silverbulleters/add/issues/289
