### ISSUE TITLE
Ошибка в проверке типов параметров УтвержденияПроверкаТаблиц.ПроверитьРавенствоТаблиц

### ISSUE THREAD

**Issue by yehorh** [silverbulleters/add#275]
**Описание ошибки**
Ошибка в проверке типов параметров в плагине УтвержденияПроверкаТаблиц

[add/plugins/УтвержденияПроверкаТаблиц/УтвержденияПроверкаТаблиц/Ext/ObjectModule.bsl](https://github.com/silverbulleters/add/blob/96dbf5f4cb0fc80130cc82f22e9cfae047d56440/plugins/%D0%A3%D1%82%D0%B2%D0%B5%D1%80%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0%D0%A2%D0%B0%D0%B1%D0%BB%D0%B8%D1%86/%D0%A3%D1%82%D0%B2%D0%B5%D1%80%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0%D0%A2%D0%B0%D0%B1%D0%BB%D0%B8%D1%86/Ext/ObjectModule.bsl#L20)	

**Ожидаемое поведение если бы ошибки не было**
` 	Если ТипЗнч(Таб2) <> Тип("ТаблицаЗначений") Тогда`

**Comment by artbear** [comment]
Спасибо за внимательность!
Пропустили :(

Исправил.
