### ISSUE TITLE
Зачем условия и циклы в фича-файлах?

### ISSUE THREAD

**Issue by ZhdanovR** [silverbulleters/add#281]
На сколько корректным является использование циклов и условий в фиче?

https://github.com/silverbulleters/add/blob/master/features/libraries/%D0%A3%D1%81%D0%BB%D0%BE%D0%B2%D0%B8%D0%B5/%D0%A3%D1%81%D0%BB%D0%BE%D0%B2%D0%B8%D0%B5%D0%98%D0%BD%D0%B0%D1%87%D0%B5.feature

По идее, логику необходимо реализовывать в обработчике шагов, но не в самой фиче.

Если это так, то данную обработку нужно выпилить из ADD, если нет то хотелось бы понять смысл этой реализации.

//cc @EvilBeaver @pumbaEO

**Comment by allustin** [comment]
@ZhdanovR я был против этой функциональности "до хрипоты" и поэтому теперь никому про неё не рассказываю ;-)

**Comment by ZhdanovR** [comment]
@artbear ок.

**Comment by JohnyDeath** [comment]
Надо оставлять ради совместимости с СППР 2.0 ;)
