### ISSUE TITLE
Дымовые в отчете Allure

### ISSUE THREAD

**Issue by allustin** [silverbulleters/add#294]
сейчас дымовые определяются общим списком TestCases[1-N]

возможно стоит параметризировать до Дымовые-ВидОбъекта[1-N]

**Comment by artbear** [comment]
Реализован спец.плагин `ГенераторОтчетаAllureXMLВерсия2` для использования в xdd.

в файле vrunner.json нужно изменить используемый плагин `ГенераторОтчетаAllureXML` на новый плагин `ГенераторОтчетаAllureXMLВерсия2`

Например, 
```json
"--reportsxunit": "ГенераторОтчетаJUnitXML{build/junit.xml};
ГенераторОтчетаAllureXMLВерсия2{build/allure/allure.xml}"
```

После этого будет формироваться новый вид отчетов Аллюр

Если включена группировка по метаданным в файле настроек - `"СпособГруппировки":"ПоВидуМетаданных"`

![tdd-for-allure2](https://user-images.githubusercontent.com/2920817/45480359-810ac200-b751-11e8-9f87-d98cdea93673.PNG)

Если включена группировка по виду метаданного в файле настроек - `"СпособГруппировки":"ПоВидуОбъекта"`

![tdd-for-allure2-group-by-single-metadata](https://user-images.githubusercontent.com/2920817/45480374-86680c80-b751-11e8-877a-ddde4fe3fe18.PNG)

**Comment by artbear** [comment]
Также при использовании нового плагина красиво отображаются сценарные и группировочные tdd-xdd тесты

Рекомендую всем переходить на использование нового плагина после выпуска ближайшего релиза!

**Comment by artbear** [comment]
>Также при использовании нового плагина красиво отображаются сценарные и группировочные tdd-xdd тесты

Пример такой группировки хорошо видно в верхней части скриншота ниже

![tdd-for-allure2](https://user-images.githubusercontent.com/2920817/45480359-810ac200-b751-11e8-9f87-d98cdea93673.PNG)

**Comment by artbear** [comment]
Добавил документацию на плагины-генераторы отчетов о тестировании 
[Генераторы отчетов](https://github.com/silverbulleters/add/blob/develop/doc/xdd/%D0%93%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%D1%8B%D0%9E%D1%82%D1%87%D0%B5%D1%82%D0%BE%D0%B2.MD)
