### ISSUE TITLE
Добавление библиотечого шага "Я открываю основную форму объекта ЗначениеОбъекта"

### ISSUE THREAD

**Issue by asheichenko** [silverbulleters/add#297]
**Хотелось бы иметь следующую функциональность**
В связи с реализацией [#224](https://github.com/silverbulleters/add/issues/224) , хотелось бы сразу открывать форму объекта, загруженного из макета, после вызова шагов
`И я загружаю макет "Макет1" с переменными:`

Предлагаю добавить библиотечные шаги:
`Я открываю основную форму справочника ИмяПеременнойИзМакета`
и 
`Я открываю основную форму документа ИмяПеременнойИзМакета`
по аналогии с библиотечными шагами
`Я открываю основную форму списка документа "Документ1"`
`Я открываю основную форму списка справочника "Справочник1"`

Как вариант сделать универсальный шаг:
`Я открываю основную форму объекта ИмяПеременнойИзМакета`

**Comment by artbear** [comment]
Да, отличное предложение.

только предлагаю чуть детальнее
```gherkin
Я открываю основную форму объекта из переменной "ИмяПеременнойИзМакета"

Я открываю основную форму справочника из переменной "ИмяПеременнойИзМакета"
Я открываю основную форму документа из переменной "ИмяПеременнойИзМакета"

```

**Comment by artbear** [comment]
@asheichenko Сделаешь?

**Comment by asheichenko** [comment]
Да, сейчас у себя прогоню, потом перенесу в ADD

**Comment by artbear** [comment]
Реализовано
