### ISSUE TITLE
Плагин "Движения документа"

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#302]
**Существует потребность**
>@AnatoliyBritko я как-то раньше даже плагин почти сделал под это дело (проверка движений через перепроведение)
	[примерный код](https://github.com/AnatoliyBritko/BUH-BLR-RegionalSolutions/blob/master/src/epf/tests/xUnitFor1C/Plugins/%D0%94%D0%B2%D0%B8%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0/%D0%94%D0%B2%D0%B8%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0/Ext/ObjectModule.bsl#L106-#L137)

>он в ошибки валит таблицу расхождения в движениях
в jenkins выглядит не оч красиво

Источник https://gitter.im/silverbulleters/vanessa-behavior?at=5b7ec859f86b741b05b1338b

**Хотелось бы иметь следующую функциональность**
Плагин "Движения документа"

**Comment by JohnyDeath** [comment]
Зафиксирую здесь свои мысли по этому поводу. Хочется иметь возможность:
1. выбирать регистры по которым сравниваются движения
1. выбирать поля регистра (набора записей), по которым необходимо сравнивать
1. выбирать поля-исключения, по которым сравнивать не надо
1. добавлять собственные правила обработки набора записей перед их сравнением. Полезно когда, например, чуть-чуть поменяли логику заполнения поля и мы можем в коде предобработки это учесть

**Comment by AnatoliyBritko** [comment]
@artbear ок. 
До конца сентября попробую до ума довести и выложить.

**Comment by artbear** [comment]
Выполнено @AnatoliyBritko в #325
