### ISSUE TITLE
Тип параметра в таблице шага "ТаблицаСталаРавной(Парам01,ТабПарам)"

### ISSUE THREAD

**Issue by yadimetrio** [silverbulleters/add#315]
**Описание ошибки**
В таблице для этого шага не понятным образом определяется тип переменной. Одинаково оформленные параметры в фиче, в таблице имеют разный тип. На скрине фичи можно видеть что параметры "Количество" и "Сумма" оформлены одинаково (строковое представление числа), но в 
таблице дерева шагов они, почему то, имеют разный тип и отображаются по разному. В результате при выполнении шага появляется ошибка:

`{ВнешняяОбработка.bddRunner.Форма.УправляемаяФорма.Форма(10716)}: Ошибка компиляции при вычислении выражения или выполнении фрагмента кода
				Значение           = Вычислить(Значение);
по причине:
{(1,2)}: Ошибка в выражении
0<<?>>,500`

**Скриншоты**
если применимо приложите скриншот
![-](https://user-images.githubusercontent.com/28138187/45217188-dbb4a180-b2ab-11e8-9063-b9effee007a9.png)
![bdd](https://user-images.githubusercontent.com/28138187/45217201-e1aa8280-b2ab-11e8-80b7-267417609660.png)

**Окружение:**
 - Версия операционной системы: Windows 10
 - Редакция 1С платформы [например 8.3.10.2772]
 - Версия ADD [например 5.5.5]
 - Версия OScript [например 1.0.21.1]

**Comment by artbear** [comment]
уже исправлено в https://github.com/silverbulleters/add/issues/441
