### ISSUE TITLE
Ошибка использования json-файлов настройки дымовых тестов

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#321]
Источник https://gitter.im/xDrivenDevelopment/xUnitFor1C?at=5ba0020ed655361f7613af6f

Вопрос по дымовым.
Качнул последнюю версию add 5.5.5

сделал джейсона:
```json
{
    "smoke": {
        "Справочники": false
    }
}
```
После загрузки настроек и нажатия на кнопку "Перезагрузить" вываливает:

```
{ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.МодульОбъекта(1023)}: 
Ошибка при вызове метода контекста (Содержит)
Если Метаданные[ВидМетаданного].Содержит(СтрОбъект.Объект) Тогда
по причине:
Несоответствие типов (параметр номер '1')
```

все джейсоны из справки тоже не прокатывают.
Пробую на чистейшей УНФ.
ЧЯДНТ?
все джейсоны из справки тоже не прокатывают.
Пробую на чистейшей УНФ.
ЧЯДНТ?

Vladislav Moroz @VladFrost 12:09
У меня, кстати, тоже дымовой тест с помощью json не настраивается. Я тупо обработку у себя правил и добавлял исключения в код.

Artur Ayukhanov @artbear 12:10
@VladFrost @JohnyDeath не забыли, что в АДД 5.5.5 появился инструмент для управления настройками дымовых?
через него создайте json

Vladislav Moroz @VladFrost 12:13
Да, вот я его как раз и пытаюсь использовать

Artur Ayukhanov @artbear 12:13
и не заводится? :(

Vladislav Moroz @VladFrost 12:13
Выбрал все отчёты, сохранил smoke.json, он получился такой:
```json
"smoke": {
"Отчеты": false
}
}
```

Потом пытаюсь его же загрузить обратно, а он мне человеческим голосом говорит:
```
Ошибка при загрузке настроек из файла: {ВнешняяОбработка.УправлениеДымовымиТестами.Форма.Форма.Форма(537)}: 
Итератор для значения не определен
```

Artur Ayukhanov @artbear 12:14
а флажок в форме ставил на узле Отчеты или каждый отчет перевыбрал?

Vladislav Moroz @VladFrost 12:14
Да, флажок на узле Отчеты ставил

**Comment by artbear** [comment]
Хотя я слегка неправ 
для справочников инструмент настройки загружает
а вот для отчетов выдается ошибка итератора :)
исправлю.

но по самим дымовым проблем-то нет

**Comment by artbear** [comment]
Исправил ошибку загрузки "пустых" настроек для отчетов и обработок.

Жду информации по самим дымовым тестами.

**Comment by JohnyDeath** [comment]
Гифкой наверное будет проще показать:
![xdd-smoke-json](https://user-images.githubusercontent.com/5936030/45709702-4bb90680-bb8d-11e8-9bf5-7bc993e71379.gif)

**Comment by JohnyDeath** [comment]
Сейчас нарисую PR, там дело в составе ФО

**Comment by JohnyDeath** [comment]
> Что-то очень странное, у меня все работает.
> и ошибка в `{ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.МодульОбъекта(1023)}:`
> может встретиться, если в json включена настройка `ИсключитьФормыЗависящиеОтОтключенныхФункциональныхОпций` :(

По умолчанию, если опция не задана, то считается, что исключаем то, что отключено по ФО.
Пруф: https://github.com/JohnyDeath/add/blob/develop/tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Ext/ObjectModule.bsl#L998

**Comment by artbear** [comment]
Обе выявленные проблемы исправлены.
