### ISSUE TITLE
Проблемы с плагином "СтроковыеУтилиты"

### ISSUE THREAD

**Issue by yadimetrio** [silverbulleters/add#332]
**Описание ошибки**
Ошибка при подключении плагина:
```
{ВнешняяОбработка.СтроковыеУтилиты.МодульОбъекта(952,9)}: Процедура или функция с указанным именем уже определена (ФорматированнаяСтрока)
Функция <<?>>ФорматированнаяСтрока(Знач Строка) Экспорт (Проверка: Толстый клиент (обычное приложение))
```
Проблема в конкретной конфигурации КА 1.1. В ней есть глобальный общий модуль, где определена экспортная функция с таким же наименованием.

Проблема решилась бы добавлением префикса в функцию плагина, но не уверен что это правильно, подгонять под конкретную конфу.

**Comment by artbear** [comment]
Да, тут сложно что-то сделать :(
Под конкретную конфигурацию подгонять нельзя.
Пока больше никто на подобное не нарывался, ни на ОФ, ни на УФ-конфигурациях.

Предлагаю оставить без изменения.
А тебе придется для этой КА сделать спец. сборку :(
