### ISSUE TITLE
Поддержка режима совместимости 8.3.5 для tddTestRunner и дымовых тестов

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#336]
Клиент запросил доработку в рамках нашей Энтерпрайз-поддержки опенсорс-продуктов.

- [ ] Посмотреть на возможность возврата к совместимости с 8.2
 - Будет ли слишком сложно или все аналогично реализации совместимости с 8.3.5 ?

- [x] Задокументировать поддержку 8.3.5

**Comment by KrapivinAndrey** [comment]
Есть большой опыт в поддержке от 8.2 и дальше в рамках одного решения. Но надо завернуть код в конструкции "Выполнить". Пойдет?

**Comment by KrapivinAndrey** [comment]
Точно есть работа с  JSON и универсальным отказом от модальности. Я правда пока не представляю как это в плагины пробросить.

**Comment by KrapivinAndrey** [comment]
А у меня на 8.2 не взлетело. Из-за #Область #КонецОбласти.
Может доработать init? Чтобы он комментировал области при флаге? Остальное проверить не смог.

Все таки есть желание переписать модуль "по-контуроски" надо только момент выбрать

**Comment by artbear** [comment]
@KrapivinAndrey Да, было бы интересно посмотреть на результат.

**Comment by artbear** [comment]
>Есть большой опыт в поддержке от 8.2 и дальше в рамках одного решения. Но надо завернуть код в конструкции "Выполнить". Пойдет?

@KrapivinAndrey Да, подойдет.

**Comment by artbear** [comment]
Документировал поддержку 8.3.5

Закрываю

**Comment by artbear** [comment]
Поддержку 8.2. предлагаю делать в рамках отдельного ишуза #99
