### ISSUE TITLE
Рефакторинг УниверсальноеПолноеИмяФайла

### ISSUE THREAD

**Issue by pumbaEO** [silverbulleters/add#34]
https://github.com/silverbulleters/add/pull/33

**Comment by artbear** [comment]
Предлагаю следующее:
выделить 2 функции
+ `УниверсальноеПолноеИмяФайла` - та, что сейчас, но без `НРег` вообще
+ УниверсальноеПолноеИмяФайлаВНижнемРегистре - вызывает `УниверсальноеПолноеИмяФайла` и ее результат преобразует в `НРег`

соответственно, в коде явно указать вызовы этих функций

**Comment by artbear** [comment]
Также нужно исправить дублирование этого метода с дублем в `lib/featurereader/vbfeaturereader/FeatureReader/Ext/ObjectModule.bsl`

**Comment by artbear** [comment]
уже сделано.
