### ISSUE TITLE
Ошибка в обработке "Smoke_InputBasedOn"

### ISSUE THREAD

**Issue by capitoshko** [silverbulleters/add#340]
**Описание ошибки**
При запуске сценария дымных тестов по документах выдает ошибку:

17.10.2018 00:02:57 {ВнешняяОбработка.Smoke_InputBasedOn.Форма.Форма.Форма(146)}: Ошибка при вызове метода контекста (Выполнить): {(11, 2)}: Поле не найдено "ПоступлениеАвтомобилей.Дата"
<<?>>ПоступлениеАвтомобилей.Дата УБЫВ

Технические данные:
        ИмяФайла: <Путь на диске>\add-5.6.0\features\libraries\Smoke\Smoke_InputBasedOn.epf
        ИмяПроцедуры: ЯОткрываюФормуДокументаЗаполненногоНаОснованииНеПроведенного
        ВерсияVB: ver 5.6.0
        ВерсияПлатформы: 8.3.12.1595
        РежимСовместимостиTestManager: Версия8_3_7

что конкретно происходит

**Сценарий воспроизведения**
Шаги по воспроизведению:
1.  сформировать фичи с помощью обработки "Smoke_InputBasedOn" в конфигурации на основе БСП
2. загрузить фичи с файла
3. попробовать запустить первый шаг для документа "Электронное письмо входящее".

**Окружение:**
 - Версия операционной системы: [windows 10 enterprise]
 - Редакция 1С платформы [например 8.3.12.1595]
 - Версия ADD [например 5.6.0]

**Дополнительный контекст**

Конигурация самописная, версия БСП 2.3.2.76. Отключен режим защиты от опасных действий

**Comment by artbear** [comment]
Выполнено
