### ISSUE TITLE
Сниппеты BDD из дополнительных библиотек загружаются через раз

### ISSUE THREAD

**Issue by shureek** [silverbulleters/add#342]
**Описание ошибки**
Сниппеты, описанные в дополнительных библиотеках, указанных на вкладке Библиотеки, загружаются через раз.

**Сценарий воспроизведения**
1. Описываем дополнительный сниппет во внешней обработке
2. Добавляем каталог с этой обработкой в библиотеки
3. Загружаем сценарий с использованием этого сниппета.
4. При каждом нажатии "Перезагрузить сценарий" описанный шаг будет определяться то как описанный, то как не описанный.

**Окружение:**
 - ADD 5.6.0
 - Асинхронные вызовы включены

Отладочные сообщения при успешной и неуспешной загрузке:
[Лог ОК.txt](https://github.com/silverbulleters/add/files/2493605/default.txt)
[Лог не ОК.txt](https://github.com/silverbulleters/add/files/2493606/default.txt)

**Comment by shureek** [comment]
Попытки разобраться в проблеме привели к процедуре `ПолучитьУжеСуществующиеСнипетыИзОбработок` в [bddRunner.epf](https://github.com/silverbulleters/add/blob/master/epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl)

Там есть такой код:  
```bsl
ПрежняяВерсия = КоллекцияВерсийФайловШагов.Получить(УниверсальноеПолноеИмя);
Если ПрежняяВерсия <> Неопределено Тогда
    Если ПрежняяВерсия <> ВерсияФайла Тогда
        //значит в кеше уже есть нужные снипеты обработок
        УдалитьИзТаблицаИзвестныхStepDefinitionДанныеПоФайлуСервер(УниверсальноеПолноеИмя);
        
        ИДМассивИменКонтекстовОбработок = МассивИменКонтекстовОбработок.Найти(Нрег(УниверсальноеПолноеИмя));
        Если ИДМассивИменКонтекстовОбработок <> Неопределено Тогда
            МассивИменКонтекстовОбработок.Удалить(ИДМассивИменКонтекстовОбработок);
            ТаблицаКонтекстовОбработок[ИДМассивИменКонтекстовОбработок].Обработка = Неопределено;
            ТаблицаКонтекстовОбработок.Удалить(ИДМассивИменКонтекстовОбработок);
        КонецЕсли;
        
        Отладка(ПолучитьТекстСообщенияПользователю("$Загрузил новую версию$") + ": " + ПолноеИмяФайла);
    Иначе
        // Сюда заходит, когда не загружаются доп. сниппеты
        Отладка(ПолучитьТекстСообщенияПользователю("$Загрузил снипеты из кеш$") + ": " + ПолноеИмяФайла);
        
        КоллекцийПутейФайловКоторыеСовпалиСКеш.Вставить(УниверсальноеПолноеИмя, Истина);
        
        ЗаполнитьТаблицуКонтекстовОбработокНеПодключаяОбработки(Файл);
        
        Продолжить;
    КонецЕсли;
КонецЕсли;

// Сюда заходит, когда загружаются доп. сниппеты
ПодключитьСнипетыИзОбработкиКлиент(Файл, ВерсияФайла, БылиОшибки);

КоллекцийПутейФайловКоторыеСовпалиСКеш.Вставить(УниверсальноеПолноеИмя, Истина);
```

Собственно, прокомментировал поведение.

**Comment by artbear** [comment]
Если я не ошибаюсь, эта ошибка уже исправлена в ветке девелоп.
Соответствующий ишуз с обсуждением https://github.com/silverbulleters/add/issues/327

@shureek  Проверь на ветке девелоп

@ZhdanovR у тебя, возможно, аналогичная проблема.
Также проверь.

Текущий ишуз закрываю как дубль.
Если на ветке девелоп не заработает, переоткрывайте ишуз

**Comment by ZhdanovR** [comment]
@artbear Да походу оно.
