### ISSUE TITLE
Загружать глобальные переменные из внешнего файла

### ISSUE THREAD

**Issue by ripreal** [silverbulleters/add#343]
**Существует проблема**
У нас в команде есть проблема с использованием в feature файлах "плавающих" пользовательских переменных, таких как имен баз,  строк подключений, логинов, паролей.  Например, нам нужно из одного сеанса тестирования открыть четыре тестовые ERP базы или, другой пример, нам нужно в один справочник записать настройки подключения к сервису RAbbitMQ, индивидуальные для каждого разработчика.
Все эти переменные приходится  зашивать в код самой фичи, а затем их модифицировать, если они изменились. Это вдвойне неудобно, когда над тестами работают несколько человек и каждый использует свои базы для тестирования. В итоге приходится в тестах вставлять конструкции вида "если-тогда". 

**Хотелось бы иметь следующую функциональность**
Нужен внешний конфигурационый файл, в котором я бы мог записать все плавающие пользовательские переменные (имена баз, строки подключений, логины, пароли)  для всех пользователей, чтобы не влезать в фичи каждый раз, если я хочу их поменять.
При открытии ванессы конфиг бы подтягивался и сохранялся в глобальный контекст (ОбъектКонтекстСохраняемый)  и в любой части теста я бы мог обращаться к этим переменным с помощью шагов, которые поддерживают работу с ними, например:
- И в поле 'ИмяПоля' я ввожу значение глобальной переменной 'ИмяПеременной' , 
- "Я подключаю клиент тестирования с параметрами:" (этот шаг нужно доработать)

**Дополнительный контекст**
В действительно мы уже сделали собственную дописку к старой ванессе (1.1.) и хотелось бы ее перенести и на ADD. Файл, в котором у нас хранятся пользовательские настройки, называется user_settings.json и имеет следующий формат:
``` json
{
    "userSettings": [
        {
            "user": "USERNAME_1",
            "settings": {
                "ИМЯ_ПЕРЕМЕННОЙ_1": "ЗНАЧЕНИЕ_ПЕРЕМЕННОЙ_1",
                "ИМЯ_ПЕРЕМЕННОЙ_2": "ЗНАЧЕНИЕ_ПЕРЕМЕННОЙ_2",
            }
        },
        {
            "user": "USERNAME_2",
            "settings": {
                "ИМЯ_ПЕРЕМЕННОЙ_1": "ЗНАЧЕНИЕ_ПЕРЕМЕННОЙ_1",
                "ИМЯ_ПЕРЕМЕННОЙ_2": "ЗНАЧЕНИЕ_ПЕРЕМЕННОЙ_2",
            }
        }
    ]
}
```

**Comment by pumbaEO** [comment]
Имхо как-то все сложно. 
1. Создаем плагин который определяет откуда брать файл настроек, парсит его  и запоминает у себя в где-то. 
2. В процедуре перед запуском сценария читаем необходимые переменные из плагина, устанавливаем значение в КонтекстСохраняемый.Вставить("ИмяПоляПроверки", "Значение"); 
3. В шагах используем волшебство в виде  
```
И     в поле с именем "Наименование" я ввожу текст '$$ИмяПоляПроверки$$'
```
4. Чуть модифицировать Адд, что-б автоматом обновляло имя шага, после вычисления переменных. 

1-3 можно использовать хоть сейчас. 
4 - доработать в будущем.

**Comment by ripreal** [comment]
@pumbaEO С точки зрения архитектурных решений могу сделать и плагином. Это в общем непринципально. Хотелось бы узнать, можно ли будет на данную функциональность создать pull реквест и в конечном счете встроить в сам проект ADD

**Comment by pumbaEO** [comment]
Никто не может запретить писать код, если руки чешутса. 

Просто если смотреть с арихтектурной стороны, то мне непонятно, где плагин будет искать файл настроек (в worksettingsRoot или где-то еще).
Какая структура файла настроек будет.  

Мое видение такое:

В плагине есть экспортная процедура "ПолучитьНастройки(ПутьПоУмолчанию)", которая определяет настройки из файла, с возможностью переопределить и передать данные файла откуда читать настройки и возвращает Структуру 

В файле линейная структура с указанием полей подходящих для ключей структуры. 

Дальше уже пошла только своя внутренняя логика по заполнению правильными переменными в процедурах ПередНачаломСценария.

**Comment by ripreal** [comment]
@pumbaEO А если использовать в качестве пути к файлу реквизит Каталог проекта. К нему ведь можно получить доступ из плагина ванессы?

**Comment by pumbaEO** [comment]
можно вызывать такой код для преобразования пути:
` Ванесса.ПреобразоватьПутьСТочкамиКНормальномуПути(ПутьКФайлуШаблона); `
и можно указать путь типа `"$workspaceRoot/Examples/table.csv"`, где $workspaceRoot развернет в каталог проекта.

**Comment by ripreal** [comment]
@pumbaEO Ок, наверное подойдет, если $workspaceRoot  соответствует каталогу проекта, который вынесет в реквизит формы на закладке Сервис.

**Comment by pumbaEO** [comment]
Да, данній макрос разворачивается в каталогПроекта

**Comment by artbear** [comment]
Выполнено
