### ISSUE TITLE
Доработать функцию запуска SikuliX скрипта

### ISSUE THREAD

**Issue by ripreal** [silverbulleters/add#345]
**Описание ошибки**
Сейчас в самой обработке ванессы bddRunner.epf в функции ПолучитьСтрокуВызоваSikuli() есть спорный харкод, в котором зашит абсолютный путь к процессу java и выглядит он так:
``` bsl
Возврат """C:\Program Files (x86)\Java\jre6\bin\java.exe"" -Xms64M -Xmx512M -Dfile.encoding=UTF-8 -Dpython.path=""C:\Program Files (x86)\Sikuli X\sikuli-script.jar/"" -jar ""C:\Program Files (x86)\Sikuli X\sikuli-ide.jar"" -r ";
```
В этот харкод мы попадаем в случае, если передаем параметр  ЗапускЧерезСкрипт  = Ложь при вызове метода. Соответственно выходит так, что практически нереально запустить скрипт для прокликивания ссылки, если не используется SikuiliX IDE 

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Создать собственный шаг вида ЯЗапускаюШагSikuliX
2. в шаге воспользоваться функцией Ванесса.ВыполнитьSikuliСкрипт(ПутьКШаблону,, Ложь), где последний параметр - это ЗапускЧерезСкрипт, установленный в ложь
3. Запустить этот шаг через ванессу
4. Шаг не выполниться, если в системе нет путей C:\Program Files (x86)\Java\jre6\ и C:\Program Files (x86)\Sikuli X\sikuli-ide.jar"

**Ожидаемое поведение если бы ошибки не было**
Шаг искал бы библиотеку по относителньому пути в соответствии с рекомендации к структуре проекта, где sikuliX скрипты, runsikulix.cmd и sikulix.jar находятся в каталоге  \tools\sikulix

**Окружение:**
 - Версия операционной системы: Windows10
 - Редакция 1С платформы 8.3.10
 - Версия ADD например 5.6.0

**Дополнительный контекст**
Мы сделали доработку ванессы, котороая ищет runsikulix.cmd и sikulix.jar в относительном каталоге  \tools\sikulix. Очень хотелось бы ее перенести в ADD. Вся доработка занимает пару строчек:
``` bsl
//Возврат """C:\Program Files (x86)\Java\jre6\bin\java.exe"" -Xms64M -Xmx512M -Dfile.encoding=UTF-8 -Dpython.path=""C:\Program Files (x86)\Sikuli X\sikuli-script.jar/"" -jar ""C:\Program Files (x86)\Sikuli X\sikuli-ide.jar"" -r ";
ПутьКФайлу = "";
СостояниеVanessaBehavior = ПолучитьСостояниеVanessaBehavior();
ПутьКТекущемуFeatureФайлу = СостояниеVanessaBehavior.ТекущаяФича.ПолныйПуть;
ПутьКФайлу = """" + Лев(ПутьКТекущемуFeatureФайлу, СтрНайти(ПутьКТекущемуFeatureФайлу, "features", НаправлениеПоиска.СКонца) - 1) + "tools\SikuliX\runsikulix.cmd"" -r ";
Возврат "call " + ПутьКФайлу;
```

Пример вызова Sikulix скрипта для этой дописки у нас следующий: 
``` bsl
Ванесса.ВыполнитьSikuliСкрипт("D:\work\repository\mdm_main\tools\Sikulix\sikuli\КликВидНоменклатурыТипУказать.sikuli",, Ложь);
```

Доработка предъявляет требования к структуре проекта, а именно sikuliX скрипты,  runsikulix.cmd и sikulix.ja, должны быть в каталоге \tools\sikulix, но это лучше харкода, который есть сейчас.

**Comment by artbear** [comment]
@ripreal Как я говорил на нашей встрече, не хочется завязываться на любую конкретную структуру каталогов.

Вообще на мой взгляд, самое правильное решение -
+ Добавить спец.настройку `Строка запуска Sikuli` внутри плагина `LoadSettings`
  + после этого можно будет эту настройку использовать в json-файле настройки или в ком.строке или в переменной окружения
+ Добавить соответствующее поле на закладку Сервис в Упр.Форме bddRunner
  + это поле автоматом заполнится плагином

в итоге можно будет указывать любой путь, как внутри проекта, так и сторонний

Реализация несложна после моего рефакторинга настроек, сделанного в 5.6.0

Что скажешь?

**Comment by ripreal** [comment]
@artbear А что делать, если тесты запускаются интерактивно без раннера, как тогда заполнять этот реквизит в форме? Кроме того разве sikulix - это не легаси, зачем его еще поддерживать так активно?

**Comment by artbear** [comment]
И в интерактивном режиме, и при командном запуске будет юзаться один и тот же параметр.
Вы для себя добавите нужный вам путь.
Остальные пользователи могут добавить удобный для себя путь.
И сделать некое умолчальное значение - `runsikulix ...`

**Comment by artbear** [comment]
@ripreal ?

**Comment by ripreal** [comment]
@artbear Согласен с учетом дефолтног параметра, давай сделаем так

**Comment by artbear** [comment]
Выполнено в #355
