### ISSUE TITLE
Ошибка при создании подчинённых справочников, в случае если владелец справочника не справочник (ПВХ, ПО)

### ISSUE THREAD

**Issue by sfaqer** [silverbulleters/add#347]
**Описание ошибки**
Ошибка при создании подчинённых справочников, в случае если владелец справочника **не** справочник (ПВХ, ПО)

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть .add\xddTestRunner.epf
1. Загрузить тесты: .\add\tests\smoke
1. Выбрать тест справочника подчинённого ПВХ (Для УПП например: "Существующие элементы : Справочник.ЗначенияСвойствОбъектов.Форма.ФормаЭлемента")
1. Нажать Выполнить выделенные
1. Ошибка в отчёте: "{ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.МодульОбъекта(1278)}: Поле объекта не обнаружено (СвойстваОбъектов)
	Элем = Справочники[ИД].СоздатьЭлемент();"

**Ожидаемое поведение если бы ошибки не было**
Один из 2ух вариантов:
1. Пропускать справочники у которых владелец <> Справочник
2. Корректно обрабатывать всех возможных типов владельцев 

**Скриншоты**
![image](https://user-images.githubusercontent.com/32082417/47766860-aa40db00-dd1c-11e8-8f18-62a50d5572ae.png)

**Окружение:**
 - Версия операционной системы: Windows 10
 - Редакция 1С платформы 8.3.11.2954
 - Версия ADD 5.6.0
 - Версия OScript 1.0.21.298

**Дополнительный контекст**
Нетиповая УПП в режиме совместимости с 8.2.13 (всякий вызов Стр*** купирован глобальным модулем)

**Comment by binexekb** [comment]
Наверняка, это лейбл [smoke](https://github.com/silverbulleters/add/labels/smoke)

**Comment by artbear** [comment]
Да, исправил метку

**Comment by artbear** [comment]
@SidnevAV очередное большущее спасибо!

Исправлено в #668
