### ISSUE TITLE
Медленно выполняется шаг чтения глобальной переменной

### ISSUE THREAD

**Issue by ripreal** [silverbulleters/add#349]
**Описание ошибки**
В обработке ванессы необоснованно медленно выполняется шаг вида
```
И в поле с именем 'ИмяПоля ввожу значение глобальной переменной "ИмяПеременной". 
```
Выполнение занимает около 5 секунд. Причина в том, что в этой процедуре вызывается метод внешней обработки Ванесса.Шаг().  Вместо этого можно непосредственно вызывать ВОткрытойФормеВПолеСЗаголовкомЯВвожуТекст() и тогда шаг будет занимать менее 1 секунды.

**Ожидаемое поведение если бы ошибки не было**
Шаг выполняется менее 1 секунды.

**Окружение:**
 - Версия операционной системы: Windows
 - Редакция 1С платформы 8.3.10.2466
 - Версия ADD например 5.6.0

**Comment by artbear** [comment]
Выполнено!
