### ISSUE TITLE
Доработка шага подключение TestClient-а из таблицы клиентов тестирования

### ISSUE THREAD

**Issue by ripreal** [silverbulleters/add#351]
**Существует проблема**
У нас возникает несколько препятствий при использовании TestClient-ов
1. Нельзя передать в текущий тест клиент ("Когда я подключаю TestClient") свои параметры командной строки
2. Нельзя передать в параметризуемый текст клиент ("Когда я подключаю клиент тестирования с параметрами") переменные, сохраненные в КонтекстСохраняемый. 
3. Нельзя в параметризуемом текст клиенте открывать текущую базу (т.е. не указывать строку подключения к ИБ)

**Хотелось бы иметь следующую функциональность**
Хотелось бы иметь единый тест клиент, который мог бы открывать текущую базу, работать с сохраняемым контекстом глобальных переменных и иметь возможность передачи в него своих параметров командной строки

**Дополнительный контекст**
В связи с этим предлагаю научить параметризуемый  TestClient работать без указания строки подключения и с контекстом сохраняемых переменных.

**Comment by artbear** [comment]
+1

**Comment by artbear** [comment]
Выполнено в #352 и ранее
