### ISSUE TITLE
Дымовые тесты по метаданным

### ISSUE THREAD

**Issue by ImHunter** [silverbulleters/add#360]
Это часть переписки из проекта xUnitFor1C
https://github.com/xDrivenDevelopment/xUnitFor1C/issues/788

> Хочу написать несколько дымовых тестов.
> Вроде как, напрашивается новый плагин. Типа ИтераторМетаданных.
> Товарищи xDD Instruments for 1C Community, как вы смотрите на появление такого плагина?
> Ну или могу без плагина, свое локальное решение сделать.

> В общем, пишу дымовые тесты для забывчивых.
> Скоро у нас в разработке будет новая самописка. Напишу несколько дымовых тестов, чтобы мы (разработчики) не забывали, например, сразу выставлять права на чтение объектов.
> В первом дымовом тесте будет проверяться, что для справ, доков и регистров будет хоть какая-то роль на Чтение, отличная от ролей с администраторскими привилегиями.
> Будет еще аналогичный тест - будет проверяться Режим установки блокировки данных. По тесту, будет требоваться установка в значение Управляемый.

Сюда копирую для создания правильной ветки в Гите для этого проекта.

**Comment by artbear** [comment]
Выполнено
