### ISSUE TITLE
Повысить устойчивость библиотечного шага Я меняю значение переключателя

### ISSUE THREAD

**Issue by asheichenko** [silverbulleters/add#362]
В типовой конфигурации ERP существует документ "Акт о расхождения после приемки"
В нем есть переключатель "Оформление расхождений в 1 строке акта"
![image](https://user-images.githubusercontent.com/8320910/48891499-9173a300-ee4c-11e8-9b72-6026fc4c9e34.png)
     При попытке выполнить библиотечный шаг 
`И я меняю значение переключателя с именем 'СпособОтраженияРасхождений' на 'Оформление корректировок поступления'` 
или 
`И я меняю значение переключателя с именем 'СпособОтраженияРасхождений' на 'Оформить корректировку поступления'` 
выдает ошибку, что данное значение не обнаружено. 

Вот что выдает результат вызова метода ПолучитьПредставлениеСпискаВыбора() для данного переключателя.
![default](https://user-images.githubusercontent.com/8320910/48891525-a4867300-ee4c-11e8-864a-d2a68a035742.PNG)

   Процедура обработки шага ВОткрытойФормеЯМеняюЗначениеПереключателяСЗаголовкомНа
имеет такой комментарий: 
![image](https://user-images.githubusercontent.com/8320910/48891732-38583f00-ee4d-11e8-8c5d-f81868f6c222.png)

  Сейчас выкрутился тем, что выполняю шаг:
`И я меняю значение переключателя с именем 'СпособОтраженияРасхождений' на 1` 
   Задал вопрос в 1С, но в тоже время, возможно стоит повысить устойчивость шага, выполняя вначале попытку обратиться по имени, а затем если не получилось пытаться обратиться по индексу.

ADD версии 5.6.0
Платформа 8.3.12.1685. 
1С:ERP Управление предприятием 2 (2.4.6.154)

**Comment by asheichenko** [comment]
Ваше сообщение зарегистрировано для расследования в отделе разработки 10204158
О результатах расследования вы можете посмотреть в Сервисе публикации ошибок по ее номеру:
https://bugboard.v8.1c.ru/search.html

**Comment by asheichenko** [comment]
1С отказалось регистрировать ошибку. Оказывается в ERP в документе "Акт расхождения после приемки" в переключателе 'Оформить корректировку поступления' в названии существует пробел в конце, из за этого не отрабатывался метод ВыбратьВариант.

**Comment by artbear** [comment]
@asheichenko а они там молодцы, да :) 
пробел, понимаешь!
