### ISSUE TITLE
Загружать глобальные переменные из Consul-а

### ISSUE THREAD

**Issue by ripreal** [silverbulleters/add#391]
**Существует проблема**
В рамках  https://github.com/silverbulleters/add/issues/343 была сделана функциональность загрузки глобальных переменных из внешнего файла user_settings.json.  Но нам этого уже недостаточно. Мы решили хранить все конфиги проекта во внешнем key-value хранилище, а не в текстовых файлах. А глобальные переменные сейчас можно загружать только из текстового файла внутри репозитория с проектом.

**Хотелось бы иметь следующую функциональность**
Нам хотелось бы сделать расширить функциональность загрузки глобальных переменных с тем, чтобы можно было загружать переменные также из внешней key-value  базы Consul

Для этого предлагается вывести дополнительный реквизит с http строкой подключения к внешней базе и рутовым каталогом (namespaces-ом) в интерфейс, с которого все пары ключ-значение загружаются как глобальные переменные. Код предлагаю сделать универсальным, чтобы можно было подключить с небольшими доработками другой тип базы (mongo, cassandra и т.п.). Этот новый реквизит также нужно будет вынести в параметры запуска ванессы.

**Comment by artbear** [comment]
что планируется поменять в настройках и/или интерфейсы ванессы?

**Comment by ripreal** [comment]
@artbear В интерфейсе и параметрах запуска появятся два параметра: 
- Поставщик настроек  - фиксированное перечисление с двумя значениями Файл и Консул
- Путь к настройкам -  файловый путь или url по которому находятся настройки

**Comment by artbear** [comment]
Лады, в таком варианте согласен, можно сделать.

Присылайте ПР :)

**Comment by artbear** [comment]
выполнено
