### ISSUE TITLE
Не сохраняются (некорректно читаются из сохраненных настроек) пути к библиотекам шагов

### ISSUE THREAD

**Issue by VladimirLitvinenko84** [silverbulleters/add#401]
Версия bddRunner.epf  5.6.0

Если в список библиотек добавить путь к своему каталогу, отличному от $instrumentsRoot/features/libraries и сохранить настройки, то при последующем открытии bddRunner.epf, после загрузки настроек, строка с этим каталогом не будет добавлена в список библиотек.

Шаги по воспроизведению:
1. Открыть 'bddRunner.epf'
2. Перейти на вкладку "Библиотеки"
3. Добавить строку в список путей к библиотекам
4. Сохранить настройки вкладки "Библиотеки"
5. Перезапустить 'bddRunner.epf'
6. На вкладке "Библиотеки" будет отсутствовать ранее добавленный путь

Скриншот, демонстрирующий ошибочное поведение:
https://infostart.ru/upload/iblock/c79/c79a3c6ddad4b3988dca573e2695f535.gif

Причина в следующем. В методе ВосстановитьНастройкиКлиент() подключается плагин LoadSettings и вызывается его метод Настройки.ВосстановитьНастройки(ЭтаФорма), который корректно загружает пути к библиотекам.

Однако затем вызывается метод ВосстановитьВсеНастройкиИзХранилища() который перезатирает результат загрузки списка библиотек.

Затем вызывается метод ЗапускВРежимеКоманднойСтроки(), хотя запуск происходит не в режиме командной строки. Этот метод читает еще часть настроек, но среди них нет каталога библиотек.

Плагином LoadSettings настройки сохраняются в ХранилищеОбщихНастроек с ключём "VanessaBehaviorUF".  А в методе ВосстановитьВсеНастройкиИзХранилища() каталог и библиотек загружаются через вызов ХранилищеОбщихНастроек.Загрузить(ЭтаФорма, "КаталогиБиблиотек"). 

Скриншот причины возникновения ошибки:
https://infostart.ru/upload/iblock/b45/b45014610143b3621a5b6753aaa46cc8.gif

Если закомментировать строку 
   ВосстановитьНастройкиИзХранилища("КаталогиБиблиотек", "КаталогиБиблиотек");
в методе ВосстановитьВсеНастройкиИзХранилища(), то ошибка перестаёт воспроизводиться.

**Comment by artbear** [comment]
Не подтверждаю данное поведение для девелоп-версии.

Проделал шаги согласно тест-кейсу и у меня добавленная библиотека сохранилась.

ишуз закрываю.
в ближайшие дни будет выпущен долгожданные релиз Ванесса.АДД и можно будет убедиться, что проблема решена.

@ZhdanovR @infactum Проверьте, плиз, на ваших версиях данный кейс.

**Comment by Infactum** [comment]
@artbear 
На актуально dev версии проблема воспроизводится.  
![test](https://user-images.githubusercontent.com/384884/52397965-2b0c3180-2ad9-11e9-851c-01948383193c.gif)

**Comment by artbear** [comment]
@Infactum Странно, я пропустил твое сообщение неделю назад :(
Посмотрю.

**Comment by artbear** [comment]
@VladimirLitvinenko84 Огромное спасибо за ишуз и подробное исследование ошибки и поиск пути ее решения.

Я сделал исправление согласно твоим предложениям.
