### ISSUE TITLE
Не работает xunit из состава ADD в обычном приложении на УПП 1.3.104 и старше

### ISSUE THREAD

**Issue by Begemoth2** [silverbulleters/add#405]
При запуске обработки xddTestRunner в обычном приложении в УПП 1.3.104.2  ошибка
{ВнешняяОбработка.СтроковыеУтилиты.МодульОбъекта(952,9)}: Процедура или функция с указанным именем уже определена (ФорматированнаяСтрока)
Функция <<?>>ФорматированнаяСтрока(Знач Строка) Экспорт (Проверка: Толстый клиент (обычное приложение))

Причина в том, что в УПП начиная с определенной версии добавили Глобальный общий модуль ИнтеграцияЕГАИСУТКлиентСерверГлобальный где есть функция ФорматированнаяСтрока.

Как следствие не можем использовать тесты на более-менее свежих версиях УПП.

В качестве способа обхода в нашем форке ADD в плагине СтроковыеУтилиты обрамили функцию ФорматированнаяСтрока в секцию
#Если ТолстыйКлиентОбычноеПриложение Тогда
#Иначе
чтобы она не компилировалась в обычном приложении

**Comment by Begemoth2** [comment]
Примите ли наш вариант исправления как пулреквест?

**Comment by artbear** [comment]
Да, подобное исправление примем.

**Comment by sfaqer** [comment]
@artbear а чем этот ишуз принципиально отличается от #322 ? Ну т.е. там отклонено с обоснованием "нельзя подгонять фреймворк под конкретную конфу", а тут уже можно?)

**Comment by artbear** [comment]
@sfaqer Хороший вопрос, спасибо.
в обоих случаях мы "допилили фреймворк" под конкретные случаи и это не потребовало сильных изменений в проекте.

**Comment by sfaqer** [comment]
@artbear, беглый поиск по проекту показывает что данный функционал нигде не используется (кроме тестов которые проверяют работу этого функционала), так что изменение предложенное выше не повлияет на работоспособность проекта, однако пользовательские тест, которые используют данный функционал, полетят, в случае если тестируемая конфигурация на обычных формах, и это не актуальная УПП. Всё таки УПП не единственная конфигурация на ОФ, да и далеко не у всех обновляется.

**Comment by sfaqer** [comment]
@artbear, блин, только сейчас обратил внимание что в моём позапрошлом комменте гитхаб вставил ссылку на ПР а не на ишуз, под "322" понимался вот этот ишуз: https://github.com/silverbulleters/add/issues/332

**Comment by artbear** [comment]
@sfaqer @yadimetrio Да, #322 и текущий ишуз имеют много общего.

В сентябре у меня было другое мнение, сейчас оно изменилось.

Мотивация такая - на обычных формах юзаются фактически только "старые и заслуженные монстры" (УПП, КА и какие-то самописки), все остальные давно на упр.формах и на новых типовых.

В новых конфигурациях нет проблем с ФорматированнаяСтрока.
Поэтому для пользователей в упр.режиме ничего не поменяется,
а для пользователей обычного режима можно пойти навстречу и дать возможность юзать и свою конфигурацию, и наш фреймворк.

**Comment by artbear** [comment]
Выполнено в #461
