### ISSUE TITLE
Дымовые тесты по бизнес-процессам

### ISSUE THREAD

**Issue by StupnikovVG** [silverbulleters/add#409]
**Существует проблема**
Не запускаются дымовые тесты по бизнес-процессам

**Хотелось бы иметь следующую функциональность**
Запускать дымовые тесты по бизнес-процессам для новых объектов, существующих объектов, списков.
В файле настроек задавать исключения для бизнес-процессов

**Дополнительный контекст**
Если функционал интересен, готов взяться за разработку

**Comment by artbear** [comment]
Да, конечно, функционал интересен.

Если сделаешь, будет супер.

**Comment by artbear** [comment]
Выполнено в #412
