### ISSUE TITLE
Подозрение - в синхронном режиме сломались отчеты в пакетном режиме в 5.7.0

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#414]
**Описание ошибки**
Источник https://github.com/silverbulleters/add/pull/413#discussion_r257619160

@VladFrost ещё сюда надо будет добавить условие про поддержку асинхронности
[https://github.com/silverbulleters/add/blob/master/epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl#L1183](https://github.com/silverbulleters/add/blob/master/epf/xddTestRunner/xddTestRunner/Forms/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L1183)

@VladFrost Или здесь что-то сделать [https://github.com/silverbulleters/add/blob/master/epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl#L1209](https://github.com/silverbulleters/add/blob/master/epf/xddTestRunner/xddTestRunner/Forms/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L1209)
Потому что сейчас в синхронном режиме сломались отчеты в пакетном режиме :(

@artbear вроде бы все в порядке, у нас на закрытом CI тесты ОФ проходят, или я что-то не вижу :)

Нужно проверить поведение в синхронном режиме

**Comment by VladFrost** [comment]
У меня заработало после такой правки в https://github.com/silverbulleters/add/blob/develop/epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl#L1181 
```bsl
Для Каждого ГенераторОтчета Из МассивДанныхОтчетов Цикл
	Параметры_xddReport.Добавить(ГенераторОтчета);
	ОписаниеПлагина = Плагин(ГенераторОтчета[0]).ОписаниеПлагина(Объект.ТипыПлагинов);
	Если ОписаниеПлагина.Свойство("ПотоковыйВывод") И ОписаниеПлагина.ПотоковыйВывод Тогда
		Параметры_xddStreamReport.Добавить(ГенераторОтчета);
	КонецЕсли;
КонецЦикла;
```
https://github.com/silverbulleters/add/commit/c81633e9f438ecfb2688c9d7246b0b066a82c9c3#r32356103

**Comment by artbear** [comment]
Исправлено
