### ISSUE TITLE
Падает  Шаг И таблица "ИмяТаблицы" содержит строки

### ISSUE THREAD

**Issue by asosnoviy** [silverbulleters/add#417]
**Описание ошибки**
Шаг:
"И таблица "Хозрасчетный" содержит строки:"
| 'Субконто2 Дт'                        | 'Субконто3 Дт'                  |
| 'Нужный Основной учет агентского НДС' | 'Списание с расчетного счета *' |

Падает с ошибкой:
21.02.2019 13:36:16 {ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(4361)}: В результирующей таблице существуют две колонки с одинаковым заголовком: В
Р

**Сценарий воспроизведения**
Вызвать шаг для проверки бух проводки Ух/БП

**Ожидаемое поведение, если бы ошибки не было**
Шаг выполняться не зависимо от имен колонок.

**Скриншоты**

![image](https://user-images.githubusercontent.com/15638529/53166764-43a33e00-35e7-11e9-854b-7009054c38d1.png)

**Окружение:**

 - Версия операционной системы:`Windows 10 (64)`

**Дополнительный контекст**

Типовая УХа 3.0 и вероятно БП 3.0 т.к. формы там одинаковые

Технические данные:
        ИмяФайла: C:\Program Files (x86)\OneScript\lib\add\features\libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf
        ИмяПроцедуры: ТаблицаСодержитСтроки
        ВерсияVB: ver 5.7.0
        ВерсияПлатформы: 8.3.13.1690
        РежимСовместимостиTestManager: Версия8_3_12

**Comment by artbear** [comment]
>В результирующей таблице существуют две колонки с одинаковым заголовком: В
Р

@asosnoviy текст неполон. не все скопировалось?

**Comment by asosnoviy** [comment]
> > В результирующей таблице существуют две колонки с одинаковым заголовком: В
> > Р
> 
> @asosnoviy текст неполон. не все скопировалось?

Это колонка так называется ВР

**Comment by asosnoviy** [comment]
@artbear Вроде все описал.

**Comment by asheichenko** [comment]
@asosnoviy  Я думаю это та же самая проблема https://github.com/silverbulleters/add/issues/335

**Comment by asosnoviy** [comment]
Как выяснилось не она.

**Comment by artbear** [comment]
@asosnoviy Ага, так понятнее.

посмотрю формирование текст шагов проверки состояния формы.

к нему у меня у самого претензии давно есть :)

**Comment by artbear** [comment]
Проблема исправлена в девелоп-ветке.
С дублями теперь работаем правильно.

также значительно ускорена работа шага, код там был веселый, старое наследство :(

**Comment by asosnoviy** [comment]
@artbear не полечилось =(

25.03.2019 12:52:12 {ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(4367)}: Ошибка при вызове метода контекста (Добавить): Неверное имя колонки

Технические данные:
        ИмяФайла: C:\Program Files (x86)\OneScript\lib\add\features\libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf
        ИмяПроцедуры: ТаблицаСодержитСтроки
        ВерсияVB: ver 5.8.0
        ВерсияПлатформы: 8.3.12.1714
        РежимСовместимостиTestManager: Версия8_3_10

**Comment by asosnoviy** [comment]
![image](https://user-images.githubusercontent.com/15638529/54911112-cd07a200-4efe-11e9-8b56-34785d66c529.png)

**Comment by artbear** [comment]
@asosnoviy странно :(

упс, перенос колонки я не увидел и не проверял :(

**Comment by asosnoviy** [comment]
> И теперь становится ясно что в имени колонки торчит 'В\nР`

Вот тут же...

**Comment by artbear** [comment]
не знаю, как пропустил, извини.

**Comment by artbear** [comment]
я проверял на ЕРП, там нет ошибки.

сейчас проверил, там нет переноса строки :(

**Comment by asosnoviy** [comment]
Посмотрел в БП 3.0.69.32. Перенос есть.

**Comment by artbear** [comment]
разобрался с переносом в заголовке реквизита, там весело получается.

1С-ка странно себя ведет с такими реквизитами, иногда дает перенос строки, а иногда сама его заменяет на пробелы :)

**Comment by artbear** [comment]
Изменения внес, пайплайн запустился, подождем полной проверки

**Comment by artbear** [comment]
забыл отписаться.

Исправлено. В ветке девелоп сборка прошла.

Исправительный релиз выйдет в ближайшее время
