### ISSUE TITLE
В отчете Allure пройденные тесты стали отображаться серым цветом (как skipped) 

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#418]
**Описание ошибки**
https://xdd.silverbulleters.org/t/v-otchete-allure-projdennye-testy-stali-otobrazhatsya-serym-czvetom-kak-skipped/2622

**Ожидаемое поведение, если бы ошибки не было**
Отчет должен быть зеленым

**Скриншоты**
по ссылке выше есть скриншоты

**Окружение:**

 - Версия `Vanessa.ADD` [например, `5.7.0`]

**Comment by ripreal** [comment]
@artbear Грац!

А ты не проверял, скриншоты в allure стали показываться после исправления ошибки со статусами?

**Comment by artbear** [comment]
@ripreal Скриншоты также стали показываться, конечно.
