### ISSUE TITLE
Затираются параметры подключения TestClient

### ISSUE THREAD

**Issue by KrapivinAndrey** [silverbulleters/add#419]
**Описание ошибки**
Использую шаг
Когда Я подключаю клиент тестирования с параметрами:
            |     'Имя подключения'    |  'Логин'  |'Пароль'|
            |'Наблюдение_Администратор'|'ФедоровБМ'|   ''   |

При выполнении ПроставитьГлобальныеПеременные(ТабПарам) параметры которые не найдены в КонтекстСохраняемый меняются значения на Неопределено.

**Ожидаемое поведение, если бы ошибки не было**

Сохранится указанный изначально Логин и тест-клиент будет запущен под нужным пользователем

**Скриншоты**

![image](https://user-images.githubusercontent.com/586025/53341402-48d8f380-392d-11e9-9993-95fbe47aa76b.png)

![image](https://user-images.githubusercontent.com/586025/53341424-57270f80-392d-11e9-9af1-441d0216b6e0.png)

**Окружение:**

 - Версия операционной системы: Windows 10 (64)
 - Редакция платформы 1С `8.3.13.1644`]
 - Версия `Vanessa.ADD` `5.7.0`
 - Версия `OneScript` `1.0.21`

**Comment by artbear** [comment]
выполнено в https://github.com/silverbulleters/add/pull/421
