### ISSUE TITLE
Ошибка Метод объекта не обнаружен (СтрШаблонКлиент) в 5.7.0

### ISSUE THREAD

**Issue by 1cgh** [silverbulleters/add#420]
**Описание ошибки**
При выполнении дымового теста по открытию форм (без исключений) из 5.7.0 возникает ошибка:
`{ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.Форма.УправляемаяФорма.Форма(940)}: Метод объекта не обнаружен (СтрШаблонКлиент)
		ВызватьИсключение КонтекстЯдра.СтрШаблонКлиент("Не удалось выполнить команду %1 на тест-клиенте.`

Видимо, в раннере переименовали метод, а в дымовых - нет. Или наоборот. Или вовсе использовали метод, которого нет.

**Окружение:**

 - Версия `Vanessa.ADD` 5.7.0 из хаба

**Comment by artbear** [comment]
Выполнено

**Comment by ovcharenko-di** [comment]
У меня ошибка воспроизводится на 6.0.0, точно также, как в описании.

**Comment by artbear** [comment]
@ovcharenko-di да, удали эту обработку. ошибка в ветке девелоп уже исправлена
