### ISSUE TITLE
В отчет алюра не подтягиваются скрины с ошибками при падении сценария

### ISSUE THREAD

**Issue by seramiti** [silverbulleters/add#423]
**Описание ошибки**
не прикрепляется скрин ошибки в отчет алюра при падении сценария 

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Запускаются сценарии
2. Формируются скрины с ошибками
3. Формируется отчет алюра без прикрепленния скринов к сценариям которые выполнены не успешно

**Ожидаемое поведение, если бы ошибки не было**
В отчете алюра по сценариям которые упали прикреплены скрины с ошибками

**Окружение:**

 - Редакция платформы 1С [например, `8.3.14.1565`]
 - Версия `Vanessa.ADD` [например, `5.7.0`]

**Comment by asosnoviy** [comment]
Якорь на тред https://t.me/testspro1c/4736

**Comment by KrapivinAndrey** [comment]
Все таки баг.. А я думал что это у меня руки кривые

**Comment by artbear** [comment]
Ага, контрибьютор слегка ошибся, а я на код-ревью не увидел :(

**Comment by artbear** [comment]
Исправления внесены. Посмотрю, что скажет CI.

@asosnoviy в телеграмме указаны все-таки неверные исправления.

но даде эти исправления помогли найти правильный путь исправления :)

**Comment by artbear** [comment]
Коллеги, проверьте, пожалуйста, данную дев-сборку.
@seramiti @seramiti @VladFrost и другие

Исправлены и аллюр, и скриншоты, и многое другое.

[add-5.7.0-dev-20190228.zip](https://github.com/silverbulleters/add/files/2916321/add-5.7.0-dev-20190228.zip)

или на яндекс-диске https://yadi.sk/d/65KpmEVu0pVkWA

жду результатов проверки.

**Comment by VladFrost** [comment]
> жду результатов проверки.
@artbear у меня норм!

**Comment by seramiti** [comment]
@artbear и у меня все норм. Спасибо.

**Comment by artbear** [comment]
Отлично.
@ripreal у коллег все в порядке.

закрываю ишуз.

**Comment by artbear** [comment]
Коллеги, для особо нуждающихся выкладываю девелоп-версию Ванесса.АДД

в которой много чего исправлено и дополнено.

релиз 5.8.0 будет выпущен или завтра или в выходные

[add-5.7.0-develop.zip](https://github.com/silverbulleters/add/files/2991517/add-5.7.0-develop.zip)
