### ISSUE TITLE
Некорректно обрабатывается шаг по нажатию кнопки выбора в таблице у поля составного типа

### ISSUE THREAD

**Issue by EightM** [silverbulleters/add#427]
**Описание ошибки**
Некорректно обрабатывается шаг по нажатию кнопки выбора в таблице у поля составного типа.

**Сценарий воспроизведения**
Шаги по воспроизведению:
На форме есть табличная часть, у одной из колонок есть составной тип.
используется сценарий:
_В таблице "Таблица" я перехожу к строке
И в таблице "Таблица" я выбираю текущую строку
И в таблице "Таблица" я нажимаю кнопку выбора у реквизита "СоставнойРеквизит"
Тогда открылось окно 'Выбор типа документа'_

При выполнении данного сценария появляется ошибка:
_ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(3495)}: Ошибка при вызове метода контекста (Выбрать): Метод не может быть вызван для данного объекта (Документ планирования): Метод не может быть вызван для данного объекта (Документ планирования)_
Но окно выбора типа успешно **открывается**.

**Ожидаемое поведение, если бы ошибки не было**
Ожидается, что окно выбора типа открывается и сценарий не падает с ошибкой.

**Окружение:**

 - Версия операционной системы: `Windows 10 (64)`
 - Редакция платформы 1С  `8.3.11.3041 (z)`
 - Версия `Vanessa.ADD`  `5.6.0`, воспроизводится и на 5.7.0
 - Версия `OneScript` 1.0.21`

**Дополнительный контекст**
Анализ кода показал, что проблема в процедуре:
`ВОткрытойФормеВТЧЯНажимаюКнопкуВыбораУРеквизитаСЗаголовком`

```
ПолеРеквизит.Активизировать();	
	
Если НЕ ТЧ.ТекущийРежимРедактирование() Тогда
	ТЧ.ИзменитьСтроку();
КонецЕсли;	 

ПолеРеквизит.Выбрать();
```

Если поле составного типа, то при выполнении кода `ТЧ.ИзменитьСтроку();` сразу откроется модальное окно выбора типа, и `ПолеРеквизит.Выбрать()` логично свалится из-за недоступности. Самый очевидный способ исправления окружить `ПолеРеквизит.Выбрать()` попыткой. При добавлении попытки, сценарий успешно выполняется.

- Нетиповая конфигурация на основе УХ 1.3.7
- Режим от опасных действий отключен

**Comment by artbear** [comment]
@EightM спасибо, проверим поведение.

**Comment by artbear** [comment]
Исправлено в девелоп-ветке.

@EightM большое спасибо за разбор проблемы, сильно помогло!
