### ISSUE TITLE
Ошибка доступа к файлу при загрузке макета

### ISSUE THREAD

**Issue by ripreal** [silverbulleters/add#428]
**Описание ошибки**
При использовании шага "и область табличного документа равна макету" происходит загрузка макета из локальной файловой системы. Ошибка состоит в том, что загрузка макета пытается выполнится на стороне сервера тогда как макет находится на клиенте. 

**Сценарий воспроизведения**
Шаги по воспроизведению:
1.   Открыть ванессу и добавить шаг И область  "R1C1:R15C12"  табличного документа  "ОтчетТабличныйДокумент"  равна макету  "АнализЛимитовЗакупок.mxl"
2. Попытатся выполнить шаг (разумеет в руте каталога проекта должен лежать файл "АнализЛимитовЗакупок.mxl"
3. Возникнет ошибка  приблизительно такая Ошибка доступа к файлу 'd:\Users\jenkins\AppData\Local\Temp\v8_9A13_30.mxl'

**Ожидаемое поведение, если бы ошибки не было**
Шаг успешно находит макет и выполняет его првоерку

**Скриншоты**
![image](https://user-images.githubusercontent.com/25801912/54823028-9d1a8d80-4cb7-11e9-8824-7735fb523d6f.png)

**Окружение:**

 - Версия операционной системы: Windows 10
 - Редакция платформы 1С 8.3.12.1685
 - Версия `Vanessa.ADD 5.7.0.

**Comment by artbear** [comment]
@ripreal я подозреваю, что у тебя что-то запуталось с разными версиями.

В чистой 5.7.0 такой ошибки нет, в дев-версии также ошибки.

Вроде в дев-версии, которую мы с тобой на парном отлаживали, мы как раз и исправляли внесенную в девелоп (уже после 5.7.0) ошибку, когда была ошибка передачи между клиентом и сервером.

**Comment by artbear** [comment]
В чистой 5.7.0 такой ошибки нет, в дев-версии также нет этой ошибки.

**Comment by ripreal** [comment]
Ок, действительно. Обновился на последнюю версию dev ветки лт 24 марта и ошибка исчезла! Спасибо
