### ISSUE TITLE
Глобальная библиотека сценариев отдельным проектом/пакетом

### ISSUE THREAD

**Issue by theshadowco** [silverbulleters/add#433]
**Существует проблема**
Сейчас в составе ADD, VA присутсвует библиотека с шагами и их реализаций, что в свою очередь увеличивает размер пакета и снижает скорость добавления и рефакторинга библиотеки шагов

**Хотелось бы иметь следующую функциональность**
Как разработчик и тестировщик
Я хочу иметь отдельный репозиторий с фичами и их реализацией для возможности обновления, рефакторинга, структуририрования.

**Дополнительный контекст**
По сути, я вижу что есть отдельная база с шагами, а каждый продукт с собой несет ТОЛЬКО свои. 

Еще одним плюсом для сообщества будет возможность использовать отдельную от инструментов библиотеку, т.к. копировать между VA и ADD запарно.

PS. Это касается не только ADD/VA, но 1bdd

**Comment by theshadowco** [comment]
@Pr-Mex, @nixel2007, @asosnoviy, @1C-Romania

Приглашаю присоедениться: единая база - это интересно всему сообществу, вне зависимости от инструментов.

**Comment by hawk911** [comment]
:popcorn: :popcorn: :popcorn: 
Думаю, объединить невозможно, а вот шаги выделить во что-то отдельное - интересная идея.

**Comment by asosnoviy** [comment]
Чем дальше, тем больше разваливается совместимость VA:ADD =( Мысль то правильная, но на реализацию придется положить кучу сил.

**Comment by theshadowco** [comment]
@hawk911 
Объединить продукты не предлагаю, хотя это было бы супер ибо сейчас вместо объединения усилий, два параллельных тунеля строится.

По поводу отдельного проекта с шагами - я понимаю, что есть некоторые особенности, но это можно решить с помощью тэгов, что конечно потребует усилий со стороны всех продуктов, но они некритичны.

@Pr-Mex, @allustin, @asosnoviy, @artbear 

Если не готовы общаться на этой площадке вместе, давайте в другом, нейтральном, месте обсудим. 

Одно из предложений к новому проекту, чтобы вам не воевать, - ни один из мейнтейнеров упомянутых продуктов не будет иметь главествующего права над общей библиотекой, дабы сообществу получить профит исключив священные войны.

**Comment by yadimetrio** [comment]
Хорошая идея, но вряд ли выгорит. К обоим продуктам и так можно подключать любые либы с шагами, ничего не мешает запилить репо с этими шагами. Мейнтейнеры проектов не придут к общему знаменателю. Как вариант, можно предложить в обоих продуктах сделать настройки "Не использовать стандартные шаги" и вместо стандартных подключать свои из репо.

**Comment by theshadowco** [comment]
@yadimetrio 

похоже на то.

Как вариант, сделать в оба продукта реквесты, создать самостоятельно реп куда копировать из продуктов + добавить свои, создать пакет opm и в vrunner'е доработать конфиг

**Comment by artbear** [comment]
Интересные предложения.

Так сразу и не дам ответа. 

Думаю. Моментов для размышлений много.

**Comment by artbear** [comment]
движений к совместной библиотеке нет. никому не интересно.закрываю в связи с неактуальностью (

**Comment by nixel2007** [comment]
а от кого должны быть движения, как не от мейнтейнеров?

**Comment by theshadowco** [comment]
так всегда: "Сообщество мы для вас, мы с вами", "Надо подумать", а потом "Неактуально"

**Comment by asosnoviy** [comment]
> так всегда: "Сообщество мы для вас, мы с вами", "Надо подумать", а потом "Неактуально"

Ну пуллреквестов то нет, значит неактуально ;)

**Comment by allustin** [comment]
Давайте не будем обманывать друг-друга - @asosnoviy @nixel2007 вы дорабатываете в другом месте... я вас в контрибьютинге давно тут не видел.

@theshadowco посыл правильный - но компания 1С уже не позволит его реализовать. На данном этапе это невозможно. Когда мы в марте обсуждали варианты реализации... была идея отдельного мейтейнера только для шагов. Не зависиящий ни от кого. Но кого выбрать мейнтейнером глобальной библиотеки. Пока этот вопрос не решить - ничего не получиться.

придет время вернемся к этому вопросу.
