### ISSUE TITLE
Ошибка при подготовке сценария к выполнению

### ISSUE THREAD

**Issue by Asakra** [silverbulleters/add#434]
**Сценарий воспроизведения**
Шаги по воспроизведению:
1. открываем обработку bddRunner
2. переходим на вкладку "Работа с UI"
3. жмем кнопку "Подготовить сценарий к выполнению"
4. получаем ошибку, что не обнаружен каталог в темпе "vanessa-add"
5. в процедуре ПодготовитьСценарийКВыполнению, нет проверки на существование каталога и нет создания каталога
6. помогло создание каталога вручную

**Ожидаемое поведение, если бы ошибки не было**
Открытие фичи в дереве тестов

**Скриншоты**
![Screenshot_2](https://user-images.githubusercontent.com/46216116/55056914-8488e980-50a2-11e9-875b-ac6182a3c825.png)
![Screenshot_1](https://user-images.githubusercontent.com/46216116/55056919-8783da00-50a2-11e9-936b-d9d065ffd3ca.png)

**Окружение:**
Windows 10 (64)
 1С 8.3.13.1576
Vanessa.ADD 5.8.0
OneScript 1.0.21

**Дополнительный контекст**
Пустая файловая конфигурация

**Comment by Asakra** [comment]
в процедуру ПодготовитьСценарийКВыполнению() скопировал из версии 5.7.0
УдалитьКаталогКомандаСистемы(КаталогВременногоFeature);
СоздатьКаталогКомандаСистемы(КаталогВременногоFeature);

все заработало...

**Comment by RetZet** [comment]
А когда будет поправлено в 5.8.0? У меня нет 5,7,0, чтобы взять оттуда код.

**Comment by allustin** [comment]
@RetZet https://github.com/silverbulleters/add/tree/v5.7.0

Вот отсюда. @artbear треба хотфикс

**Comment by RetZet** [comment]
оказывается сделал как в 5.7.0, как выше указано, встави строчки. Мне не помогло.

28.03.2019 11:30:54 Ошибка при построении дерева из файла <C:\Users\имяпользователя\AppData\Local\Temp\vanessa-add\temp.feature>
{ВнешняяОбработка.vbFeatureReader.МодульОбъекта(5150)}: Ошибка при вызове метода контекста (Открыть): Ошибка доступа к файлу 'C:\Users\trofimov\AppData\Local\Temp\vanessa-add\temp.feature'

**Comment by Asakra** [comment]
@RetZet  создайте в темпе каталог "vanessa-add":
C:\Users\имяпользователя\AppData\Local\Temp\vanessa-add\

**Comment by RetZet** [comment]
> @RetZet создайте в темпе каталог "vanessa-add":
> C:\Users\имяпользователя\AppData\Local\Temp\vanessa-add\

Так он уже есть!

**Comment by artbear** [comment]
@RetZet точно есть именно по пути, указанному в ошибке Ванессы?

код, который выдает ошибку, прост - пытается создать файл фичи с указанным именем в указанном каталоге.
и чаще всего проблема в том, что каталога просто нет.

**Comment by RetZet** [comment]
> @RetZet точно есть именно по пути, указанному в ошибке Ванессы?
> 
> код, который выдает ошибку, прост - пытается создать файл фичи с указанным именем в указанном каталоге.
> и чаще всего проблема в том, что каталога просто нет.

проверяю перед нажатием кнопки, каталог есть.

**Comment by RetZet** [comment]
Я в отладчике КаталогВременногоFeature поставил как "D:\_1С\Тестирование\vanessa-add\" и все поехало. Подозреваю, что что-то выполняется не от меня как юзера, соответственно, доступа к папке "C:\Users\имяпользователя\AppData\Local\Temp\vanessa-add\" просто нет. 
Можно как-то сделать в bddRunner.epf переопределение каталога временных файлов. По умолчанию пусть ставит, как есть, но чтобы его можно было бы переопределить.

**Comment by artbear** [comment]
@RetZet в Ванесса-АДД на менеджере тестирования большая часть действий выполняется на клиенте.

Код, приводящий к ошибке, работает на клиенте.

Ошибка в релиз 5.8.0 состоит в том, что я не полностью продумал все последствия удаления кода создания временного каталога vanessa-add во временном каталоге и удалил код создания этого каталога, который как раз и создавал каталог vanessa-add во временном каталоге на машине, на которой запущена Ванесса-АДД.

Почему у Вас работает не так, непонятно и странно.

**Comment by artbear** [comment]
я внес исправления в девелоп-ветку
- Исправлена ошибка при подготовке сценария к выполнению #434

И дополнительно сделал

- Если заполнен каталог проекта, тогда сценарий, подготовленный к выполнению, создается в каталоге проекта

т.е. теперь можно не извращаться с временным каталогом, а сразу создавать фичу в правильном месте

 Исправительный релиз будет в ближайшее время
