### ISSUE TITLE
Поддержка 8.3.14 - для дымовых и BDD

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#438]
**Существует проблема**
На 8.3.14 в 5.8.0 не стартуют дымовые тесты

Причина выяснена @nixel2007 

```
синтакс-контроль модуля обработки выдает ошибку на 
`ТипЗнч(ТестируемаяФорма) = Тип("УправляемаяФорма")`

вероятно обработка просто не компилируется, поэтому вообще не запускается.

поставил в настройках враннера использование 8.3.13 - заработало
```

```
Что переименовано  Старое наименование  Новое наименование
Название типа, описывающего форму клиентского приложения.  
УправляемаяФорма.
ФормаКлиентскогоПриложения.

```
Источник: https://dl03.1c.ru/content/Platform/8_3_14_1630/1cv8upd_8_3_14_1630.htm#7d5e536e-a534-11e8-a3f7-0050569f678a

**Хотелось бы иметь следующую функциональность**

- [ ] Исправить код дымовых тестов для совместимости с 8.3.14 и платформами ниже

- [ ] Аналогично исправить весь код, в котором есть использование `Тип("УправляемаяФорма")` 

- [ ] Проверить весь код, в котором есть использование `"УправляемаяФорма"` , вдруг там легаси-код преобразования типа к строке

**Comment by KrapivinAndrey** [comment]
![image](https://user-images.githubusercontent.com/586025/55331121-0ebebc80-54ac-11e9-8cb5-89356ecd7aa9.png)
Проверил свою обработку. На 8.3.14 без проблема такой кусок работает.
![image](https://user-images.githubusercontent.com/586025/55331155-2302b980-54ac-11e9-8b98-e1459728a9c9.png)
И ошибок не находит.

База - каркасная конфигурация для тестов без режима совместимости на 8.3.14.1630

**Comment by artbear** [comment]
Связано с похожей проблемой https://github.com/silverbulleters/add/issues/447

**Comment by artbear** [comment]
Лето заканчивается. Выполнено.
