### ISSUE TITLE
Неверный регистр в ПутиКПлагинам в xddTestRunner

### ISSUE THREAD

**Issue by igostv** [silverbulleters/add#440]
**Описание ошибки**
Путь к плагинам неверный для Unix систем
Сейчас [`Plugins\`](https://github.com/silverbulleters/add/blob/master/epf/xddTestRunner/xddTestRunner/Forms/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L1704) а должно быть `plugins/`

```
&НаКлиенте
Функция ПолучитьПутьКПлагинам()
	// Для встроенного в состав конфигурации браузера тестов
	// используемое имя файла не используется
	Если НЕ Объект.ЭтоВстроеннаяОбработка Тогда
		ФайлЯдра = Новый Файл(ЭтаФорма["ИспользуемоеИмяФайла"]);
		Результат = ФайлЯдра.Путь + "Plugins\";
	КонецЕсли;

	Возврат Результат;
КонецФункции
```

**Сценарий воспроизведения**
Запуск дымовых на Linux

```
./oscript_modules/bin/vrunner xunit --settings tools/vrunner.json
```

**Окружение:**

 - Версия операционной системы:  Ubuntu 18.04
 - Редакция платформы 1С [например, `8.3.14.1565`]
 - Версия `Vanessa.ADD` [например, `5.8.0`]
 - Версия `OneScript` [например, `1.1.0.11`]

**Comment by artbear** [comment]
@igostv Интересно, спасибо, исправлю

**Comment by artbear** [comment]
в ветке девелоп исправлено.

релиз 5.9.0 планировал сегодня выпустить.

**Comment by artbear** [comment]
исправлено и в xdd-, и в bdd-части
