### ISSUE TITLE
Нечитаемый текст исключения Проверки режима блокировки

### ISSUE THREAD

**Issue by allustin** [silverbulleters/add#442]
**Существует проблема**

При проверке способом дымового тестирования мы проверяем что режим блокировки объекта метаданных соответствует корневому режиму для всех метаданных. В случае не соответствия выдаем исключение.

Исключение сейчас выглядит как 

```
Проверка режима блокировки данных РегистрСведений
ВнешняяОбработка.УтвержденияBDD.МодульОбъекта(292)}: [Failed] 
Ожидали, что проверяемое значение (Ложь) является ИСТИНОЙ.
```

**Хотелось бы иметь следующую функциональность**

Вот тут https://github.com/silverbulleters/add/blob/develop/tests/smoke/%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0%D0%A0%D0%B5%D0%B6%D0%B8%D0%BC%D0%B0%D0%91%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B8/%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0%D0%A0%D0%B5%D0%B6%D0%B8%D0%BC%D0%B0%D0%91%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B8/Ext/ObjectModule.bsl#L70

Добавить:

* расширенное описание ошибки, включающее в себя способ исправления

Например

```
Нестандартный режим блокировки объекта <ОбъектМетаданных>.
Для исключения ошибки - переведите объект <ОбъектМетаданных> 
в режим управления блокировками - <РекомендуемыйРежимБлокировокОбъекта>
```

**Дополнительный контекст**

из канала Теллеграм  https://t.me/silvernation

![изображение](https://user-images.githubusercontent.com/55323/55391248-a7ebe280-5541-11e9-93a5-8cc93ff1e946.png)

**Comment by artbear** [comment]
дополнен текст ошибки

![image](https://user-images.githubusercontent.com/2920817/66644533-d30a6980-ec29-11e9-9c08-88a5f532bc7c.png)
