### ISSUE TITLE
Не запускаются дымовые тесты форм на Linux

### ISSUE THREAD

**Issue by igostv** [silverbulleters/add#444]
**Окружение:**

 - Версия операционной системы: `Ubuntu 18.04`
 - Редакция платформы 1С: `8.3.14.1565`
 - Версия Vanessa.ADD: `5.8.0`

**Описание:**

В плагине УправлениеПриложением.epf много кода жестко привязанного к выполнению только на windows:
Процедура ЗаполнитьМассивPIDПоИмениПроцесса
Процедура СделатьОкноПроцессаАктивным
Процедура ВыполнитьКомандуОСБезПоказаЧерногоОкна
Процедура ВыполнитьКомандуОСБезПоказаЧерногоОкнаСВыводом
...

**Comment by igostv** [comment]
#440

**Comment by artbear** [comment]
@igostv ВыполнитьКомандуОСБезПоказаЧерногоОкна - там же есть код для Линукс
и, возможно, и здесь ВыполнитьКомандуОСБезПоказаЧерногоОкнаСВыводом

**Comment by artbear** [comment]
@igostv и указанные методы в дымовых тестах форм не участвуют же.

просто плагин УправлениеПриложением.epf инициализируется, выполняется его базовый код и все, 
методы не вызывается в дымовых тестах.

или нужны примеры, где идет вызов, если я не прав.

**Comment by artbear** [comment]
@igostv случайно закрыл, переоткрываю

**Comment by artbear** [comment]
Совместно с @Infactum нарвались на эту же проблему и внесли исправления в код плагина УправлениеПриложениями
В ветке девелоп.

**Comment by artbear** [comment]
Вот коммит https://github.com/silverbulleters/add/commit/49cbf57b91fe02c40ffa0f15a48f8da9f1adfb91
