### ISSUE TITLE
Доработка для 8.3.14 - Не запускается обработка для дымовых тестов

### ISSUE THREAD

**Issue by lelikanet** [silverbulleters/add#447]
**Описание ошибки**
Не запускается обработка. Ошибка:
{ВнешняяОбработка.xddTestRunner.МодульОбъекта(65)}: Значение не является значением объектного типа (Инициализация)
    Плагин.Инициализация(ЭтотОбъект);

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть '* одина'
2. Нажать 'Ctrl+O'
3. Запустить 'обработку xddTestRunner.epf'
4. после открытия формы - показывается ошибка

**Ожидаемое поведение, если бы ошибки не было**
'открытие обработки - без ошибки. Анализ и открытие списка последних запущенных тестов'
**Скриншот:**
![image](https://user-images.githubusercontent.com/45041332/55560184-63ef0e00-56f8-11e9-8c6c-d4e3ad755cbd.png)

**Окружение:**
 - Версия операционной системы: [например, `Windows 10 (64)`
 - Редакция платформы 1С [`8.3.14.1630`]
 - Версия `Vanessa.ADD` [`5.8.0`]
 - Версия `OneScript` [`1.0.21`]

**Дополнительный контекст**
- Не типовая конфигурация
- Включен ли режим защиты от опасных действий
- Выключен режим совместимости
- Серверная база
- Тонкий клиент

**Comment by artbear** [comment]
@lelikanet  чудес же не бывает :)
посмотрите еще раз, пожалуйста.
сеанс под тем ли пользователем стартует?
точно правильная база или соседняя база стартует :) ?
и т.п.

![image](https://user-images.githubusercontent.com/2920817/55563181-1aa1bd00-56fe-11e9-87c0-7bb305acd211.png)

**Comment by artbear** [comment]
@lelikanet а что за пункты?
```
Открыть '* одина'
Нажать 'Ctrl+O'
```
при чем здесь Ванесса-АДД ?

**Comment by artbear** [comment]
Подтверждаю, что для серверных базах 8.3.14 нужна доработка.

Доработка готова.

будет в релизе.

**Comment by maminkaktus** [comment]
Добрый вечер, столкнулась с похожей проблемой. Версия Ванессы 5.6.0 
База серверная, windows 10 (64)
Текст ошибки:
{ВнешняяОбработка.ЗагрузчикФайла.Форма.Форма.Форма(297)}: Старый формат тестов в обработке тестов <C:\Users\Aпупкина\AppData\Local\Temp\17\vanessa-behavior\step_definitions\temp.epf>.
Метод ПолучитьСписокТестов сейчас не принимает параметров
            ВызватьИсключение "Старый формат тестов в обработке тестов <"+ФайлОбработки.ПолноеИмя+">."+Символы.ПС+

![скрин ошибки](https://user-images.githubusercontent.com/49633892/56509486-cbe28880-652f-11e9-97ed-6d8f472b47d0.jpg)

Что я делаю не так?

**Comment by TheDemonCat** [comment]
По всей видимости из той же темы.
![изображение](https://user-images.githubusercontent.com/26283990/60333303-78226e80-99ba-11e9-9847-5dcbf710c707.png)

```bsl
Не удалось загрузить файл C:\Program Files (x86)\OneScript\lib\add\tests\smoke\Smoke_InputBasedOn.epf
Переданный файл не существует файл <C:/Program Files (x86)/OneScript/lib/add/tests/smoke/Smoke_InputBasedOn.epf>
{ВнешняяОбработка.ЗагрузчикФайла.МодульОбъекта(112)}:       ВызватьИсключение "Переданный файл не существует файл <" + Файл.ПолноеИмя + ">";
{ВнешняяОбработка.ЗагрузчикФайла.МодульОбъекта(93)}:            ПроверитьКорректностьФайла(ФайлОбработки);
{ВнешняяОбработка.ЗагрузчикФайла.МодульОбъекта(120)}:   Обработка = ПолучитьКонтекстОбработки(ФайлОбработки, ИмяОбработки);
{ВнешняяОбработка.ЗагрузчикФайла.Форма.Форма.Форма(212)}:   Контейнер = ЭтотОбъектНаСервере().ЗагрузитьФайл(ПостроительДереваТестов, ФайлОбработки, КонтекстЯдра, ИмяОбработки);
{ВнешняяОбработка.ЗагрузчикФайла.Форма.Форма.Форма(126)}:       КонтейнерССервернымиТестамиОбработки = ЗагрузитьФайлНаСервере(ФайлОбработки.ПолноеИмя, ИмяОбработки, КонтекстЯдра.Объект);
{ВнешняяОбработка.ЗагрузчикКаталога.Форма.Форма.Форма(184)}:        ДеревоТестовФайла = ЗагрузчикФайла.Загрузить(КонтекстЯдра, ФайлОбработки.ПолноеИмя);
{ВнешняяОбработка.ЗагрузчикКаталога.Форма.Форма.Форма(170)}:            КонтейнерФайла = ЗагрузитьФайл(КонтекстЯдра, Файл);
{ВнешняяОбработка.ЗагрузчикКаталога.Форма.Форма.Форма(37)}: ДеревоТестов = ЗагрузитьКаталог(КонтекстЯдра, КаталогДляЗагрузки);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(490)}:     ЭтаФорма.ДеревоОтЗагрузчика = ФормаЗагрузчика.Загрузить(ЭтаФорма, Путь);
{ВнешняяОбработка.ЗагрузчикКаталога.Форма.Форма.Форма(225)}:        КонтекстЯдра.ЗагрузитьТесты(Описание.Идентификатор, Результат);
```

**Comment by artbear** [comment]
Лето заканчивается. Выполнено.
