### ISSUE TITLE
Добавляются лишние исключения при получении списка исключений для дымовых тестов

### ISSUE THREAD

**Issue by ovcharenko-di** [silverbulleters/add#448]
**Описание ошибки**
В любой конфигурации при наличии в ней документа с именем "Штрафы" или справочника с именем "ирАлгоритмы" список тестов заполняется некорректно (указанные объекты всегда добавляются в исключения проверки). Проблема в незакомментированном коде.

[ссылка на ошибку №1](https://github.com/silverbulleters/add/blob/ffe03ec3515317325da658c07f03777aaf5b414a/tests/smoke/%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/%D0%A2%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/Ext/ObjectModule.bsl#L207)

[ссылка на ошибку №2](https://github.com/silverbulleters/add/blob/ffe03ec3515317325da658c07f03777aaf5b414a/tests/smoke/%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/%D0%A2%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/Ext/ObjectModule.bsl#L221)

[ссылка на ошибку №3](https://github.com/silverbulleters/add/blob/ffe03ec3515317325da658c07f03777aaf5b414a/tests/smoke/%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/%D0%A2%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/Ext/ObjectModule.bsl#L293)

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть xddTestRunner.epf в конфигурации, в которой есть документ с именем "Штрафы" и справочник с именем "ирАлгоритмы" 
2. Загрузить тест "Тесты_ОткрытиеФормКонфигурации.epf"
3. Убедиться, что в списке отсутствуют
- Справочники -> Существующие : Справочник.ирАлгоритмы
- Справочники -> Новые : Справочник.ирАлгоритмы
- Документы -> Новые : Документ.Штрафы

**Ожидаемое поведение, если бы ошибки не было**
Наличие всех видов тестов для всех объектов, без исключения

**Окружение:**
 - Версия `Vanessa.ADD 5.8.0`

**Comment by ovcharenko-di** [comment]
Еще одна незакомментированная строка:

[ошибка №4](https://github.com/silverbulleters/add/blob/ffe03ec3515317325da658c07f03777aaf5b414a/tests/smoke/%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/%D0%A2%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/Ext/ObjectModule.bsl#L236)

Соответственно, справочника ирАлгоритмы вообще не будет в списке тестов.

**Comment by artbear** [comment]
Выполнено
