### ISSUE TITLE
Некорректный путь к OneScript при автоматической сборке в Travis

### ISSUE THREAD

**Issue by ovcharenko-di** [silverbulleters/add#450]
**Описание ошибки**
При автоматической сборке валится этап compile, так как происходит [вызов](https://github.com/silverbulleters/add/blob/c878303dfa48b80b46d012b144cf648941aeedcb/.travis.yml#L52) wget со ссылкой, которая выдает 404.

Вот правильная ссылка:
http://oscript.io/downloads/latest/onescript-engine_1.0.21_all.deb

**Comment by artbear** [comment]
Выполнено
