### ISSUE TITLE
Для каталогов lib/TemplateEpfUF и lib/TemplateEpf добавить переименование неверного имени epf-файла в имя родительской папки

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#46]
Сейчас при сборке обработок в каталогах `lib/TemplateEpfUF` и `lib/TemplateEpf` создается файл `lib/Обработка.epf`
При этом остается только один из этих файлов, а не появляются 2 файла.

Нужно добавить переименование файла обработки в `lib/TemplateEpfUF.epf` и `lib/TemplateEpf.epf` соответственно

**Comment by nixel2007** [comment]
Может идентификаторы просто поменять?

**Comment by artbear** [comment]
Если я не ошибаюсь, идентификаторы "Обработка" используются при генерации файлов новых шагов.
Поэтому так просто их не поменять, нужно код генерации менять.

**Comment by artbear** [comment]
Возможно, еще @pumbaEO подскажет по имени обработки и генерации новых шагов

**Comment by artbear** [comment]
Тут опять какая-то магия.
Я вчера вечером запускал на add сборку.
Сегодня я увидел, что получил правильные имена файлов :)
![image](https://user-images.githubusercontent.com/2920817/35432656-ca5e78e0-0291-11e8-9be7-c7809c26eeab.png)

А на моем локальном репо (сильно порезанный add для быстрой разработки) создается один файл `Обработка.epf` :(

Магия!
