### ISSUE TITLE
Дымовые тесты на тест-клиенте должны уметь закрывать модальные окна с заголовком "1С:Предприятие"

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#460]
**Существует проблема**
Одна из форма при выполнении теста создает модальное окно-вопрос с заголовком "1С:Предприятие", в котором есть кнопки Да и Нет

и это окно блокирует весь интерфейс.

в результате все последующие тесты падают :(

**Хотелось бы иметь следующую функциональность**
Вариант реализации  [...]
Дымовые тесты на тест-клиенте должны уметь закрывать модальные окна с заголовком "1С:Предприятие"

**Comment by theshadowco** [comment]
@artbear 
Ты имеешь ввиду окна-ошибки?

**Comment by ovcharenko-di** [comment]
@theshadowco, @artbear, я тоже столкнулся с этой проблемой. 

У меня это, например, обычный ПоказатьВопрос(,"Точно закрыть?") при закрытии одной из обработок.

**Comment by ovcharenko-di** [comment]
@artbear, такой вариант поиска активного окна в обработке `тесты_ОткрытиеФормКонфигурации.epf` может сработать? Он позволит пропустить окно с заголовком "1С:Предприятие". Или это слишком грубое решение?

```bsl
&НаКлиенте
Функция ОсновноеОкно(ТестКлиент)

	Для Каждого ТестируемоеОкно Из ТестКлиент.ПолучитьПодчиненныеОбъекты() Цикл
		Если ТестируемоеОкно.Основное
			И Не ТестируемоеОкно.Заголовок = "1С:Предприятие" Тогда
			Возврат ТестируемоеОкно;
		КонецЕсли;
	КонецЦикла;

	ВызватьИсключение "Не удалось найти основное окно";

КонецФункции```

**Comment by artbear** [comment]
@ovcharenko-di пропустил твой вопрос, извини :(

а подобный пропуск таких окон что нам даст?
не основные окна будут закрываться, а основное не будет закрываться или что?

**Comment by artbear** [comment]
@VladFrost что скажешь по этой проблеме? твой последний ПР решает эту проблему?

**Comment by VladFrost** [comment]
Там метод был вынесен в плагин: `КонтекстЯдра.Плагин("ТестКлиенты").ИдентифицироватьОкноПредупреждение()` https://github.com/silverbulleters/add/blob/develop/plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl#L186 

А в дымовом тесте в тех местах, где могут диалоги внезапно появляться, добавляется вызов, например https://github.com/silverbulleters/add/blob/develop/tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl#L176

**Comment by artbear** [comment]
Провели расследование.

Штатные окна с заголовком "1С:Предприятие" сейчас УЖЕ нормально отрабатываются и закрываются. проверяли в версии 6.4.0

Предлагаю ишуз закрыть.

@VladFrost @theshadowco @ovcharenko-di Если несогласны, давайте уточнения и пояснения, в каких случаях остались проблемы.
