### ISSUE TITLE
Не работает заполнение поля Каталог проекта ADD

### ISSUE THREAD

**Issue by ripreal** [silverbulleters/add#462]
**Описание ошибки**
Поле интерфейса Каталог Проекта не заполняется по-умолчанию, в случае если 1С-ка запускается с одного диска, а репозиторий ADD находится на другом диске.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Развернуть тонкий клиент 1С на диск C
2. Склонировать репозиторий ADD на диск D
3. Запустить обработку ADD в тонком клиенте 1С
4. Поле Каталог проекта на вкладке Сервис будет пустым, 

**Ожидаемое поведение, если бы ошибки не было**
Поле Каталог проекта должно указывать на корневую директорию репозитория ADD

**Окружение:**

 - Windows 10
 - 1C 8.3.12.1684
 - ADD 5.8.0
 - Runner 1.6

**Comment by artbear** [comment]
Выполнено в #463
