### ISSUE TITLE
Добавить возможность открывать произвольную форму плана видов характеристик

### ISSUE THREAD

**Issue by ovcharenko-di** [silverbulleters/add#465]
**Существует проблема**
Есть необходимость в шаге, который бы позволял открывать произвольную форму плана видов характеристик

**Хотелось бы иметь следующую функциональность**
Я открываю основную форму плана вида характеристик "ДополнительныеРеквизитыИСведения"

**Дополнительный контекст**
Сделать можно по аналогии с имеющимися шагами.

**Comment by artbear** [comment]
выполнено в https://github.com/silverbulleters/add/pull/470
