### ISSUE TITLE
В кнопконажималке для числовых полей генерируется шаг И в таблице "Товары" из выпадающего списка "Количество" я выбираю по строке '12,000' приводящий к ошибке

### ISSUE THREAD

**Issue by asheichenko** [silverbulleters/add#468]
**Описание ошибки**
При генерации шагов в режиме кнопконажималки для числовых полей генерируется шаг
`И в таблице "Товары" из выпадающего списка "Количество" я выбираю по строке '12,000'`
который при воспроизведении приводит к ошибке 
![Ошибка шага](https://user-images.githubusercontent.com/8320910/56652400-f3526600-6693-11e9-9e30-95b1e3dbe11c.PNG)
 
Когда я заменяю на шаг:
`И в таблице "Товары" в поле "Количество" я ввожу текст '12,000'`
шаг проходит

**Окружение:**
 - Версия операционной системы: `Windows 10 (64)`
 - Редакция платформы 1С `8.3.12.1790`
 - Версия `Vanessa.ADD`  `5.8.0`
 - Версия `OneScript`  `1.1.0.325`]

**Comment by artbear** [comment]
исправлено в рамках https://github.com/silverbulleters/add/issues/441
