### ISSUE TITLE
Ошибка при отключении конкретного теста открытия формы справочников в файле настроек

### ISSUE THREAD

**Issue by mkulbarakov** [silverbulleters/add#471]
**Описание ошибки**
Вызывается исключение при загрузке файла настроек для дымового теста "Открытие форм конфигурации". Обработка не может определить МассивИсключений.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть xddTestRunner.epf
2. Запустить внешний инструмент "Управление дымовыми тестами"
3. Сделать настройки как на скриншоте 1 и 2. Т.е. отключить конкретные тесты справочника, не объекты.
4. Сохранить файл;
5. Попытаться загрузить в обработку xddTestRunner.

**Ожидаемое поведение, если бы ошибки не было**
Файл загрузился без ошибок, в тест не попали исключенные полностью справочники.

**Скриншоты**
Скриншот 1. Файл настроек с ошибкой.
![image](https://user-images.githubusercontent.com/40254531/56727337-b319e300-677a-11e9-95be-09576f92cb8a.png)

Скриншот 2. Настройки через "Управление дымовыми тестами".
![image](https://user-images.githubusercontent.com/40254531/56727816-ad70cd00-677b-11e9-9386-70377c3535d1.png)

Скриншот 3. Возникающая ошибка при загрузке файла настроек.
![image](https://user-images.githubusercontent.com/40254531/56727869-c6797e00-677b-11e9-8d50-fc445243c19d.png)

**Окружение:**

 - Версия операционной системы: win 10
 - Редакция платформы 1С 8.3.14
 - Версия `Vanessa.ADD` 5.8.0

**Comment by artbear** [comment]
Исправлено в ветке девелоп
