### ISSUE TITLE
Преобразование значения к типу Булево не может быть выполнено "Если Не ФормыДобавлены Тогда"

### ISSUE THREAD

**Issue by witales** [silverbulleters/add#475]
**Описание ошибки**
Ошибка при загрузке дымовых тестов

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть 'xddTestRunner'
2. Нажать 'Загрузить тесты из файлов'
3. Выбрать 'smoke/Тесты_ОткрытиеФормКонфигурации'
4. Возникает ошибка
"{ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.Форма.УправляемаяФорма.Форма(546)}: Преобразование значения к типу Булево не может быть выполнено
    Если Не ФормыДобавлены Тогда"

**Ожидаемое поведение, если бы ошибки не было**
Ошибки не должно быть.

Ошибка возникает из-за того, что у пользователя нет прав на объект, в итоге проверяется значение неинициализированной переменной.

**Окружение:**

 - Версия операционной системы: `Windows 7 (64)`
 - Редакция платформы 1С:Предприятие `8.3.10.2466`
 - Версия `Vanessa.ADD` `5.8.0`
 - Версия `OneScript` `1.0.21.1`

**Дополнительный контекст**

- Типовая конфигурация Управление торговлей, редакция 11 (11.4.5.63)
- Режим защиты от опасных действий отключен.

**Comment by artbear** [comment]
Выполнено в https://github.com/silverbulleters/add/pull/476
