### ISSUE TITLE
В обработке ПроверкаРежимаБлокировки проверяются объекты вида "Нумераторы документов", хотя не должны

### ISSUE THREAD

**Issue by ovcharenko-di** [silverbulleters/add#481]
**Описание ошибки**
Если в конфигурации определен нумератор документов, то при генерации тестов по проверке режима блокировки по этому объекту создается тест, который всегда падает, так как у объекта нет свойства "РежимУправленияБлокировкойДанных"

**Сценарий воспроизведения**
В конфигурации создать нумератор документов, запустить проверку режима блокировок. Увидеть, что тест по нумератору сгенерировался и упал.

**Ожидаемое поведение, если бы ошибки не было**
Для объектов коллекции "Метаданные.НумераторыДокументов" тесты по проверке режима блокировки не должны создаваться вообще.

**Comment by artbear** [comment]
Реализовано в https://github.com/silverbulleters/add/pull/482
