### ISSUE TITLE
В поставке 6.0.0 появилась лишняя обработка в /tests/smoke/

### ISSUE THREAD

**Issue by ovcharenko-di** [silverbulleters/add#483]
**Описание ошибки**
Версия 6.0.0
При установке через `opm install add` в каталоге `/tests/smoke/` появляется "лишняя" обработка:

Тесты_ОткрытиеФормКонфигурации_ЧерезКлиентТестирования.epf

**Comment by artbear** [comment]
Да, есть такой баг, сам увидел на Пульском хакатоне :(

особенности сборки.

**Comment by artbear** [comment]
Исправлено.
