### ISSUE TITLE
Инструкция для создания видеоинструкций

### ISSUE THREAD

**Issue by theshadowco** [silverbulleters/add#486]
**Если выполнять настройку по приложенной инструкции, то создание видеоинструкций не работает**

Если воспользоваться описанием https://github.com/Pr-Mex/vanessa-automation/blob/develop/MakeAutoVideo.md, видеоинструкции создаются без ошибок.

**Comment by artbear** [comment]
@theshadowco Спасибо за ишуз.
Исправим.

**Comment by artbear** [comment]
Исправлено.
