### ISSUE TITLE
ошибка запуска в режиме совместимости 8.3.5 и ниже add 6.0

### ISSUE THREAD

**Issue by grahovsky** [silverbulleters/add#487]
**Описание ошибки**
При использовании конфигурации в режиме совместимости 8.3.5 при загрузке стандартной библиотеки шагов после открытия bddRunner.epf возникает ошибка "функция не найдена СтрШаблон("

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Установить режим совместимости конфигурации 8.3.5
2. Открыть bddRunner.epf
..
4. Где ошибка
add\features\libraries\Файлы\step_definitions\Файловые_операции\Файловые_операции\Forms\Форма\Ext\Form\Module.bsl

**Ожидаемое поведение, если бы ошибки не было**
Обработка не закрылась бы с ошибкой

**Окружение:**

 - Версия операционной системы: `Windows 10 (64)`
 - Редакция платформы 1С [`8.3.10.2699`]
 - Версия `Vanessa.ADD` [`6.0.0`]
 - Версия `OneScript` [`1.0.21`]

**Дополнительный контекст**

- **не типовая** конфигурация ?
- Включен ли режим защиты от опасных действий и т.д. - отключен для пользователя под которым выполнен запуск

**Comment by artbear** [comment]
Это внесенная ошибка, будет исправлено в ближайшее время

**Comment by artbear** [comment]
Исправлено. Будет в релизе 6.1.0
