### ISSUE TITLE
Ошибка проверки условия "Если ... Тогда" на add 6.0.0

### ISSUE THREAD

**Issue by StupnikovVG** [silverbulleters/add#488]
**Описание ошибки**
На версии 6.0.0 шаги проверки условия вида: 
"Если "$$ТестУсловиеИзКонтекста$$" тогда"

стали падать с ошибкой: 
"22.05.2019 9:45:27 {ВнешняяОбработка.bddRunner.Форма.УправляемаяФорма.Форма(4854)}: Ошибка компиляции при вычислении выражения или выполнении фрагмента кода: {(1,1)}: Переменная не определена (Да)

Технические данные:
        ИмяФайла: C:\Program Files (x86)\OneScript\lib\add\features\libraries\Условие\step_definitions\Условие.epf
        ИмяПроцедуры: Условие
        ВерсияVanessaADD: ver 6.0.0
        ВерсияПлатформы: 8.3.12.1595
        РежимСовместимостиTestManager: Версия8_3_8"

Можно обойти ошибку переписав условие на:
"Если "$$ТестУсловиеИзКонтекста$$ = Истина" тогда"

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Создать feature-файл вида: 
	И Я запоминаю значение выражения "Истина" в переменную "ТестУсловие" глобально
	Если "$$ТестУсловие$$" тогда
2. Запустить выполнение фичи в add версии 6.0.0
4. Получить сообщение об ошибке

**Ожидаемое поведение, если бы ошибки не было**
Проверка условия вида "Если "$$ТестУсловиеИзКонтекста$$" тогда" отрабатывает без ошибки.

**Окружение:**

 - Версия операционной системы: `Windows 10 (64)`
 - Редакция платформы 1С: 8.3.12.1595
 - Версия `Vanessa.ADD`: 6.0.0
 - Версия `OneScript`: `1.0.21.1`

**Comment by artbear** [comment]
@StupnikovVG Интересный кейс, подумаю.

**Comment by artbear** [comment]
Это особенность реализации удобного чтения переменных контекста.

по-другому не сделаешь.

придется использовать 
- или указанный в шапке обходной путь
- или `выражение встроенного языка "" Истинно`

закрываю.
