### ISSUE TITLE
Ошибка выполнения шага "тогда талица "ИмяТаблицы" стала равной" на версии 6.0.0

### ISSUE THREAD

**Issue by StupnikovVG** [silverbulleters/add#492]
**Описание ошибки**
Если управляемая форма содержит таблицу, колонки которой сгруппированы, то на версии библиотеки 6.0.0 шаги вида:
  ```
Тогда таблица "ИмяТаблицы" стала равной
  |ИмяКолонки         |
  |ЗначениеКолонки|

```
Стали падать с ошибкой:
   ```
{ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(3811)}: Ошибка   проверки значения таблицы <ИмяТаблицы>. Не найдены колонки: ИмяКолонки

Технические данные:
        ИмяФайла: C:\Program Files (x86)\OneScript\lib\add\features\libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf
        ИмяПроцедуры: ТаблицаСталаРавной
        ВерсияVanessaADD: ver 6.0.0
        ВерсияПлатформы: 8.3.12.1595
        РежимСовместимостиTestManager: Версия8_3_8
```

в случаях, когда проверяются колонки, включенные в группы колонок таблицы.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть ADD, подключить клиент тестирования
2. В клиенте тестирования открыть форму, содержащую таблицу значений со сгруппированными колонками. Активизировать таблицу.
3. В ADD на закладке "Работа с UI" вызвать команду Форма->Получить состояние текущего элемента формы.
4. Получить текст сценария вида:
```
    Тогда таблица "ИмяТаблицы" стала равной
    |ИмяКолонки         |
    |ЗначениеКолонки|
```
6. Нажать кнопку "Подготовить сценарий к выполнению" и запустить подготовленный сценарий
7. Убедиться, что сценарий отрабатывает с ошибкой

**Ожидаемое поведение, если бы ошибки не было**
Подготовленный сценарий отрабатывает без ошибки

**Окружение:**

 - Версия операционной системы: `Windows Server 2016 Standart (64)`
 - Редакция платформы 1С 8.3.12.1595 (база в режиме совместимости с 8.3.8)
 - Версия `Vanessa.ADD` 6.0.0
 - Версия `OneScript` 1.0.21

**Дополнительный контекст**

Ошибка появилась из-за того, что в версии 6.0.0 в обработке "РаботаСИнтерфейсом.epf" в функции "ПолучитьОшибкаНетКолонок" получение колонок вместо метода "НайтиОбъекты()" получается методом "ПолучитьПодчиненныеОбъекты()". Метод "ПолучитьПодчиненныеОбъекты" возвращает только объекты, непосредственно подчиненные таблице. Т.е. в случае группировки колонок, он вернет группу колонок, но не вернет колонки, входящие в эту группу.

**Comment by artbear** [comment]
@StupnikovVG круто, отличное исследование, спасибо!

**Comment by artbear** [comment]
Выполнено в #510 

Огромное спасибо и @StupnikovVG и @ovcharenko-di !
