### ISSUE TITLE
В плагине СериализаторMXL не работает сохранение макета в файл в клиент-сервере, если не поддерживаются асинхронные вызовы

### ISSUE THREAD

**Issue by 1cgh** [silverbulleters/add#496]
**Описание ошибки**
В плагине СериализаторMXL не работает сохранение макета в файл в клиент-сервере, если не поддерживаются асинхронные вызовы

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть плагин СериализаторMXL в ИБ без поддержки асинхронных вызовов. База должна быть клиент-серверная.
2. Нажать кнопку 'Сохранить макет данных в файл'
3. Указать каталог и имя файла **на клиенте**.
4. После нажатия кнопки 'Сохранить' в системном диалоге получить ошибку 'Каталог ... не найден'.
5. Из-за отсутствия директивы компиляции обработчик сохранения макета выполняется на сервере и сохраняет файл на сервере, а должен на клиенте.
https://github.com/silverbulleters/add/blob/master/plugins/%D0%A1%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%82%D0%BE%D1%80MXL/%D0%A1%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%82%D0%BE%D1%80MXL/Forms/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L139

**Ожидаемое поведение, если бы ошибки не было**
Сохранение макета в файл происходит успешно на клиенте

**Comment by artbear** [comment]
@1cgh интересно, посмотрю.

**Comment by 1cgh** [comment]
@artbear  там просто надо &НаКлиенте поставить у синхронного обработчика. сейчас там ничего не стоит, т.е. он выполняется на сервере

**Comment by artbear** [comment]
выполнено в https://github.com/silverbulleters/add/pull/498
