### ISSUE TITLE
Как с этим работать?

### ISSUE THREAD

**Issue by khorevaa** [silverbulleters/add#50]
Все делаю несколько подходов к чтению реадми и никак понять с чего начать не могу

**Comment by nixel2007** [comment]
@khorevaa оно еще не в релизе. поэтому пока условно "никак"

**Comment by artbear** [comment]
точнее, в ридми "условно" указано, как начать работать :)

2 способа установки
+ гитхаб
+ хаб оскрипта
  + для этого практически все сделано, но пока официально релиз не выпущен
  + добиваем остатки

использование как обычно
+ behavior/фичи - bddRunner (наследник vanessa-behavior)
+ тесты в коде - xddTestRunner (наследник xUnitFor1C)

**Comment by khorevaa** [comment]
Хорошо, но все равно ничего не понятно! -))
Хотелось бы минимальное описание с заголовком "Быстрый Старт"

**Comment by artbear** [comment]
А тебе нужно что ?
+ В режиме контрибьютора? смотри https://github.com/silverbulleters/add/blob/develop/.github/CONTRIBUTING.md

+ В режиме пользователя? я выше написал https://github.com/silverbulleters/add/issues/50#issuecomment-361061082

что еще?

**Comment by khorevaa** [comment]
Расшифровать слово как обычно- для тех кто не знает как обычно! -)

**Comment by artbear** [comment]
Документировано
