### ISSUE TITLE
Не передается параметр ОткрываемФормыНаКлиентеТестирования из конфигурационного файла для дымовых тестов открытия форм

### ISSUE THREAD

**Issue by KeynihAV** [silverbulleters/add#503]
**Описание ошибки**
При запуске дымох тестов открытия форм, если установить в конфигурационном файле "ОткрываемФормыНаКлиентеТестирования": false все равно запускается клиент тестирования.

**Сценарий воспроизведения**
Запустить дымовые тесты через vanessa-runner - vrunner xunit --settings ./vRunner.json в файле настроек smoke.json указать "ОткрываемФормыНаКлиентеТестирования": false. Откроется клиент тестирования.

**Ожидаемое поведение, если бы ошибки не было**
Тесты запускаются в том же сеансе.

**Окружение:**
 - Редакция платформы 1С [`8.3.12`]
 - Версия `Vanessa.ADD` [`6.0.0`]

Если говорить про конкретный код, то есть предположение.  
[Вот одно из условий, в котором фигурирует глобальная клиентская переменная](https://github.com/silverbulleters/add/blob/2e7fe8e2e9291d6f3fad2bd270e564134de3b685/tests/smoke/%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/%D0%A2%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/Forms/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L573)

[А вот загрузка настроек, она эту переменную не заполняет, а заполняет реквизит](https://github.com/silverbulleters/add/blob/2e7fe8e2e9291d6f3fad2bd270e564134de3b685/tests/smoke/%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/%D0%A2%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/Forms/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L743)

**Comment by artbear** [comment]
Выполнено @KeynihAV в #504 - большое спасибо!
