### ISSUE TITLE
Ошибка выполнения шага "И я нажимаю на гиперссылку с именем "" " на версии 6.0.0 для форматированной строки

### ISSUE THREAD

**Issue by daryafret** [silverbulleters/add#505]
**Описание ошибки**
Не происходит переход по гиперссылке, представленной форматированной строкой. В процессе накликивания переход "проглатывается", т.е. идет шаг до (например, заполнение поля) и сразу же "Тогда открылось окно". При попытке добавить шаг вручную:
```
И я нажимаю на гиперссылку с именем "ГиперссылкаПерейтиСерииНоменклатуры"
```
или аналогичный ему шаг без имени,
падает с ошибкой:
```
24.06.2019 14:33:20 {ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(3561)}: Ошибка при вызове метода контекста (Нажать): Неподходящий тип элемента управления для вызванного действия.

Технические данные:
        ИмяФайла: C:\Users\d.smirnova\Desktop\Коробка\Тестирование\add-6.0.0\features\libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf
        ИмяПроцедуры: ЯНажимаюНаГиперссылкуСИменем
        ВерсияVanessaADD: ver 6.0.0
        ВерсияПлатформы: 8.3.13.1644
        РежимСовместимостиTestManager: Версия8_3_12
```

**Сценарий воспроизведения**
*Сценарий накликивания*:
1. Открыть ADD, подключить клиент тестирования
2. В клиенте тестирования открыть форму, содержащую гиперссылку, представленную форматированной строкой
3. Начать запись шагов пользователя
4. Нажать на гиперссылку
5. Остановить запись шагов пользователя.
6. Убедиться, что шаг нажатия гиперссылки не записан

*Сценарий добавления шага вручную*:
1. Открыть ADD, подключить клиент тестирования
2. В клиенте тестирования открыть форму, содержащую гиперссылку, представленную форматированной строкой
3. В ADD на закладке "Работа с UI" через команду "Форма" -> "Получить состояние текущего элемента формы" получить текст сценария вида:
```
И я нажимаю на гиперссылку с именем "ИмяГиперссылки"
```
4. Нажать "Подготовить сценарий к выполнению" и запустить данный сценарий.
5. Получить неотработанный сценарий и ошибку, описанную в "Описание ошибки" выше

**Ожидаемое поведение, если бы ошибки не было**
1. При накликивании шаг создается автоматически.
2. Сценарий, созданный вручную, отработает без ошибки.

**Окружение:**

 - Версия операционной системы: `Windows Server 2012 R2 Standart (64)`
 - Редакция платформы 1С :  `8.3.13.1644`
 - Версия `Vanessa.ADD`: `6.0.0`
 - Версия `OneScript` -

**Comment by artbear** [comment]
@daryafret а можете привести xml-текст, который формируется на соответствующей закладке в окне "Работа с UI" ?

**Comment by AndreyDanilov-nn** [comment]
@artbear 
```
Сценарий: <описание сценария>

	Когда открылось окно 'Смесь 50% (Номенклатура)'
	И я перехожу к закладке "Дополнительно"
	Тогда открылось окно 'Виды анализов позиции номенклатуры Смесь 50%'
	И Я закрываю окно 'Виды анализов позиции номенклатуры Смесь 50%'
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<uilog xmlns:d1p1="http://v8.1c.ru/8.3/uilog">
	<ClientApplicationWindow caption="Смесь 50% (Номенклатура)">
		<Form title="Смесь 50% (Номенклатура)">
			<FormGroup name="ГруппаСтраницы" title="Страницы">
				<FormGroup name="СтраницаДополнительно" title="Дополнительно">
					<activate/>
					<FormField name="СтавкаНДС" title="Ставка НДС">
						<activate/>
					</FormField>
					<FormDecoration name="ГиперссылкаПерейтиВидыАнализов" title="Виды анализов качественных показателей (0)">
						<activate/>
						<clickFormattedStringHyperlink title="Виды анализов качественных показателей (0)"/>
					</FormDecoration>
				</FormGroup>
			</FormGroup>
		</Form>
	</ClientApplicationWindow>
	<ClientApplicationWindow caption="Виды анализов позиции номенклатуры Смесь 50%">
		<close/>
	</ClientApplicationWindow>
</uilog>
```

**Comment by artbear** [comment]
Выполнено. будет в 6.4.0

**Comment by artbear** [comment]
Реализованы новые шаги для работы с гиперссылками в формах 
-  И я нажимаю на гиперссылку 'Гиперссылка2' для поля "Форматированная строка"
-  И я нажимаю на гиперссылку 'Гиперссылка1' для поля с именем "ФорматированнаяСтрокаСсылка"
