### ISSUE TITLE
Ошибка "папка temp\vanessa-add не найдена"

### ISSUE THREAD

**Issue by forsaled** [silverbulleters/add#506]
**Описание ошибки**
1. Открыл обработку, включил УИ, записал сценарий, жму Подготовить сценарий. Вываливается ошибка о том, что папка Ц-Юзерс-итакдалее\Temp\vanessa-add не найдена. Оказалось, что темповый файл пытается туда записать, хотя эту папку никто не создавал. 

**Окружение:**
Версия `Vanessa.ADD`  `5.8.0`
Типовая

**Comment by artbear** [comment]
@forsaled Проверь на 6.0.0, пожалуйста. Вроде бы было исправление на эту тему.

**Comment by forsaled** [comment]
Да, на 6.0.0 ошибка исчезла, спасибо!
