### ISSUE TITLE
Использование разных машин для сервера и клиента приводит к ошибке

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/add#518]
**Описание ошибки**
При запуске xddTestRunner.epf ошибка:
```
Значение не является значением объектного типа (Инициализация)
{ВнешняяОбработка.xddTestRunner.МодульОбъекта(65)}:		Плагин.Инициализация(ЭтотОбъект);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(449)}:	ОписанияЗагрузчиков = ОбъектНаСервере.ПолучитьОписанияПлагиновПоТипу(ОбъектНаСервере.ТипыПлагинов.Загрузчик);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(421)}:	ОписанияЗагрузчиков = ПолучитьОписанияЗагрузчиковНаСервере();
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(333)}:	ДобавитьКомандыЗагрузчиковНаФорме();
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(327)}:	ЗагрузкаПлагиновЗавершение();
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(302)}:	ПодключитьНайденныеКлиентскиеПлагины(ПомещенныеФайлы, ДополнительныеПараметры.ИдентификаторыПлагинов);
```

**Сценарий воспроизведения**
Шаги по воспроизведению:
- Сделать сервер на одной машине (Я так понял, что неважно разные ОСи на машинах или нет, на винде скорее всего такая же была бы проблема)
- Запустить клиент на другой машине
- Открыть xddTestRunner.epf

**Окружение:**

Сервер 1С на debian 9
Клиент на windows 10
Платформа 8.3.15.1489
Vanessa.ADD 5.8.0 и 6.0.0

**Comment by artbear** [comment]
@viskvortsov эта проблема известна https://github.com/silverbulleters/add/issues/447

Решено в ветке девелоп.

будет в релизе 6.1.0 на этой или на следующей неделе.
