### ISSUE TITLE
Ошибка при отключении теста открытия формы справочников в файле настроек

### ISSUE THREAD

**Issue by ViktorErmakov** [silverbulleters/add#520]
После загрузки настроек указанных ниже, и нажатии кнопки "Перезагрузить" выходит ошибка.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Запускаем XdRunner
2. Нажимаем внешние инструменты, управление дымовыми тестами
3. Указываем такие настройки 
![изображение](https://user-images.githubusercontent.com/39617680/62734464-c3a44f80-ba31-11e9-9f4e-9295b196ac70.png)
p.s. возможны разные комбинации

4. Сохраняем эти настройки в файл.
5. в XddRunner загружаем обработку открытия форм, и созданный файл настроек.
6. Нажимаем кнопку "Перегрузить"
Вот тут и получаем ошибку:
![изображение](https://user-images.githubusercontent.com/39617680/62734583-05cd9100-ba32-11e9-9a26-b324a1bb1501.png)

**Окружение:**
не важно, т.к. программный косяк.

**Comment by artbear** [comment]
@ViktorErmakov  Да, инструмент по управлению дымовыми еще сыроват.

я лично работаю с ним так:
- использую существующий файл настроек из поставки Ванесса-АДД smoke.json
- загружаю его в инструменте
- ставлю нужные галочки
- сохраняю снова в файл

тогда точно нет проблем.

**Comment by ViktorErmakov** [comment]
Артур спасибо! Я там нашел косяк в коде, предложил его исправить в пулл реквесте, и тогда эти настройки работают нормально. Но там нужно понимать бизнес логику кода, правильно ли я понял и исправил, или нет. Сможешь посмотреть?
Спасибо!

**Comment by artbear** [comment]
Выполнено в #524
