### ISSUE TITLE
При выполнении дымовых тестов, не открываются отчеты с общими формами

### ISSUE THREAD

**Issue by lashmyash** [silverbulleters/add#532]
**Описание ошибки**
При выполнении дымового теста "Открытие форм конфигурации" проверка отчетов, у которых нет своих форм, а они выбраны из Общих форм проваливается выполнение теста.
Например:

`{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(1612)}: [Failed] Выявлено модальное окно:[Переход по кнопке командного интерфейса] Неизвестное имя формы. Имя: "e1cib/app/Отчет.ЖурналОперацийЭлектронныеПодписи.Форма" 	ВызватьИсключение Префикс + " " + СообщениеОшибки;`

**Окружение:**

 - Редакция платформы 1С 8.3.14.1854
 - Версия `Vanessa.ADD` 6.0.0
 - Версия `OneScript` 1.1.1.44

**Comment by ViktorErmakov** [comment]
коллеги, я посмотрю в чем проблема

**Comment by artbear** [comment]
@ViktorErmakov Отлично, ждем  результатов.

**Comment by SergeyKud** [comment]
Проверил два варианта на версии из ветки develop, при условиях:
- выбрана форма
- поле формы отчёта пустое и используется форма по умолчанию

Ошибка не повторилась. Все тесты отрабатывают корректно.

**Comment by artbear** [comment]
@ViktorErmakov удалось разобраться с проблемой?

@lashmyash @ViktorErmakov Коллеги, у вас точно повторяется именно эта проблема?
мы не смогли повторить ее (

**Comment by ViktorErmakov** [comment]
Коллеги, меня загрузили по самый не балуй. Я еще не проверял, завтра попробую уделить время поговорить с инициатором.

**Comment by AndreyGubin** [comment]
@artbear Добрый день. 
Удалил OneScript, поставил актуальный билд с официального сайта v1.1.1 от 19.07.2019.
Установил пакеты командами:
opm install add
и
opm install vanessa-runner
Скачал с гитхаба версии 6.0.0, 6.1.0 и закинул их в каталог OneScript/lib под именами add600 и add610
Закинул свои конфиги vrunner.json и xUnitParams.json
Итог:
На версии 6.0.0 при прогоне тестов через Тесты_ОткрытиеФормКонфигурации.epf все падают с ошибкой как у @lashmyash 
На версиях 6.1.0 и 6.2.0 падают с ошибками (привожу одну как пример, все они отличаются только именем):
```
{ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.Форма.УправляемаяФорма.Форма(591)}: Ошибка при вызове метода контекста (ОткрытьФорму)
		ТестируемаяФорма = ОткрытьФорму(ПолноеИмяФормы, ПараметрыФормы,, Новый УникальныйИдентификатор);
по причине:
Неизвестное имя формы. Имя: "Справочник.ах_ВидыТорговогоМеста"
```

Я связывался с нашим разработчиком 1С, он ответил, что так не должно быть, нужно вызывать форму: ОткрытьФорму("Справочник.ах_ВидыТорговогоМеста.ФормаОбъекта");

**Comment by ViktorErmakov** [comment]
Проблему я нашел и понял как ее сымитировать. Посмотрю на следующей неделе.

**Comment by ViktorErmakov** [comment]
Коллеги, вопрос:
![изображение](https://user-images.githubusercontent.com/39617680/65368490-5566c580-dc4a-11e9-847d-c6a819250e0c.png)
Вот тут, если формы объекта не были получены, то добавляется полное имя объекта метаданных в список. Так надо? Именно эту строку потом и пытается ОткрытьФорму использовать, а там "Справочник.ах_ВидыТорговогоМеста"

**Comment by artbear** [comment]
Извините за молчание - небольшой отпуск и болезнь (

Подумаю.

**Comment by artbear** [comment]
В файле xUnitParams.json включена настройка выполнения дымовых на тест-клиенте?

**Comment by ViktorErmakov** [comment]
В общем попробую описать письменно, т.к. с Артуром по времени не сходимся поболтать.
По первой ошибке: 
Есть отчет бспшный (2.4.6) "АнализЖурналаРегистрации" у него указаны формы отчета, настроек общие, которые уже указаны в свойствах конфигурации.
![изображение](https://user-images.githubusercontent.com/39617680/65719465-8746b480-e0ae-11e9-95ff-1eead45f78d5.png)
В "ОткрытиеФормКонфигурации_УправляемаяФорма_Строка 513
содержится код
![изображение](https://user-images.githubusercontent.com/39617680/65719572-beb56100-e0ae-11e9-97f2-88a1c800b32f.png)
Это приводит к тому, что когда тестирование идет в клиенте тестирования используется метод
![изображение](https://user-images.githubusercontent.com/39617680/65719687-fb815800-e0ae-11e9-89a5-0e78750cd52f.png)
А для этого метода, добавленный текст ".Форма" и ".ФормаНастроек" лишние, навигационные ссылки этого не терпят, и не открывают окно.
А вот если бы тест выполнялся в менеджере тестирования, тогда для метода "ОткрытьФорму(..)" как раз этот текст и нужен.

По второй ошибке обратная ситуация:
Есть некоторый отчет, где формы не указаны, а наследуются из конфигурации
![изображение](https://user-images.githubusercontent.com/39617680/65719841-5a46d180-e0af-11e9-9c6f-a757654e77e3.png)
Тогда при загрузке форма добавиться вот таким образом
![изображение](https://user-images.githubusercontent.com/39617680/65719899-7c405400-e0af-11e9-9afb-28c72983c1a3.png)
т.е. "Отчет.АнализЖурналаРегистрации_Мой" без указания формы.
Если тестирование будет через клиента тестирования, то никаких ошибок не будет и все пройдет успешно.
А вот если тестирование будет идти в менеджере тестирования, то метод
"ОткрытьФорму(...)" ругнется на открытие этой формы, и тест падает.

Хотел исправить через значение "ОсновнойОбъект.ОткрываемФормыНаКлиентеТестирования", но это свойство всегда содержит "Да" при загрузке настроек, при том, что в файле xUnitParams изменил на false "ОткрываемФормыНаКлиентеТестирования". Так что как исправить я пока не знаю, Подсказывай Артур что будем делать))

**Comment by AndreyGubin** [comment]
> В файле xUnitParams.json включена настройка выполнения дымовых на тест-клиенте?

Нет. В какой-то момент у меня была проблема с открытием тест-клиента и я отключил настройку. Сейчас попробую поменять, Спасибо за совет.

`        "СтрогийПорядокВыполнения":true,
        "ОткрываемФормыНаКлиентеТестирования":false,

        "ВыводитьСообщенияВЖурналРегистрации":true,
        "ИсключитьФормыЗависящиеОтОтключенныхФункциональныхОпций":true,

        "СпособГруппировки":"ПоВидуМетаданных",
        "КоличествоВГруппе":1,`

**Comment by AndreyGubin** [comment]
Исправил false на true, тесты сыпятся с самого первого:

```
ИНФОРМАЦИЯ - ОШИБКА:
ИНФОРМАЦИЯ - {ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.Форма.УправляемаяФорма.Форма(1133)}: Выявлено окно, которое не закрывается!
ИНФОРМАЦИЯ - Возможно, это модальное окно.
ИНФОРМАЦИЯ - Заголовок окна <Сообщения системы>
ИНФОРМАЦИЯ - ВызватьИсключение ТекстИсключения;
```

**Comment by artbear** [comment]
а что за окно Заголовок окна <Сообщения системы> ?
что там при открытии приложения 1С?

**Comment by artbear** [comment]
@AndreyGubin ?

**Comment by AndreyGubin** [comment]
У нас есть одна обработка с таким заголовком, это окно с информацией о новом функционале. 
- В самом приложении 1С оно отображается один раз для одного пользователя.
- Данное окно не закрывается на крестик, его можно закрыть только нажатием на кнопку "Ознакомлен" (такое было требование заказчика)
- При прогоне тестов данное окно не отображается
- В файле xUnitParams.json я добавил строки, которые по идее должны исключить эту обработку

```
"Справочники": {
            "Подчиненные": {
            },
            "ЗначенияРеквизитовНовых": {
            },
            "Списки": [
           "Справочник.дт_ОбращенияГражданПрисоединенныеФайлы",
           "Справочник.дт_ОбследованияТорговыхПредприятий",
           "дт_ОбследованияТорговыхПредприятий",
"Справочник.хс_СообщенияСистемы",
"хс_СообщенияСистемы"

            ],
            "Существующие": [
                "ПодчиненныйСДвумяВладельцами",
                "СправочникСОбязательнымРеквизитом",
                "Справочник.дт_ОбследованияТорговыхПредприятий",
                "дт_ОбследованияТорговыхПредприятий",
"Справочник.СообщенияСистемы.Форма.ФормаЭлемента",
"Справочник.хс_СообщенияСистемы.Форма.ФормаЭлемента",
"СообщенияСистемы.Форма.ФормаЭлемента",
"хс_СообщенияСистемы.Форма.ФормаЭлемента"              
            ],
            "Новые": [
                "ПодчиненныйСДвумяВладельцами",
                "СправочникСОбязательнымРеквизитом",
                "Справочник.дт_ОбследованияТорговыхПредприятий",
                "дт_ОбследованияТорговыхПредприятий",
                
"Справочник.ДополнительныеОтчетыИОбработки",
"ДополнительныеОтчетыИОбработки",
"Справочник.СообщенияСистемы.Форма.ФормаЭлемента",
"Справочник.хс_СообщенияСистемы.Форма.ФормаЭлемента",        
"СообщенияСистемы.Форма.ФормаЭлемента",
"хс_СообщенияСистемы.Форма.ФормаЭлемента",
"Справочник.СертификатыКлючейЭлектроннойПодписиИШифрования",
"СертификатыКлючейЭлектроннойПодписиИШифрования"

            ]
        },
        "Документы": {
            "Списки": [
            ],
            "Существующие": [
            ],
            "Новые": [
            ],
            "ПеренестиДату": [
            ]
        },
        "Отчеты": [
"Отчет.дт_ЗаканчивающиеДействиеДоговоры",
"дт_ЗаканчивающиеДействиеДоговоры"
        ],
        "Обработки": [
            "ОткрытьVanessaADD",
            "ТестОбработка_Форма_ИсключениеПриОткрытии",
"Обработка.УдалениеПомеченныхОбъектов",
"УдалениеПомеченныхОбъектов"
        ],
        "ПропускаемыеИсключения" : [
            "Обработка не предназначена для непосредственного использования"
        ]
    }
}
```

**Comment by artbear** [comment]
>Данное окно не закрывается на крестик, его можно закрыть только нажатием на кнопку "Ознакомлен" (такое было требование заказчика)
При прогоне тестов данное окно не отображается

@AndreyGubin а это модальное окно или окно, блокирующее интерфейс?
если да, это грустно
ведь его еще автоматом закрыть нельзя (

Предложение 1 - при открытии этого окна проверять ПараметрЗапуска от 1С, и если там есть что-нибудь от Ванесса-АДД (`xddTestRunner` или что-то из ком.строки запуска тестов)
тогда не открывать это окно.
т.е. при интерактивной работе окно открывается, при автозапуске тестов окно не открывается и проблемы не будет.

Предложение 2 (намного сложнее) - сделать спец.тест, который будет запускаться первым при запуске дымовых тестов и выполнять\закрывать подобные "незакрываемые" окна

предложение 1 ИМХО нормально

**Comment by AndreyGubin** [comment]
> а это модальное окно или окно, блокирующее интерфейс?
Оно не блокирует ничего, просто не закрывается, то есть можно открыть еще одно окно или продолжить работу нажав в панели вкладок "Начальная страница". 
После прогона всех тестов с настройкой "ОткрываемФормыНаКлиентеТестирования":false,
 у меня осталось два обычных модальных окна
- Данная форма предназначена для открытия только из формы элемента плана вида характеристик "Вопросы для анкетирования"
- Варианты ответов анкет используются только внешними пользователями.
Тесты не могут сами завершить прогон, пока я их не закрою.
Окна обычные, закрываются на "ок" и "крестик", сейчас попробую добавить в исключения их и самый первый тест. Потом отпишусь о результате.

**Comment by AndreyGubin** [comment]
@artbear прогнал тесты двумя способами:
- с настройкой "ОткрываемФормыНаКлиентеТестирования":false
- с настройкой "ОткрываемФормыНаКлиентеТестирования":true

Могу точно сказать, что с настройкой true список исключенных форм игнорируется, то есть прогон идет по всем формам без исключения.

**Comment by artbear** [comment]
Правильная проверка подобных форм отчетов реализована в https://github.com/silverbulleters/add/pull/570

будет в очередном релизе в ближайшие дни

**Comment by ViktorErmakov** [comment]
Добрый вечер коллеги. Наконец то добрался я до тестов.
Ну как я и предполагал, когда почитал изменения в коде, проблему основную не решили.
Я имею ввиду открытие по навигационной ссылке с Форма.Имя.ОсновнаяФорма в клиенте тестирования не работает, и не будет работать, туда нужно передавать имя без ".ОсновнаяФорма". 
![изображение](https://user-images.githubusercontent.com/39617680/66340684-67d14680-e94e-11e9-8326-7c3160a407cd.png)

Я исправил для тестов и в клиенте и в менеджере, у меня два отчета, один с указанными общими формами, другой с наследуемыми, отработали в двух режимах.
Там есть нюанс, пришлось убрать "ФормаНастроек" т.к. бспшная требует передачи какого то параметра, поэтому пока закомментировал эти строки, что бы тест был без ошибок, жду обсуждения по этому поводу. 
Прошу протестировать мои доработки, во всех описанных вариантах у себя, спасибо!
