### ISSUE TITLE
Client (ordinary application) в проверке общих модулей Tests_SmokeCommonModules.epf

### ISSUE THREAD

**Issue by alexkmbk** [silverbulleters/add#535]
В обработке Tests_SmokeCommonModules.epf из комплекта дымовых тестов, в случае, если в имени модуля есть слово Клиент, проверяется наличие флага"Client (ordinary application)" у общего модуля. 
Однако, в конфигурациях, которые работают только в управляемых режимах, данного крыжика у общих модулей нет, поэтому его физически нельзя установить, а следовательно и исправить данную ошибку нельзя. 

Предлагаю убрать эту проверку из теста.

**Comment by artbear** [comment]
@alexkmbk Сам убрать сможешь? )

**Comment by artbear** [comment]
и сделать пулл-реквест?

**Comment by alexkmbk** [comment]
> 
> 
> и сделать пулл-реквест?

ок, #547

**Comment by artbear** [comment]
Выполнено в #547
