### ISSUE TITLE
Ванесса стала криво получать состояние формы в части Табличных частей

### ISSUE THREAD

**Issue by Wadus16** [silverbulleters/add#536]
**Описание ошибки**
При получении состояния текущего элемента формы для табличной части значения табличной части могут добавляться без таких кавычек ' . Что приводит к ошибке при попытке выполнить такой код.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. В запущенном тест клиенте открыть документ с табличной частью (например "Приобретение товаров и услуг" в ERP), выделить ячейку табличной части
2. В запущенном менеджере тестирования в ванессе нажать на кнопку "Получить состояние текущего элемента формы". 
3. Нажать на кнопку "Подготовить сценарий к выполнению";
4. Запустить подготовленный сценарий.

**Ожидаемое поведение, если бы ошибки не было**
Шаг должен был выполниться без ошибки

**Скриншоты**
http://prntscr.com/p132v8

![image](https://user-images.githubusercontent.com/2920817/64334570-76d87800-cfe1-11e9-97f4-6977b86da244.png)

**Окружение:**

 - Версия операционной системы: `Windows 10 (64)`
 - Редакция платформы 1С `8.3.12.1685`
 - Версия `Vanessa.ADD` [например, `6.0.1`]
 - Версия `OneScript` [например, `1.0.21.1`]

**Дополнительный контекст**

- Типовая или не типовая конфигурация - типовая ERP 2.4.6.230 ?
- Включен ли режим защиты от опасных действий - нет

На версии Add 5.6.0 все работает корректно

**Comment by artbear** [comment]
@Wadus16 Я специально убирал подобные кавычки для увеличения читабельности таблиц и уменьшения количества "шумящих" символов.

Исправим эту проблему.

PS в гитхаб можно сразу удобно прикреплять картинки, просто вставляя их в текст.
Читать становится проще.

что я и сделал по Вашему комментарию )

**Comment by artbear** [comment]
Выполнено в #542
