### ISSUE TITLE
Как прописать пользователя в запросе?

### ISSUE THREAD

**Issue by testforgity** [silverbulleters/add#537]
Здравствуйте, я прописываю: vrunner vanessa --vanessasettings ./tool/VBParams.json --workspace . --ibconnection /SТУТ\ИБ /N"Админ", но у меня не заходит, при этом ругается на юзера(неизвестный параметр), что можно сделать? если не прописывать пользователя, то ругается - пользователь ИБ не идентифицирован

**Comment by testforgity** [comment]
--db-user "USERNAME"

**Comment by testforgity** [comment]
А как решить проблему Неизвестный идентификатор плагина <Загрузки пользовательских настроек>

**Comment by artbear** [comment]
@testforgity использовать версию 6.1.0

**Comment by artbear** [comment]
@testforgity ишуз закрываю как решенный

если будут вопросы, переоткрывайте или создавайте новый

**Comment by testforgity** [comment]
> @testforgity ишуз закрываю как решенный
> 
> если будут вопросы, переоткрывайте или создавайте новый

версию чего 6.1.0? простите за глупый вопрос
