### ISSUE TITLE
Версию чего 6.1.0?

### ISSUE THREAD

**Issue by testforgity** [silverbulleters/add#540]
-А как решить проблему Неизвестный идентификатор плагина <Загрузки пользовательских настроек>?
-использовать версию 6.1.0
-Версию чего 6.1.0?простите за глупый вопрос

**Comment by pumbaEO** [comment]
https://github.com/silverbulleters/add/releases/tag/v6.1.0 скачати разархивировать и указать путь к bddRunner.epf через парамете раннера --vanessapath. Как то так

**Comment by artbear** [comment]
или более штатным путем 
`opm install add`

приедет последняя версия Ванесса-АДД, 6.1.0

**Comment by testforgity** [comment]
а у меня и так последняя версия стоит
