### ISSUE TITLE
Неизвестный идентификатор плагина <Загрузки пользовательских настроек>

### ISSUE THREAD

**Issue by testforgity** [silverbulleters/add#545]
как решить проблему? все что нужно последней версии 100%, так-то там тесты проходят, но закрыть после тестов не получается из-за окна ошибки

**Comment by artbear** [comment]
@testforgity Где подробности?

пока непонятно, что, как и где сломалось?

**Comment by testforgity** [comment]
Пример кода pipeline, иб на сервере (пользователь админ, пароля нет, "безопасный режим" отключил)
pipeline {
    agent {
        label 'bdd'
    }

    stages {
        stage('Testing') {
            steps {
                timestamps {
                    cmd("vrunner vanessa --vanessasettings ./tools/VBParams.json --workspace . --ibconnection /SБЛАБЛА --db-user \"Admin\"")
                }
            }
        }
        stage('Publishing results') {
            steps {
                timestamps {
                    script {
                        def allurePath = tool name: 'allure', type: 'allure'
                        cmd("${allurePath}/bin/allure generate -o out/allure-report out/allure")
                    }

                    publishHTML target: [
                        allowMissing: false, 
                        alwaysLinkToLastBuild: false, 
                        keepAll: false, 
                        reportDir: 'out/allure-report', 
                        reportFiles: 'index.html', 
                        reportName: 'HTML Report', 
                        reportTitles: ''
                    ]

                    step([
                        $class: 'CucumberReportPublisher',
                        fileIncludePattern: '**/*.json',
                        jsonReportDirectory: 'out/cucumber'
                    ])
                }
            }
        }
    }
}

def cmd(command){
    if(isUnix()){
        sh "${command}"
    } else {
        bat "chcp 65001\n${command}"
    }
}

**Comment by artbear** [comment]
@testforgity 
- Платформа 1С какая? 
- режим совместимости конфигурации какой?

А ведь при создании ишуза есть шаблон ошибки, в котором эти вопросы заданы )

**Описание ошибки**
что конкретно происходит

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть '...'
2. Нажать '....'
3. Запустить '....'
4. Где ошибка

**Ожидаемое поведение, если бы ошибки не было**
'....'

**Скриншоты**
если применимо, приложите скриншоты

**Окружение:**

 - Версия операционной системы: [например, `Windows 10 (64)` или `Ubuntu 18.04`]
 - Редакция платформы 1С [например, `8.3.12.1542`]
 - Версия `Vanessa.ADD` [например, `5.6.0`]
 - Версия `OneScript` [например, `1.0.21`]

**Дополнительный контекст**

- Типовая или не типовая конфигурация ?
- Включен ли режим защиты от опасных действий и т.д.

**Comment by testforgity** [comment]
Платформа - 8.3.14.1854
Режим совместимости - 8.3.8
Я создал pipeline(JENKINS), который использует json выше для тестов. Когда я запускаю сборку, подключение к иб происходит без ошибок, однако на этапе открытия(делается это не руками) менеджера тестирования вылетает окошко: |Неизвестный идентификатор плагина <ЗагрузчикПользовательскихНастроек>|, закрыв которое сборка продолжает работать нормально(пока без ошибок), однако если не закрыть, то будет все висеть в режиме ожидания.
OScript - 1.0.21.1
Vanessa.ADD - 6.1.0
ОС - windows 10 (64)
Выключен режим от опасных действий(у пользователя и в configе)

**Comment by testforgity** [comment]
все супер круто
