### ISSUE TITLE
BDD ОФ: У элементов формы не заполнены "Данные"

### ISSUE THREAD

**Issue by sfaqer** [silverbulleters/add#548]
**Описание ошибки**
У всех элементов обычной формы слетели данные

**Ожидаемое поведение, если бы ошибки не было**
Данные заполнены.

**Скриншоты**
![image](https://user-images.githubusercontent.com/32082417/64588857-f5b92080-d3e6-11e9-9fa8-b7f553b4b872.png)
![image](https://user-images.githubusercontent.com/32082417/64588878-06699680-d3e7-11e9-964e-04339b80049d.png)

**Comment by artbear** [comment]
@sfaqer Какая версия Ванесса-АДД ?

**Comment by sfaqer** [comment]
@artbear, 6.1.0, в мастер ветке репа поведение такое же

**Comment by artbear** [comment]
Обход описан в закрытом https://github.com/silverbulleters/add/issues/499

буду проверять на разных платформах, тут явно версия 1С виновата (

**Comment by sfaqer** [comment]
@artbear в #499 была не заполнена ОбработкаОбъект, вероятно тогда же слетели данные у элементов формы. Сейчас ОбработкаОбъект заполнена, а вот данных у элементов формы нет, так что, этот обход тут не взлетит.
Может есть собранная обработка с ещё не побитой формой, чтоб её перевыгрузить?

**Comment by artbear** [comment]
Исправлено в #552

**Comment by artbear** [comment]
На 2х машинах исходное неправильное поведение формы подтвердили.
после исправления и загрузки из исходников форма стала работать верно.
