### ISSUE TITLE
Настройка для исключения форм при тестировании командного интерфейса

### ISSUE THREAD

**Issue by realMaxA** [silverbulleters/add#557]
**Существует проблема**
Обработка "тесты_КомандныйИнтерфейс.epf"
При проверке открытия форм списков внешних источников данных на не настроенной базе появляется и не закрывается служебное окно подключения к внешнему источнику данных.

**Хотелось бы иметь следующую функциональность**
Предлагается два варианта реализации:
1. При появлении окна с заголовком "Подключение к источнику данных" сразу его закрывать
2. Добавить возможность настройки исключений открытия форм. Если форма указана в списке исключений, даже не пытаться её открыть.

**Дополнительный контекст**
Актуально для пустых баз, созданных из исходников для целей тестирования на CI.

**Comment by artbear** [comment]
настройка исключений уже реализовано в 6.2.0

буквально на днях релиз выпущен )

**Comment by artbear** [comment]
проверь описание 6.2.0 и посмотри файл примеров smoke.example.json

**Comment by artbear** [comment]
Выполнено в #574 

@realMaxA Большое спасибо!
