### ISSUE TITLE
Использование тегов severity для формирования отчета Allure 

### ISSUE THREAD

**Issue by pumbaEO** [silverbulleters/add#560]
**в allure отчет по умолчанию уровень ошибки ставит normal**

**Хотелось бы иметь следующую функциональность**
`Функционал: размечать тегами фичи и сценарии 
   Как QA, заказчик , РП
   Я хочу размечать тегами сценарии и фичи
   Чтобы отчет Allure был более информативным

Контекст:
  Дано: <версия инструментария> любая
  И <полная версия 1С> какая угодно
  и <конфигурация запуска> любая

Сценарий: установка тега severity
  Допустим: Я помечаю сценарий тегом @normal
  Когда: формируется отчет allure
  Тогда: он выглядит так:`

![зображення](https://user-images.githubusercontent.com/166003/65038776-69b07700-d959-11e9-9d10-8583b4c77315.png)

Все теги подробно описаны тут https://github.com/allure-framework/allure-csharp#features
Формат файла настроек тут: https://github.com/allure-framework/allure-csharp/blob/master/Tests.SpecRun/allureConfig.json

**Comment by artbear** [comment]
Выполнено в #556
