### ISSUE TITLE
Ошибка при формировании скриншота

### ISSUE THREAD

**Issue by StupnikovVG** [silverbulleters/add#562]
**Описание ошибки**
При установленном флаге "Формировать скриншот при ошибке" если в процессе выполнения сценариев в одном из них происходит ошибка, выполнение падает с ошибкой копирования файлов. 
Ошибка выходит в процедуре "ОтчетАллюр": процедура выполняется на клиенте, при этом в ней вызывается функция "ПутьФайлаПоДвоичнымДаннымСервер", создающая файл на сервере и далее процедурой "КопироватьФайлКомандаСистемы" производится попытка на клиенте скопировать файл, созданный на сервере. Естественно, файл для копирования не находится и тестирование падает с ошибкой.

Возможный вариант решения:
Сразу сохранять двоичные данные скриншота в нужный файл, не тратя время на генерацию временного файла и его копирование.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Необходима клиент-серверная установка 1С. При этом запуск тестов должен происходить на машине, отличной от сервера
2. Сгенерировать сценарий, который заведомо будет падать с ошибкой
3. Настроить формирование скриншотов при ошибке
4. Запустить сценарий, убедиться, что выйдет ошибка копирования файлов

**Ожидаемое поведение, если бы ошибки не было**
Скриншот формируется без ошибки и отражается в отчете Аллюр.

**Скриншоты**
Скрин ошибки:
![image](https://user-images.githubusercontent.com/27226655/65326227-a4b0e580-dbb9-11e9-9c1e-7cbd3fb7c2e8.png)

Код, вызывающий ошибку:
![image](https://user-images.githubusercontent.com/27226655/65326322-d9bd3800-dbb9-11e9-8915-5d1f235922de.png)

**Окружение:**

 - Версия операционной системы: `Windows Server 2016`
 - Редакция платформы 1С: `8.3.12.1595`
 - Версия `Vanessa.ADD` 6.2.0

**Comment by artbear** [comment]
Выполнено в #566
