### ISSUE TITLE
Не передается служебный параметр "НастройкиОтчета" при выполнении тестов на открытие форм конфигурации

### ISSUE THREAD

**Issue by AndreyGubin** [silverbulleters/add#572]
**Описание ошибки**
Часть тестов падает с ошибкой Не передан служебный параметр "НастройкиОтчета"

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Скачать add из ветки develop
2. Собрать файл epf из исходников Тесты_ОткрытиеФормКонфигурации, версия от 1 октября 2019 года, 17:03 Московского времени
3. В командной строке выполнить: vrunner xunit C:\vanessa\openforms_beta2.epf --settings C:\vanessa\json\OpenForms.json --testclient Имя:Пароль:1538
4. По окончании процесса сгенерировать отчет Allure

В отчете будет около сотни упавших тестов с ошибкой:

```
{ОбщаяФорма.ФормаНастроекОтчета.Форма(27)}: Не передан служебный параметр "НастройкиОтчета".
		ВызватьИсключение НСтр("ru = 'Не передан служебный параметр ""НастройкиОтчета"".'");
```

**Ожидаемое поведение, если бы ошибки не было**
'Тест пройден успешно'

**Окружение:**

 - Версия операционной системы: [`Windows Server 2016`]
 - Редакция платформы 1С [`8.3.13.1513`]
 - Версия `OneScript` [`1.1.1`]

**Дополнительный контекст**

- Конфигурация нетиповая
- Режим от опасных действий выключен
- В файле xUnitParams.json - "ОткрываемФормыНаКлиентеТестирования":false
Если исправить на true, то сыпятся все тесты из-за модального окна. Окно появляется скорее всего из-за того, что список исключений обрабатывается некорректно.

**Comment by artbear** [comment]
@AndreyGubin Правильно я понял, что согласно твоему комментарию из https://github.com/silverbulleters/add/issues/585#issuecomment-539354492

ошибка не повторяется?

цитата:
>Все остальные работали без проблем. И еще - эта ошибка больше не воспроизводится

>{ОбщаяФорма.ФормаНастроекОтчета.Форма(27)}: Не передан служебный параметр "НастройкиОтчета".
		ВызватьИсключение НСтр("ru = 'Не передан служебный параметр ""НастройкиОтчета"".'

**Comment by AndreyGubin** [comment]
> Правильно я понял, что согласно твоему комментарию из [#585 (comment)](https://github.com/silverbulleters/add/issues/585#issuecomment-539354492)
> 
> ошибка не повторяется?

Ошибка не повторяется если взять обработку, которую предложил @ViktorErmakov этой ночью. Согласно его комментарию, он отключил часть кода, которая отвечала за вызов ФормыНастроек. На версии 6.3.0 ошибка повторяется.

**Comment by ViktorErmakov** [comment]
Артур, я просто закомментировал добавление форм настроек отчетов, т.к. эти формы вызываться должны с параметром служебным, ну и получается что смысла открывать форму настроек отчета БСП, не из отчета нет смысла. Код пока не удалял, жду общих рассуждений по этому поводу.

**Comment by 1cgh** [comment]
кмк всегда, когда у объекта метаданных стандартная форма - общая, то в дымовом она должна вызываться через имя стандартной формы объекта, а не через имя общей формы

**Comment by ViktorErmakov** [comment]
> 
> 
> кмк всегда, когда у объекта метаданных стандартная форма - общая, то в дымовом она должна вызываться через имя стандартной формы объекта, а не через имя общей формы

Анатолий, вообще не понял посыл Вашего сообщения. Как нам это может помочь в данный момент?

**Comment by ViktorErmakov** [comment]
@artbear скажи пожалуйста, а такие формы настроек с входящим параметром вообще нужно пытаться открыть? Мне кажется не нужно. Но такой код добавили в предыдущем коммите.

**Comment by artbear** [comment]
@AndreyGubin @ViktorErmakov я согласен с изменениями Виктора из #585

поэтому текущий ишуз закрываю - формы настроек не будут открываться.

**Comment by artbear** [comment]
@AndreyGubin если не согласен с "формы настроек не будут открываться", тогда пиши.

текущий ишуз я закрываю.
