### ISSUE TITLE
Дать человекопонятные названия дымовым тестам блокировки объектов и проверки наименований общих модулей

### ISSUE THREAD

**Issue by KrapivinAndrey** [silverbulleters/add#577]
**Существует проблема**
Впервые запустил дымовые на УФ. Формирую отчет Allure, так как очень к нему привык. Названия тестов совсем не отражают в чем проблема:
![image](https://user-images.githubusercontent.com/586025/66101851-c6529980-e5c9-11e9-8cba-80d40a1d07cc.png)

![image](https://user-images.githubusercontent.com/586025/66101888-e4b89500-e5c9-11e9-8d11-578d5a84efe7.png)

**Хотелось бы иметь следующую функциональность**
Корректное описание теста, понятное сообщение в asserts

**Comment by artbear** [comment]
@KrapivinAndrey вообще часто лучше просматривать через нормальную группировку (закладка Behavior)

- ![image](https://user-images.githubusercontent.com/2920817/66585107-f3d1b100-eb8e-11e9-96b0-a0688c365ff1.png)

еще можно смотреть через Packages, там одна группа - набор тестов

- ![image](https://user-images.githubusercontent.com/2920817/66585330-5034d080-eb8f-11e9-95f4-ef4c3c5311e4.png)


а не через сплошной список (закладка Suites), в котором как раз и неудобно смотреть группировку

- ![image](https://user-images.githubusercontent.com/2920817/66585370-5c209280-eb8f-11e9-89cb-0fdd4645691d.png)

**Comment by artbear** [comment]
Можно сделать вот так

- ![image](https://user-images.githubusercontent.com/2920817/66585919-68f1b600-eb90-11e9-8f74-d7468298f7da.png)

будет ли это наглядно?

**Comment by artbear** [comment]
выполнено.

- Добавлены человекочитаемые имена дымовым тестам #577
  - проверки командного интерфейса
  - проверки макетов СКД
  - проверки режима блокировки
  - проверки наименования общих модулей
  - проверки ролей
