### ISSUE TITLE
При выполнении дымовых тестов, не открываются отчеты с общими формами

### ISSUE THREAD

**Issue by ViktorErmakov** [silverbulleters/add#585]
Описание ошибки
При выполнении дымового теста "Открытие форм конфигурации" проверка отчетов, у которых нет своих форм, а они выбраны из Общих форм проваливается выполнение теста.
Например:

{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(1612)}: [Failed] Выявлено модальное окно:[Переход по кнопке командного интерфейса] Неизвестное имя формы. Имя: "e1cib/app/Отчет.ЖурналОперацийЭлектронныеПодписи.Форма"  ВызватьИсключение Префикс + " " + СообщениеОшибки;

Окружение:

    Редакция платформы 1С 8.3.14.1854
    Версия Vanessa.ADD 6.0.0
    Версия OneScript 1.1.1.44

Есть отчет бспшный (2.4.6) "АнализЖурналаРегистрации" у него указаны формы отчета, настроек общие, которые уже указаны в свойствах конфигурации.
изображение
В "ОткрытиеФормКонфигурации_УправляемаяФорма_Строка 513
содержится код
изображение
Это приводит к тому, что когда тестирование идет в клиенте тестирования используется метод
изображение
А для этого метода, добавленный текст ".Форма" и ".ФормаНастроек" лишние, навигационные ссылки этого не терпят, и не открывают окно.
А вот если бы тест выполнялся в менеджере тестирования, тогда для метода "ОткрытьФорму(..)" как раз этот текст и нужен.

По второй ошибке обратная ситуация:
Есть некоторый отчет, где формы не указаны, а наследуются из конфигурации
изображение
Тогда при загрузке форма добавиться вот таким образом
изображение
т.е. "Отчет.АнализЖурналаРегистрации_Мой" без указания формы.
Если тестирование будет через клиента тестирования, то никаких ошибок не будет и все пройдет успешно.
А вот если тестирование будет идти в менеджере тестирования, то метод
"ОткрытьФорму(...)" ругнется на открытие этой формы, и тест падает.

**Comment by ViktorErmakov** [comment]
Пришлось открыть новый ишуз, т.к. #520 не затестировали и отправили в релиз, ишузу закрыли.

**Comment by AndreyGubin** [comment]
Добрый день. К сожалению, не помогло. Вот несколько примеров:

```
{ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.Форма.УправляемаяФорма.Форма(670)}: Ошибка при вызове метода контекста (ОткрытьФорму)
		ТестируемаяФорма = ОткрытьФорму(ПолноеИмяФормы, ПараметрыФормы,, Новый УникальныйИдентификатор);
по причине:
Неизвестное имя формы. Имя: "Справочник.ах_ВидыТорговогоМеста"
```

Полностью код ошибки переписывать не буду, он одинаковый, пишу только последнюю строку:
Неизвестное имя формы. Имя: "Справочник.ах_НачислениеШтрафаПрисоединенныеФайлы"
Неизвестное имя формы. Имя: "Справочник.ах_Номенклатура"
Неизвестное имя формы. Имя: "Справочник.ах_СпециализацииРозничныхРынков"
Неизвестное имя формы. Имя: "Справочник.ГруппыИсполнителейЗадач"
Неизвестное имя формы. Имя: "Справочник.дт_ВидыМестоположения"
Неизвестное имя формы. Имя: "Справочник.дт_ДоговорыПрисоединенныеФайлы"
Неизвестное имя формы. Имя: "Справочник.хс_СтанцииМетрополитена"

**Comment by artbear** [comment]
@ViktorErmakov @AndreyGubin Коллеги, в версии 6.3.0 все же было исправлено согласно #532 

протестировано, проверены разные кейсы согласно этому ишузу.

@ViktorErmakov почему вдруг используешь версию 6.0.0 ??

проверь на 6.3.0

**Comment by ViktorErmakov** [comment]
> 
> 
> @ViktorErmakov @AndreyGubin Коллеги, в версии 6.3.0 все же было исправлено согласно #532
> 
> протестировано, проверены разные кейсы согласно этому ишузу.
> 
> @ViktorErmakov почему вдруг используешь версию 6.0.0 ??
> 
> проверь на 6.3.0

Артур, я скачал 6.3.0 (в описании текущего ишуза я не верно просто указал версию), повторюсь, протестировали хреново, не знаю кто и как тестировал и на каких кейсах, мой кейс по анализу остался не рабочим.

**Comment by ViktorErmakov** [comment]
> 
> 
> Добрый день. К сожалению, не помогло. Вот несколько примеров:
> 
> ```
> {ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.Форма.УправляемаяФорма.Форма(670)}: Ошибка при вызове метода контекста (ОткрытьФорму)
> 		ТестируемаяФорма = ОткрытьФорму(ПолноеИмяФормы, ПараметрыФормы,, Новый УникальныйИдентификатор);
> по причине:
> Неизвестное имя формы. Имя: "Справочник.ах_ВидыТорговогоМеста"
> ```
> 
> Полностью код ошибки переписывать не буду, он одинаковый, пишу только последнюю строку:
> Неизвестное имя формы. Имя: "Справочник.ах_НачислениеШтрафаПрисоединенныеФайлы"
> Неизвестное имя формы. Имя: "Справочник.ах_Номенклатура"
> Неизвестное имя формы. Имя: "Справочник.ах_СпециализацииРозничныхРынков"
> Неизвестное имя формы. Имя: "Справочник.ГруппыИсполнителейЗадач"
> Неизвестное имя формы. Имя: "Справочник.дт_ВидыМестоположения"
> Неизвестное имя формы. Имя: "Справочник.дт_ДоговорыПрисоединенныеФайлы"
> Неизвестное имя формы. Имя: "Справочник.хс_СтанцииМетрополитена"
> 
> Уточню - что на версии файла, которая попала в релиз, подобного поведения не наблюдалось, там были проблемы с тремя типами:
> Неизвестное имя формы. Имя: "Справочник.хс_ОграниченияПоРазмещению.Форма"
> Неизвестное имя формы. Имя: "Справочник.хс_ОграниченияПоРазмещению.ФормаВарианта"
> Неизвестное имя формы. Имя: "Справочник.хс_ОграниченияПоРазмещению.ФормаНастроек"
> 
> Все остальные работали без проблем. И еще - эта ошибка больше не воспроизводится
> 
> ```
> {ОбщаяФорма.ФормаНастроекОтчета.Форма(27)}: Не передан служебный параметр "НастройкиОтчета".
> 		ВызватьИсключение НСтр("ru = 'Не передан служебный параметр ""НастройкиОтчета"".'");
> ```

Понял, ты тестируешь в менеджере тестирования, посмотрю что я мог навредить.
Спасибо!

**Comment by ViktorErmakov** [comment]
> 
> 
> Добрый день. К сожалению, не помогло. Вот несколько примеров:
> 
> ```
> {ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.Форма.УправляемаяФорма.Форма(670)}: Ошибка при вызове метода контекста (ОткрытьФорму)
> 		ТестируемаяФорма = ОткрытьФорму(ПолноеИмяФормы, ПараметрыФормы,, Новый УникальныйИдентификатор);
> по причине:
> Неизвестное имя формы. Имя: "Справочник.ах_ВидыТорговогоМеста"
> ```
> 
> Полностью код ошибки переписывать не буду, он одинаковый, пишу только последнюю строку:
> Неизвестное имя формы. Имя: "Справочник.ах_НачислениеШтрафаПрисоединенныеФайлы"
> Неизвестное имя формы. Имя: "Справочник.ах_Номенклатура"
> Неизвестное имя формы. Имя: "Справочник.ах_СпециализацииРозничныхРынков"
> Неизвестное имя формы. Имя: "Справочник.ГруппыИсполнителейЗадач"
> Неизвестное имя формы. Имя: "Справочник.дт_ВидыМестоположения"
> Неизвестное имя формы. Имя: "Справочник.дт_ДоговорыПрисоединенныеФайлы"
> Неизвестное имя формы. Имя: "Справочник.хс_СтанцииМетрополитена"
> 
> Уточню - что на версии файла, которая попала в релиз, подобного поведения не наблюдалось, там были проблемы с тремя типами:
> Неизвестное имя формы. Имя: "Справочник.хс_ОграниченияПоРазмещению.Форма"
> Неизвестное имя формы. Имя: "Справочник.хс_ОграниченияПоРазмещению.ФормаВарианта"
> Неизвестное имя формы. Имя: "Справочник.хс_ОграниченияПоРазмещению.ФормаНастроек"
> 
> Все остальные работали без проблем. И еще - эта ошибка больше не воспроизводится
> 
> ```
> {ОбщаяФорма.ФормаНастроекОтчета.Форма(27)}: Не передан служебный параметр "НастройкиОтчета".
> 		ВызватьИсключение НСтр("ru = 'Не передан служебный параметр ""НастройкиОтчета"".'");
> ```

Андрей, я немного докопал сегодня. Я акцент делал только на отчетах когда изменения вносил и тестил. А у Вас получается ошибка со справочниками. До моих изменений почему не было ошибок, поясню, у Вас эти справочники вообще не попадали в проверку, и не открывались. Посмотрите пожалуйста список справочников на форме ADD той версии, есть ли там объекты указанные выше в комментарии, такие как: "Справочник.ах_Номенклатура"?

**Comment by ViktorErmakov** [comment]
И посмотри сегодняшние изменения, возможно сейчас ошибок не будет, но нужно понимать мне как было у тебя до этого.

**Comment by AndreyGubin** [comment]
> Понял, ты тестируешь в менеджере тестирования, посмотрю что я мог навредить.

К сожалению, я не могу открыть через клиента тестирования. https://github.com/silverbulleters/add/issues/573

**Comment by AndreyGubin** [comment]
> есть ли там объекты указанные выше в комментарии, такие как: "Справочник.ах_Номенклатура"? Какие виды форм для него есть?

Открыл конфигуратор, там есть
Справочник.ах_Номенклатура - ФормаСписка
Справочник.ах_СпециализацииРозничныхРынков - владка формы пустая
Справочник.ГруппыИсполнителейЗадач - владка формы пустая
Справочник.дт_ВидыМестоположения - ФормаЭлемента, ФормаВыбора
Справочник.дт_ДоговорыПрисоединенныеФайлы - владка формы пустая
Справочник.хс_СтанцииМетрополитена - ФормаВыбора
Справочник.ах_НачислениеШтрафаПрисоединенныеФайлы - владка формы пустая

Из отчета ADD 6.3.0
1) Справочник.ах_Номенклатура:
Заголовок теста:
Списки : Справочник.ах_Номенклатура.Форма.ФормаСписка - пройден успешно
2) Справочник.ах_СпециализацииРозничныхРынков - отсутствует
3) Справочник.ГруппыИсполнителейЗадач - отсутствует
4) Справочник.дт_ВидыМестоположения:
Заголовки тестов:
Новые : Справочник.дт_ВидыМестоположения.Форма.ФормаЭлемента
Существующие : Справочник.дт_ВидыМестоположения.Форма.ФормаЭлемента
Пройдены успешно
5) Справочник.дт_ДоговорыПрисоединенныеФайлы - отсутствует
6) Справочник.хс_СтанцииМетрополитена:
Заголовок теста:
Списки : Справочник.хс_СтанцииМетрополитена.Форма.ФормаВыбора - пройден успешно
7) Справочник.ах_НачислениеШтрафаПрисоединенныеФайлы - отсутствует

То есть получается, что в данный момент на 6.3.0 в тесты не попадают элементы, у которых нет формы

**Comment by AndreyGubin** [comment]
Проверил этот файл - https://github.com/ViktorErmakov/add/commit/6305038c2bad5001671f0faf244bfe365778f94c

Пройдено - 1330 тест кейсов, из них 19 - product defects (красные) и 4 test defects (желтые). Считаю, что всё получилось, в прошлый раз было от 300 до 600 красных ошибок.

**Comment by artbear** [comment]
@ViktorErmakov ты проверял на конфигурации xddNoSync от Ванесса-АДД?

в прошлом нашем исправлении там специально добавлены все варианты форм отчетов - свои формы, выбраны общие формы отчетов, не выбраны формы отчетов

тестировали и в режиме тест-клиента, и на менеджере тестирования.
ошибок не было.

проверь, пожалуйста, на этой конфигурации.

**Comment by ViktorErmakov** [comment]
@artbear привет! Я проверяю на своей конфигурации. xddNoSync - как ее получить?

**Comment by ViktorErmakov** [comment]
> 300 до 600

Такое количество ошибок было в версии 6.3.0?
А сейчас 19 красных, и 4 желтые, это с чем связано?

Да, если у справочников например формы не указаны, а строятся автоматически платформой, то их и проверять получается не нужно, поэтому они в ADD не попадают. Спасибо за ответ.

**Comment by ViktorErmakov** [comment]
> тестировали и в режиме тест-клиента, и на менеджере тестирования.
> ошибок не было.
> 
> проверь, пожалуйста, на этой конфигурации.

@artbear может я конечно что то не понимаю, но давай Артур и ты протести на указанной конфигурации версию релиза 6.3.0
Я загрузил конфигурацию из файлов, скачал версию 6.3.0
Запустил тесты пот отчетам, и вот что получил

![изображение](https://user-images.githubusercontent.com/39617680/66512515-cbd84400-eae1-11e9-9a86-1efd9821fa94.png)

**Comment by AndreyGubin** [comment]
> Такое количество ошибок было в версии 6.3.0?
> А сейчас 19 красных, и 4 желтые, это с чем связано?

Оставшиеся ошибки это проблема именно в нашей конфигурации:
- создание документа производится на основании другого документа
- недостаточно прав на создание документа (да, у нас есть баг с невозможностью открытия одного раздела под админом, а для открытия надо в конфигураторе выставить пользователю определенные права)
- таблица не найдена
и подобные.

Почему число ошибок снизилось с 600 до 14:
- пропали ошибки о которых я писал в https://github.com/silverbulleters/add/issues/572
- пропали ошибки "неизвестное имя формы"

**Comment by artbear** [comment]
>протести на указанной конфигурации версию релиза 6.3.0
Я загрузил конфигурацию из файлов, скачал версию 6.3.0
Запустил тесты пот отчетам, и вот что получил

@ViktorErmakov проверю сегодня

**Comment by artbear** [comment]
@ViktorErmakov я смотрю твой коммент https://github.com/silverbulleters/add/issues/585#issuecomment-540146815

на картинке видно, что конфигурация у тебя версии 6.2.0 (
на версии 6.3.0 (в которой 25 форм отчетов) ошибок нет 
- при запуске в режиме клиент тестирования
- и при запуске без него 

вот скриншот 
![image](https://user-images.githubusercontent.com/2920817/66565124-5b293a00-eb6a-11e9-9972-ca8973d2fa8d.png)

**Comment by artbear** [comment]
вот расшифровка форм отчетов 
![image](https://user-images.githubusercontent.com/2920817/66565177-84e26100-eb6a-11e9-8dc6-e6f3fc1e75ff.png)

**Comment by artbear** [comment]
@ViktorErmakov Проверил на БСП 3.Х и 8.3.15
я подтверждаю падения, аналогичные https://github.com/silverbulleters/add/issues/585#issuecomment-540146815 

значит, в прошлый раз мы недопроверили (

уже легче.

сейчас проверю твой исправляющий ПР - если на БСП все будет хорошо, приму.

**Comment by artbear** [comment]
Внедрено в проект. В #589

**Comment by ViktorErmakov** [comment]
@artbear с моими исправлениями у меня начали добавляться формы бизнесс процессов в список форм. У тебя это же повторилось? Я с этим еще не разбирался.
