### ISSUE TITLE
ОФ: xddTestRunner не заполнено значение реквизита ОбработкаОбъект

### ISSUE THREAD

**Issue by sfaqer** [silverbulleters/add#592]
**Описание ошибки**
xddTestRunner не заполнено значение реквизита ОбработкаОбъект

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. opm u add
2. открыть xddTestRunner в конфигураторе
4. Открыть форму "Форма", ошибка на вкладке реквизиты

**Ожидаемое поведение, если бы ошибки не было**
Реквизит ОбработкаОбъект был бы заполнен

**Скриншоты**
![image](https://user-images.githubusercontent.com/32082417/66728629-5fff2e00-ee89-11e9-9d1f-5d5a7ff856f5.png)

**Окружение:**

 - Версия операционной системы:`Windows 10 (64)`]
 - Редакция платформы 1С 8.3.14
 - Версия `Vanessa.ADD` 6.4.0
 - Версия `OneScript` 1.0.21

**Comment by artbear** [comment]
@sfaqer опять беда со сборкой обычной формы (

проверим, исправим.

Есть обход: вручную поставить тип этого реквизита на "ВнешняяОбработка.xddTestRunner" в форме внешней обработки и сохранить файл.
И проблема (локально) уйдет.

**Comment by sfaqer** [comment]
@artbear Да, про обход знаю. Ишузу завёл чтобы зафиксировать баг в релизе. Спасибо!

**Comment by artbear** [comment]
исправлено
