### ISSUE TITLE
Названия дымовых тестов по открытию форм на основании

### ISSUE THREAD

**Issue by ovcharenko-di** [silverbulleters/add#598]
**Описание ошибки**
Каждый новый запуск тестов генерирует отдельную запись в Allure, потому что в названии указывается номер и дата документа

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Запустить дымовые тесты по открытию форм на основании
2. Сгенерировать отчет Allure
3. Повторно запустить дымовые тесты по открытию форм на основании
4. Сгенерировать отчет Allure
5. Убедиться, что в списке тестов есть по две записи на каждый ввод на основании

**Ожидаемое поведение, если бы ошибки не было**
Записей в отчете должно быть столько же, сколько вариантов ввода на основании проверялось, вне зависимости от количества запусков.

**Скриншоты**
![image](https://user-images.githubusercontent.com/24920942/67392463-3c369900-f5a9-11e9-9d01-4046ca8d42d7.png)

**Окружение:**
 - Версия `Vanessa.ADD` [например, `6.4.0`]

**Comment by ovcharenko-di** [comment]
Забрал себе

**Comment by artbear** [comment]
выполнено в https://github.com/silverbulleters/add/pull/599
