### ISSUE TITLE
При первом запуске тесты не выполняются

### ISSUE THREAD

**Issue by PashaMak** [silverbulleters/add#602]
**Описание ошибки**
При первом запуске заполняется дерево тестов, но тесты не выполняются при синхронном режиме.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть очистить кэш известных шагов и перевести конфигурацию в синхронный режим
2. Загрузить и выполнить тесты через командную строку
3. Тесты загрузятся но не выполнятся, при этом тесты посчитаются выполненными и не будет алюра.

**Ожидаемое поведение, если бы ошибки не было**
Тесты должны начать прогоняться.

**Скриншоты**
![Все сценарии выполнены](https://user-images.githubusercontent.com/24808007/67842208-541f9700-fb2c-11e9-9ced-57e51ba57080.png)
![Поиск сценариев по известным шагам для их выполнения 2](https://user-images.githubusercontent.com/24808007/67842209-541f9700-fb2c-11e9-8c57-f5bf0d4d1861.png)
![Поиск сценариев по известным шагам для их выполнения](https://user-images.githubusercontent.com/24808007/67842210-541f9700-fb2c-11e9-87f8-b54a1e062ec6.png)
![Асинхронынй метод в синхронном режиме](https://user-images.githubusercontent.com/24808007/67842211-54b82d80-fb2c-11e9-96c5-dbef944cc610.png)

**Окружение:**

 - Версия операционной системы: Windows 10 (64)
 - Редакция платформы 1С 8.3.12
 - Версия `Vanessa.ADD` 6.4.0
 - Версия `OneScript` 1.0.21

**Дополнительный контекст**

Проверил на версиях 6.0-6.4 ошибка воспроизводится.
По отладчику видно что метод НачатьПеремещениеФайлов выполняется и управление передается на построение сценариев по известным шагам, после этого управление передается на перемещение, в процессе которого и заполняются эти шаги. При переводе в асинхронный режим работает. 
Синхронность режима определяется настройкой конфигурации, которая не переносится на новые базы в EDT. Зачем синхронность расширений и внешних компонент связывать с синхронностью тестов? Может стоит вынести настройки асинхронного режима отдельно в файл настроек?

**Comment by artbear** [comment]
@PashaMak Спасибо за анализ, проверю.

**Comment by artbear** [comment]
@PashaMak исправление планируем в первую очередь. должно быть в релизе 6.5.0 на этой неделе

**Comment by PashaMak** [comment]
Что насчет выноса настройки асинхронного режима в настройки?

**Comment by artbear** [comment]
@PashaMak не удалось полностью повторить твою проблему, она воспроизвелась у меня всего один раз за множество попыток.

но удалось повторить и исправить очень похожую проблему с отсутствием шагов фич при сбросе кеша.

я сделал исправление.

проверил его на куче вариантов и платформ в разных режимах синхронности.

все работает.

Могу выложить дев-сборку, чтобы ты смог потестировать.

потестишь?

PS "насчет выноса настройки асинхронного режима в настройки" - думаю

**Comment by artbear** [comment]
@PashaMak заодно в этой сборке я сделал возможность сброса кеша через настройки, а не только интерактивно.

теперь можно сбросить гарантированно сбросить кеш перед запуском фичи в начале работы Ванессы.

чтобы ручками не сбрасывать каждый раз )

**Comment by PashaMak** [comment]
> потестишь?

Уже нет.
Пока решили проблему переводом в асинхронный режим.

**Comment by artbear** [comment]
@PashaMak А можешь мне свою конфигурацию на тест выдать?
только мне для тестов, NDA соблюдем )

**Comment by PashaMak** [comment]
Контур у нас создается автоматически, поэтому при каждом запуске все окружение чистое.
Конфу для тестов отправил на почту.

**Comment by artbear** [comment]
@PashaMak можешь в облако куда-нибудь положить, дать мне ссылку через мою почту, я скачаю, потом удалить сразу можно из облако

**Comment by StupnikovVG** [comment]
@artbear удалось в итоге воспроизвести и понять, как исправить?

**Comment by VladFrost** [comment]
@artbear у меня, кстати, в 6.5.0 тоже не запускается прогон в пакетном режиме.
Воспроизведение такое:
1. удалить все папки сборочной линии
2. развернуть тестовую базу из .dt
3. выполнить команду `vrunner vanessa --vanessasettings VBParams.json`

Результат:
Сразу после заполнения кэша выполнение сценариев не начинается, 1С:Предприятие закрывается.

Тесты начинают прогоняться только после повторного запуска.

VBParams.json:
```
{
    "$schema":"https://raw.githubusercontent.com/silverbulleters/vanessa-runner/develop/behavior-schema.json",
    "ИмяСборки": "SBM",
    "ВерсияПлатформы": "8.3.15",
    "ВыводитьСообщенияВФайл": "$workspaceRoot/build/message.txt",
    "ПутьКVanessaBehavior": "$workspaceRoot/bddRunner.epf",
    "КаталогФич": "$workspaceRoot/features/",
    "КаталогиБиблиотек": [
        "$instrumentsRoot/features/libraries/",
        "$workspaceRoot/features/libraries/"
    ],
    "ВыполнитьСценарии": "Истина",
    "ЗавершитьРаботуСистемы": "Истина",
    "ЗакрытьTestClientПослеЗапускаСценариев": "Истина",
    "ДелатьЛогВыполненияСценариевВЖР": "Истина",
    "ДелатьОтчетВФорматеАллюр": "Истина",
    "ДелатьОтчетВФорматеjUnit": "Истина",
    "ДелатьОтчетВФорматеCucumberJson": "Истина",
    "ДелатьЛогВыполненияСценариевВТекстовыйФайл": "Истина",
    "КаталогOutputAllureБазовый": "$workspaceRoot/allure-results",
    "КаталогOutputjUnit": "$workspaceRoot/junitreport",
    "КаталогOutputCucumberJson": "$workspaceRoot/cucumber",
    "СоздаватьПодкаталогВКаталогеAllureДляЭтойСборки": "Ложь",
    "ДелатьСкриншотПриВозникновенииОшибки": "Истина",
    "КаталогOutputСкриншоты": "$workspaceRoot/allure-results/",
    "ИмяФайлаЛогВыполненияСценариев": "$workspaceRoot/build/vanessaonline.txt",
    "КомандаСделатьСкриншот": "\"C:\\Program Files\\IrfanView\\i_view64.exe\" /capture=1 /convert=",
    "СписокТеговИсключение": [
        "IgnoreOnCIMainBuild",
        "IgnoreOn8310",
        "IgnoreOnUFBuilds",
        "Ignore",
        "IgnoreIfNotIrfanView",
        "NotOnSRC",
        "IgnoreOnLinux",
        "Video",
        "Email",
        "EmptyIB",
        "RLS"
    ],
    "СписокТеговОтбор": [],
    "ТаймаутЗапуска1С": "100"
}
```

**Comment by artbear** [comment]
@VladFrost @StupnikovVG @PashaMak Коллеги в https://github.com/silverbulleters/add/issues/674#issuecomment-593055356 подтвердили, что исходная проблема решена.

проверьте готовый бинарник c bddRunner.epf из https://github.com/silverbulleters/add/issues/674#issuecomment-592972125

жду.

**Comment by artbear** [comment]
я выполнил условия из шапки, у меня на последних исправлениях все штатно выполняется и выдаются результаты

![image](https://user-images.githubusercontent.com/2920817/75669124-846a7400-5c8b-11ea-9e9b-b7d90a58020a.png)

@VladFrost @StupnikovVG @PashaMak

**Comment by VladFrost** [comment]
Проверил: с новым бинарником тестирование запускается с первого раза.

**Comment by artbear** [comment]
@VladFrost Большое спасибо!

Отлично, значит, проблема решена окончательно!

**Comment by PashaMak** [comment]
Проверил, сборка пошла.

> @VladFrost @StupnikovVG @PashaMak Коллеги в [#674 (comment)](https://github.com/silverbulleters/add/issues/674#issuecomment-593055356) подтвердили, что исходная проблема решена.
> 
> проверьте готовый бинарник c bddRunner.epf из [#674 (comment)](https://github.com/silverbulleters/add/issues/674#issuecomment-592972125)
> 
> жду.

Проверил, тесты отработали, аллюр соформировался.

**Comment by StupnikovVG** [comment]
В связи со сменой работы временно не могу проверить. Но уважаемому сообществу разработчиков верю на слово ))
> 
> 
> @VladFrost @StupnikovVG @PashaMak Коллеги в [#674 (comment)](https://github.com/silverbulleters/add/issues/674#issuecomment-593055356) подтвердили, что исходная проблема решена.
> 
> проверьте готовый бинарник c bddRunner.epf из [#674 (comment)](https://github.com/silverbulleters/add/issues/674#issuecomment-592972125)
> 
> жду.
