### ISSUE TITLE
Шаг для проверки модифицированности текущей формы

### ISSUE THREAD

**Issue by yadimetrio** [silverbulleters/add#607]
**Существует проблема**
Не нашел шага для проверки модифицированности текущей формы в тест клиенте `ТекущаяФорма.ТекущаяМодифицированность()`

**Хотелось бы иметь следующую функциональность**
Когда в поле "Наименование" я ввожу "Новое наименование"
Тогда текущая форма модифицированна
Когда я нажимаю на кнопку "Записать"
Тогда текущая форма не модифицирована

**Comment by artbear** [comment]
Выполнено в https://github.com/silverbulleters/add/pull/608

@yadimetrio Большое спасибо, сам нашел и сам исправил! люблю такое )
