### ISSUE TITLE
Перестал работать шаг "Когда я выполняю шаг с параметром 0"

### ISSUE THREAD

**Issue by yadimetrio** [silverbulleters/add#615]
**Описание ошибки**
Не правильно определяется тип числового параметра, когда значение параметра равно нулю. Он определяется как "Строка"

**Сценарий воспроизведения**
Когда я выполняю шаг с параметром 0

Этот шаг на сборке из master у меня падает, т.к. методу передается "0", вместо 0

https://github.com/silverbulleters/add/blob/master/epf/bddRunner/bddRunner/Forms/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl

Проблема в условии Лев(Значение, 1) = "0" должно быть как то так:
 Лев(Значение, 1) = "0" И СтрДлина(Значение) > 1 

```&НаКлиенте
Функция ПолучитьЗначениеДляПередачиВМетод(Знач Значение, Знач Тип)
	Если Тип = "Строка" Тогда
		РезЗначение = ВычислитьПеременныеКонтекстаВнутриСтроки(Значение);
		РезЗначение = СобратьСтрокуДляПередачиВКод(РезЗначение);
		Возврат """" + СтрЗаменить(РезЗначение, """", """""") + """";
	ИначеЕсли Тип = "Число" Тогда
		Если Лев(Значение, 1) = "0" Тогда // TODO заменить в парсере фич - строки 0001 должны определяться как тип "Строка", а не как тип "Число"
			Возврат """" + Значение + """";
		КонецЕсли;
		Возврат Значение;
	ИначеЕсли Тип = "Дата" Тогда
		Возврат ПреобразоватьКДатеСтроку(Значение);
	КонецЕсли;

	ТекстСообщения = "Неизвестный Тип: %1 в ПолучитьЗначениеДляПередачиВМетод";
	ТекстСообщения = СтрЗаменить(ТекстСообщения,"%1",Тип);
	ВызватьИсключение ТекстСообщения;
КонецФункции
```

**Comment by artbear** [comment]
Исправлено в #620 

@yadimetrio Большущее спасибо!
