### ISSUE TITLE
Проверить/исправить падающие ошибки для bdd

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#63]
Например, http://ci.silverbulleters.org/view/all/job/ADD%20test/job/feature%252Fci/51/allure/#

![image](https://user-images.githubusercontent.com/2920817/35557374-056b47fc-05b6-11e8-91a5-955021b4eb72.png)

+ 25 падений

**Comment by pumbaEO** [comment]
вроде как ошибок нет.
