### ISSUE TITLE
BDDrunner ошибка подстановки параметра типа Число из конфигурационного файла

### ISSUE THREAD

**Issue by StupnikovVG** [silverbulleters/add#637]
**Описание ошибки**
В конфигурационном json-файле указываю параметр "ТаймаутЗапуска1С" отличный от стандартного. При запуске из командной строки значение параметра не подставляется в bddrunner.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. В конфигурационном json-файле указать параметр "ТаймаутЗапуска1С" отличный от 25.
2. Запустить выполнение тестов из командной строки с указанием конфигурационного файла из п. 1 
3. Убедиться, что значение параметра "ТаймаутЗапуска1С" в открывшейся обработке не совпадает со значением из файла настроек.

**Ожидаемое поведение, если бы ошибки не было**
Параметр "ТаймаутЗапуска1С" загружается из конфигурационного файла.

**Скриншоты**
![изображение](https://user-images.githubusercontent.com/27226655/71479435-73256700-2805-11ea-95c5-ba5478694cdf.png)

**Окружение:**

 - Версия операционной системы: `Windows Server 2016 (64)`
 - Редакция платформы 1С `8.3.12.1595`
 - Версия `Vanessa.ADD` `6.5.0`
 - Версия `OneScript` 1.1.1.43

**Дополнительный контекст**

Ошибка в плагине загрузки настроек LoadSettings. Функция, подставляющая параметры из файла настроек, не обрабатывает значения типа Число:
![изображение](https://user-images.githubusercontent.com/27226655/71479786-09a65800-2807-11ea-83a4-658324c6513b.png)

**Comment by artbear** [comment]
выполнено в https://github.com/silverbulleters/add/pull/638
