### ISSUE TITLE
в описании плагина УтвержденияПроверкаТаблиц неточность

### ISSUE THREAD

**Issue by sulfur17** [silverbulleters/add#650]
На странице add\doc\xdd\Проверка-таблиц-и-табличных-документов.MD написано что в методы передаются Таб1 и Таб2. Но если в дальнейшем плагин выдаст сообщение о разном количестве колонок таблиц, то будет не понятно какая из этих таб Результат, а какая Эталон.

**Comment by artbear** [comment]
уже исправлено.
