### ISSUE TITLE
Собрать техническую информацию для issues

### ISSUE THREAD

**Issue by KrapivinAndrey** [silverbulleters/add#653]
**Существует проблема**
Автоматизировать сбор необходимой информации для решения проблемы.

**Хотелось бы иметь следующую функциональность**
Для того, чтобы зарегистрировать issue надо указывать тех. информацию: версию add, платформа, конфигурация и т.д. И это правильно, но занимает много времени. Предлагаю добавить кнопку - собрать техническую информацию и копировать ее при необходимости

![image](https://user-images.githubusercontent.com/586025/73069048-8a23ab80-3ece-11ea-8862-053ef6f37e1f.png)

![image](https://user-images.githubusercontent.com/586025/73069218-fdc5b880-3ece-11ea-8d47-8c50d9a77c63.png)

**Comment by artbear** [comment]
@KrapivinAndrey отличное предложение. нужно сделать, да

**Comment by artbear** [comment]
Выполнено в #712 

По сравнению с исходным скриншотом значительно расширен список получаемых полей.

@KrapivinAndrey Один минус - я не реализовал кнопку Копировать.
Не знаю универсального решения для Вин и Лин, которое будет работать для минимальной 8.3
Если кто-то знает, как сделать кнопку копирования в буфер обмена, напишите, плиз.

**Comment by KrapivinAndrey** [comment]
Знаю только для Win через COM

**Comment by KrapivinAndrey** [comment]
Можно вот попробовать

https://www.vdgb.ru/kompaniya/tehpodderzhka-1s/faq/rabota-s-buferom-obmena-sredstvami-1s/
