### ISSUE TITLE
Шаг "И открылось окно предупреждения" не работает с катомным заголовком

### ISSUE THREAD

**Issue by KrapivinAndrey** [silverbulleters/add#654]
**Описание ошибки**
Захардкодено, что заголовок модального окна должен быть 1С: Предприятие или 1C:Enterprise. Но у меня кастомный заголовок(ПоказатьПредупреждение(, "Айайай", 30, "МойЗаголовок))

Вообще, любой шаг работающий с окнами Вопрос/Предупреждение не сработает

**Ожидаемое поведение, если бы ошибки не было**
Шаг корректно отработает и проверить содержимое окна

**Окружение:**

 - Версия `Vanessa.ADD`: `6.5.0` 

**Дополнительный контекст**
У меня почти готовы дополнительные шаги. Протестирую и пришлю PR. Зафиксировал чтобы не забыть.

**Comment by artbear** [comment]
@KrapivinAndrey жду. интересно, как решаешь этот вопрос.

**Comment by artbear** [comment]
@KrapivinAndrey я сегодня правил этот шаг в https://github.com/silverbulleters/add/pull/704

и упс - я не обратил внимание на хард-код )

**Comment by artbear** [comment]
@KrapivinAndrey  и твой ПР я так и не вижу )

**Comment by artbear** [comment]
Выполнено.

**Comment by artbear** [comment]
@KrapivinAndrey Обрати внимание, в https://github.com/silverbulleters/add/pull/704 я улучшил поведение этого шага

**Comment by KrapivinAndrey** [comment]
> @KrapivinAndrey Обрати внимание, в #704 я улучшил поведение этого шага

@artbear Кажется наоборот все сломается. У тебя сейчас захардкожено Заголовок - 1с Предприятие и текст предупреждения Текст предупреждения
