### ISSUE TITLE
Настройки теста SmokeCommonModules недоступны на сервере приложений

### ISSUE THREAD

**Issue by SidnevAV** [silverbulleters/add#656]
**Описание ошибки**
При запуске смок тестов в управляемом приложении, настройки теста `SmokeCommonModules` недоступны на сервере приложений. У сервера нет доступа к локальному каталогу клиента.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Запустить в тонком клиенте `xddTestRunner` не на сервере приложений.
2. Загрузить настройки `xUnitParams.json` из файла
3. Загрузить тест `Tests_SmokeCommonModules.epf`

**Ожидаемое поведение, если бы ошибки не было**
Настройки теста `SmokeCommonModules` загружаются на сервере 1С.

**Окружение:**

 - Версия операционной системы: `Windows Server 2016`
 - Редакция платформы 1С: `8.3.12.1595`
 - Версия `Vanessa.ADD`: `6.5.0`

**Дополнительный контекст**

- Типовая конфигурация ДО, редакция 2.1 (2.1.11.5).
- Режим защиты от опасных действий выключен.

**Comment by artbear** [comment]
Выполнено в https://github.com/silverbulleters/add/pull/657

Очередные спасибо уходят в сторону @SidnevAV
