### ISSUE TITLE
ДанныеАллюрМеток не выводятся в отчет Allure

### ISSUE THREAD

**Issue by SidnevAV** [silverbulleters/add#663]
**Описание ошибки**
При пакетном запуске BDDrunner, данные аллюр меток не выводятся в отчет.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Прописать ДанныеАллюрМеток в VBParams.json
2. Прописать теги severity в тестах
3. Запустить сценарные тесты через vrunner
4. В отчете Allure все тесты с важностью normal

**Ожидаемое поведение, если бы ошибки не было**
В отчете тесты распределены по важности в соответствие с заданными тегами

**Окружение:**

 - Версия операционной системы: `Windows Server 2016`
 - Редакция платформы 1С: `8.3.12.1595`
 - Версия `Vanessa.ADD`: `6.5.0`
 - Версия `OneScript`: `1.1.1.42`

**Дополнительный контекст**

- Типовая конфигурация ДО, редакция 2.1 (2.1.11.5).
- Режим защиты от опасных действий выключен.

**Comment by artbear** [comment]
@SidnevAV молодец! сам встретил проблему, зафиксировал и сам исправил.

Идеальное поведение )

**Comment by artbear** [comment]
Выполнено в #664
