### ISSUE TITLE
Тесты_ОткрытиеФормКонфигурации в форме элемента открывается группа, а не элемент

### ISSUE THREAD

**Issue by SidnevAV** [silverbulleters/add#666]
**Описание ошибки**
В тесте открытия формы элемента иерархического справочника открывается группа, а не элемент справочника.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1.  Добавить новый иерархический справочник.
2. Формы группы не создавать.
3. В клиенте создать сначала группу, потом элемент справочника.
4. Запустить тест открытия формы элемента для этого справочника.

**Ожидаемое поведение, если бы ошибки не было**
Тест открывает в форме элемента элемент справочника, а не группу.

**Окружение:**

 - Версия операционной системы: `Windows Server 2016`
 - Редакция платформы 1С: `8.3.12.1595`
 - Версия `Vanessa.ADD`: `6.5.0`

**Дополнительный контекст**

- Типовая конфигурация ДО, редакция 2.1 (2.1.11.5).
- Режим защиты от опасных действий выключен.

**Comment by artbear** [comment]
@SidnevAV Отлично! Большое спасибо!

Сам нашел проблему и сам исправил!

и ишуз с номером 666 быстро закрыли )
