### ISSUE TITLE
Шаг 'И я нажимаю на кнопку с именем "ФормаНастройкаСписка"' в сценарии 'И Я очищаю фильтр на форме списка' падает в типовых формах

### ISSUE THREAD

**Issue by SidnevAV** [silverbulleters/add#671]
**Описание ошибки**
Шаг 'И я нажимаю на кнопку с именем "ФормаНастройкаСписка"' падает в типовых формах ДО.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Сделать простой тест с установкой и очисткой фильтра динамического списка в справочнике "Внутренние документы".
2. Запустить сценарный тест в базе ДО 2.1.11.5.
3. Шаг 'И я нажимаю на кнопку с именем "ФормаНастройкаСписка"' упадет с ошибкой.

**Ожидаемое поведение, если бы ошибки не было**
Шаг 'И я нажимаю на кнопку с именем "ФормаНастройкаСписка"' отрабатывает корректно.

**Окружение:**

 - Версия операционной системы: `Windows Server 2016`
 - Редакция платформы 1С: `8.3.12.1595`
 - Версия `Vanessa.ADD`: `6.5.0`

**Дополнительный контекст**

- Типовая конфигурация ДО, редакция 2.1 (2.1.11.5).
- Режим защиты от опасных действий выключен.

**Comment by artbear** [comment]
выполнено в https://github.com/silverbulleters/add/pull/672
