### ISSUE TITLE
Сначала выполняются сценарии а потом загружаются фичи

### ISSUE THREAD

**Issue by KrapivinAndrey** [silverbulleters/add#674]
Дмитрий Коротовских, [17.02.20 17:12]
Привет ребят, я тут такую особенность обнаружил:
1. Запускаю add через vrunner
2. Предполагается загрузка фич (см. ЗаполнитьДеревоФич) -> Выполнение сценария (см.ВыполнитьСценарии)
3. В "ЗаполнитьДеревоФич" происходит вызов НачатьПомещениеФайлов с оповещением "ОбработчикПодключенияШаговИзПереданныхФайловШагов"
4. В "ВыполнитьСценарии" происходит подключение обработчика ожидания "АсинхронноВыполнитьСценарий"
5. Ну и прикол в том, что 2а асинхронных обработчика в моем случае выполняются в не предполагаемом порядке, сначала управление перехватывает "АсинхронноВыполнитьСценарий", а потом "ОбработчикПодключенияШаговИзПереданныхФайловШагов"
6. Сначала выполняются фичи, а потом загружаются фичи, таким образом ничего не выполняется

add@6.4.0, 8.3.15.1656 - Серверный, БП 3.0

Может знаете, как обойти проблему без изменений в add? например закостылить ИнтервалВыполненияШага через параметры?

Дмитрий Коротовских, [17.02.20 17:23]
Ну и к слову, кажется что запуск из командной строки не может работать корректно когда НачатьПомещениеФайлов - не успевает выполниться до возврата клиенту управления

![image](https://user-images.githubusercontent.com/586025/74712850-1c5a6d80-5249-11ea-8c79-50c43e2d57ed.png)

@DmitriyKorotovskih - автор

**Comment by DmitriyKorotovskih** [comment]
Кажется, что проблема описанная здесь https://github.com/silverbulleters/add/issues/602 связана с текущей

**Comment by KrapivinAndrey** [comment]
![image](https://user-images.githubusercontent.com/586025/74827213-d24bb780-532e-11ea-82ae-e007b7a1e1f5.png)
 словил тоже самое на файловой УТ 11.4

**Comment by artbear** [comment]
@DmitriyKorotovskih @KrapivinAndrey ух ты, как интересно, проверю.

**Comment by artbear** [comment]
@DmitriyKorotovskih @KrapivinAndrey проверьте, плиз.

у меня проблем нет, тесты правильно отрабатывают.

**Comment by artbear** [comment]
Кстати, я тут одновременно правлю ванесса-раннер, чтобы выдача результатов тестирования, проверки поведения была более удобной и наглядной.

- https://github.com/silverbulleters/vanessa-runner/issues/339
- https://github.com/silverbulleters/vanessa-runner/pull/354

**Comment by artbear** [comment]
Для ускорения выкладываю готовый бинарник c bddRunner.epf

[bddRunner.zip](https://github.com/silverbulleters/add/files/4270636/bddRunner.zip)

**Comment by DmitriyKorotovskih** [comment]
> Для ускорения выкладываю готовый бинарник c bddRunner.epf
> [bddRunner.zip](https://github.com/silverbulleters/add/files/4270636/bddRunner.zip)
@artbear Спасибо, в переданной версии проблема с порядком операций не воспроизводится

**Comment by KrapivinAndrey** [comment]
@artbear У меня тоже порядок

**Comment by artbear** [comment]
@DmitriyKorotovskih @KrapivinAndrey ну и отлично.

закрываю.
