### ISSUE TITLE
Подключение тест-клиента с доменной авторизацией при запуске дымовых тестов

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#680]
**Существует проблема**
На проекте имплементации инженерных практик обучаемые запросили возможность доменной авторизации тест-клиента при запуске дымовых тестов

**Хотелось бы иметь следующую функциональность**
- Нужно передавать спец.ключ авторизации при запуске тест-клиента 1С, что-то типа `/WA+`

**Comment by artbear** [comment]
Связано с https://github.com/silverbulleters/add/issues/422

**Comment by SidnevAV** [comment]
@artbear Недавно правил плагин "ТестКлиенты" для удобства интерактивного запуска smoke тестов. По идее, должно помочь с этой issue.

**Comment by artbear** [comment]
Выполнено в https://github.com/silverbulleters/add/pull/685
