### ISSUE TITLE
Тест "Командный интерфейс" проверяет не все команды разделов

### ISSUE THREAD

**Issue by SidnevAV** [silverbulleters/add#695]
**Описание ошибки**
В список тестов попадают только команды из групп разделов (Сервис, Отчеты и т.д.) и из вложенных подсистем.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть тест "тесты_КомандныйИнтерфейс.epf".
2. В списке тестов нет основных команд из разделов.

**Ожидаемое поведение, если бы ошибки не было**
В список тестов попадают все команды из разделов.

**Скриншоты**
![image](https://user-images.githubusercontent.com/56798144/75911246-52f6d180-5e60-11ea-9297-6eadada85df8.png)

**Окружение:**

 - Версия операционной системы: `Windows Server 2016`
 - Редакция платформы 1С: `8.3.12.1595`
 - Версия `Vanessa.ADD`: `6.5.0`

**Дополнительный контекст**

- Типовая конфигурация ДО, редакция 2.1 (2.1.11.5).
- Режим защиты от опасных действий выключен.

**Comment by artbear** [comment]
Выполнено в #696 и #706

**Comment by artbear** [comment]
@SidnevAV молодец - сделал ишуз и сам же его выполнил!

больше бы таких !
