### ISSUE TITLE
Тест "ПроверкаМакетовСКД", проверка вложенных схем СКД

### ISSUE THREAD

**Issue by SidnevAV** [silverbulleters/add#697]
**Существует проблема**
Тест "ПроверкаМакетовСКД" не проверяет вложенные схемы СКД. Тест по основной схеме не падает, хотя во вложенной схеме есть ошибка.

**Хотелось бы иметь следующую функциональность**
Вариант 1: Проверять вложенные схемы в том же тесте.
Вариант 2: Выводить отдельные тесты для каждой вложенной схемы СКД.

**Comment by artbear** [comment]
Выполнено в #711
