### ISSUE TITLE
Использование макетов обработок при разработке на EDT

### ISSUE THREAD

**Issue by PashaMak** [silverbulleters/add#701]
**Существует проблема**
При разработке тестов в EDT они выносятся в отдельный внешний проект. Их бинарные файлы собираются в отличном от ожидаемого add места. 
Вместо структуры
```
- features /*каталог тестов*/
- ИмяОбработка.feature /*сценарий*/
- step_definitions
-  ИмяОбработка.epf /*шаги и макеты сценария*/
получается структура
- features /*каталог сценариев*/
- ИмяОбработка.feature
- step_definitions /*каталог данных для тестов*/
-   bin
-     ИмяОбработка.epf /*шаги и макеты сценария*/
```

В текущей версии add 6.5 невозможно подключить загрузку макетов для этих тестов.

**Хотелось бы иметь следующую функциональность**
Хочется вести разработку только на EDT без запуска конфигуратора. 
Не хранить в репозитории файлы обработок собираемые EDT из исходников.

**Дополнительный контекст**
Готовлю pr для реализации данного функционала.
Вижу следующую реализацию 
- добавить описание каталога внешних проектов edt
- с этого каталога подключать собранные обработки для вытягивания макетов
- для подтягивания шагов описанных в этих обработках подключать этот каталог в библиотеки

**Comment by artbear** [comment]
@PashaMak бдд-часть вроде бы должна подтягивать любые обработки, назодящиеся в любой глубине каталогов.или я ошибаюсь?

**Comment by PashaMak** [comment]
БДД подтягивает описание шагов, но не подтягивает макеты и другие данные хранящиеся в обработке

**Comment by PashaMak** [comment]
https://github.com/silverbulleters/add/pull/702

**Comment by artbear** [comment]
@PashaMak Ты супер-молодец. Сам создал ишуз, сам его и реализовал.

Обалденно! Люблю такое )

Большущее спасибо!

Выполнено в #702
