### ISSUE TITLE
Не закрывается тест клиент после ошибки авторизации

### ISSUE THREAD

**Issue by SidnevAV** [silverbulleters/add#708]
**Описание ошибки**
Если тест клиент не смог авторизоваться в базе, диалог ввода пароля так и будет висеть. Настройка "ЗакрытьTestClientПослеЗапускаСценариев" не спасает.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть 'Vanessa ADD'
2. Добавить один шаг 'Дано Я открыл сеанс TestClient от имени "Пользователь" с паролем "Пароль" или подключаю уже существующий'
3. Запустить сценарий
4. Окно авторизации так и будет висеть открытым

**Ожидаемое поведение, если бы ошибки не было**
Окно авторизации закрывается по таймауту

**Окружение:**

 - Версия операционной системы: `Windows Server 2016`
 - Редакция платформы 1С: `8.3.12.1595`
 - Версия `Vanessa.ADD`: `6.5.0`

**Дополнительный контекст**

- Типовая конфигурация ДО, редакция 2.1 (2.1.11.5).
- Режим защиты от опасных действий выключен.

**Comment by SidnevAV** [comment]
@artbear Если в одном сценарии не удалось авторизоваться тест клиенту, следующие сценарии с этим же тест клиентом тоже падают.

**Comment by artbear** [comment]
Выполнено в https://github.com/silverbulleters/add/pull/709
