### ISSUE TITLE
Дымовые тесты ломаются на банальных ошибках открытия форм 

### ISSUE THREAD

**Issue by Alexey-Zharkov** [silverbulleters/add#736]
**Описание ошибки**
При простых ошибках открытия форм дымовые тесты выдают статус "broken" вместо статуса "failed" и код тестовой обработки вместо, в котором обнаружена ошибка

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Выполняю дымовое тестирование на конфигурации 1С:ERP (доработанной) с использованием pipeline Jenkins
2. После тестирования смотрю отчет Allure
3. Большинство ошибок при открытие форм в отчете в статусе "broken" и сообщения об ошибке содержат фрагменты кода тестовой обработки (см. ниже), вместо кода формы с ошибкой (скриншот с примером ошибки приложен)

Ожидается статус "Failed" и сообщение об ошибки с фрагментом кода тестируемой формы

Сообщение об ошибке в отчете:
Failed] Выявлено модальное окно:
[Переход по кнопке командного интерфейса] 
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(1654)}:	ВызватьИсключение Префикс + " " + СообщениеОшибки;
{ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.Форма.УправляемаяФорма.Форма(1278)}:	КонтекстЯдра.ВызватьОшибкуПроверки(ТекстИсключения);
{ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.Форма.УправляемаяФорма.Форма(1221)}:	ИдентифицироватьОкноПредупреждение(ПереходПоКнопкеКомандногоИнтерфейса(), ТестКлиент);
{ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.Форма.УправляемаяФорма.Форма(677)}:		ТестироватьФормуНаКлиентеТестирования(ПолноеИмяФормы, ПараметрыФормы);
{ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.Форма.УправляемаяФорма.Форма(759)}:	ТестироватьФорму(Мета_ПолноеИмя, ПараметрыФормы);
{ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.Форма.УправляемаяФорма.Форма(993)}:	ТестироватьФормуСсылочногоОбъекта(Мета_ПолноеИмя, Неопределено);
{(1)}:КонтекстВыполнения.ТестДолжен_ОткрытьФормуНовогоДокумента(Параметры[0]);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(934)}:	Выполнить(ИcполняемыйКод);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(811)}:			ВыполнитьПроцедуруКонтекста(КонтекстВыполнения, ЭлементДереваТестов.ИмяМетода, ЭлементДереваТестов.Параметры);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(795)}:		РезультатТестирования = ВыполнитьТестовыйМетодНаКлиенте(КонтекстВыполнения, ЭлементДереваТестов);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(678)}:				ДочернийРезультатТестирования = ВыполнитьТестовыйМетод(КонтекстВыполнения, ДочернийУзел);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(662)}:			ДочернийРезультатТестирования = ВыполнитьТесты(Загрузчик, ДочернийУзел, ФильтрДляДочернихУзлов, Подписчик, Родитель, ПараметрыПотоковыхОтчетов);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(662)}:			ДочернийРезультатТестирования = ВыполнитьТесты(Загрузчик, ДочернийУзел, ФильтрДляДочернихУзлов, Подписчик, Родитель, ПараметрыПотоковыхОтчетов);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(1539)}:		РезультатыТестирования = ВыполнитьТесты(Загрузчик, ДеревоТестовОтЗагрузчика);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(1224)}:		РезультатыТестирования = ЗагрузитьИВыполнитьТесты_ПакетныйРежим(ПараметрыЗапуска.Параметры_xddRun);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(1168)}:			ВыполнитьПакетныйЗапускСинхронно(НастройкиШагов);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(70)}:		ВыполнитьПакетныйЗапуск(ПараметрЗапуска);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(352)}:	ПриОткрытииЗавершение();
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(345)}:	ЗагрузкаПлагиновЗавершение();
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(309)}:	ПодключитьНайденныеКлиентскиеПлагины(ПомещенныеФайлы, ДополнительныеПараметры.ИдентификаторыПлагинов);
{(1)}:ОписаниеОповещения.Модуль.ОбработчикПоискаКлиентскихПлагиновЗавершение(Результат, ОписаниеОповещения.ДополнительныеПараметры)
{ВнешняяОбработка.xddTestRunner.Форма.МодульАсинк.Форма(202)}:				Выполнить("ОписаниеОповещения.Модуль." + ОписаниеОповещения.ИмяПроцедуры + "(Результат, ОписаниеОповещения.ДополнительныеПараметры)");
{ВнешняяОбработка.xddTestRunner.Форма.МодульАсинк.Форма(596)}:			смв_ВыполнитьОбработкуОповещения(ОписаниеОповещенияОЗавершении, ПомещенныеФайлы);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(294)}:			АСинк().смв_ПоместитьФайлы(ОписаниеЗавершения, ПомещаемыеФайлы);
{(1)}:ОписаниеОповещения.Модуль.ОбработчикПоискаКлиентскихПлагинов(Результат, ОписаниеОповещения.ДополнительныеПараметры)
{ВнешняяОбработка.xddTestRunner.Форма.МодульАсинк.Форма(202)}:				Выполнить("ОписаниеОповещения.Модуль." + ОписаниеОповещения.ИмяПроцедуры + "(Результат, ОписаниеОповещения.ДополнительныеПараметры)");
{ВнешняяОбработка.xddTestRunner.Форма.МодульАсинк.Форма(892)}:			смв_ВыполнитьОбработкуОповещения(ОписаниеОповещенияОЗавершении, Результат);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(249)}:		АСинк().смв_НайтиФайлы(ОбработчикПоискаКлиентскихПлагинов,
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(46)}:	ЗагрузитьПлагины();

Categories: Test defects  

Severity: normal

 Duration:  6s 061ms  

Execution

No information about test execution is available. 

**Скриншоты**
![Снимок](https://user-images.githubusercontent.com/65337206/81915398-33f08a80-95db-11ea-8c7b-15c72a09a23f.PNG)

**Окружение:**

**Дополнительный контекст**

- Типовая или не типовая конфигурация ?
1С:ERP Управление предприятием 2 (2.4.9.70) (сильно доработанная)
- Включен ли режим защиты от опасных действий
- и т.д.

**Comment by artbear** [comment]
@Alexey-Zharkov интересно, да, очень похоже на неверное поведение теста

приложи, пожалуйста, техническую информацию из Ванесса-АДД 6.6.5 - через меню Загрузить или Внешние инструменты

**Comment by artbear** [comment]
@Alexey-Zharkov интересно, да, очень похоже на неверное поведение теста

Приложи, пожалуйста, описание окружения из Vanessa-ADD 6.6.5 - подменю "Загрузить" - кнопка "Техническая информация" и вставить сюда.

закрыл случайно. переоткрываю.

**Comment by Alexey-Zharkov** [comment]
Прилагал, ведь. Видимо, стер случайно.
Техническая информация:
	- Версия Vanessa-ADD: 6.6.5
	- Имя конфигурации: УправлениеПредприятием
	- Синоним конфигурации: 1С:ERP Управление предприятием 2
	- Версия конфигурации: 2.4.9.70
	- Платформа 1С: 8.3.16.1296
	- Тип базы: Клиент-серверная ИБ
	- Режим запуска: Управляемое приложение (Тонкий клиент)
	- Режим совместимости (для TestManager): Версия8_3_12
	- Режим совместимости интерфейса (для TestManager): ТаксиРазрешитьВерсия8_2
 	- Режим синхронности: включен
 	- Защита от опасных действий: выключен
	- Язык (для TestManager): Русский
	- Локализация (для TestManager): ru_RU
	- Операционная система (клиент): Windows x86-64 Microsoft Windows 10 version 10.0  (Build 14393)
	- Операционная система (сервер): Windows x86-64 Microsoft Windows 10 version 10.0  (Build 14393)

**Comment by artbear** [comment]
Сделано в https://github.com/vanessa-opensource/add/pull/753

**Comment by Alexey-Zharkov** [comment]
Добрый день, когда ждать выхода релиза 6.7.0? Есть надежда, что эта ошибка когда-то исправится?
