### ISSUE TITLE
Добавить проверку модифицированности формы ПриОткрытии

### ISSUE THREAD

**Issue by GladilovDmitry** [silverbulleters/add#741]
**Существует проблема**
В модифицированной конфигурации может присутствовать код, модифицирующий данные объекта формы при открытии.

**Хотелось бы иметь следующую функциональность**
В тестах, проверяющих открытие формы, выполнять проверку ТестируемаяФорма.ТекущаяМодифицированность() сразу после открытия формы.
Например, в тестах КомандныйИнтерфейс и ОткрытиеФормКонфигурации

**Comment by artbear** [comment]
я уже сделал ишуз на эту тему https://github.com/vanessa-opensource/add/issues/738

закрываю как дубль.
