### ISSUE TITLE
 Медленная работа продукта на больших конфигурациях (xdd)

### ISSUE THREAD

**Issue by GladilovDmitry** [silverbulleters/add#744]
**Описание ошибки**
Загрузка тестов в xddRunner.epf выполняется долго на больших конфигурациях, например ЕРПУХ.

**Предлагаемое решение**
По замеру производительности выявлены несколько не оптимальных мест, связанных с выполнением обработок входящих в состав продукта в цикле для каждого загружаемого в браузер теста.

1. Tests_SmokeCommonModules.Forms.Form._StrTemplate()
Выполняется создание объекта обработки, с обращением к методу объекта _StrTemplate().
Предлагаю заменить обращение к методу объекта на метод формы, с использованием СтрШаблон() - вместо использования СтрЗаменить() в _StrTemplate().
2. ПостроительДереваТестов.Формы.Форма
В клиентской функции СоздатьЭлемент() выполняется обращение к методу, создающему объект обработки для выполнения простого кода по созданию структур ЭтотОбъектНаСервере().СоздатьЭлемент(). Предлагаю заменить серверный код на выполнение на клиенте, скопировав код в форму.
3. xddTestRunner.Формы.УправляемаяФорма
В клиентсокой процедуре ЗагрузитьТесты() вызывается СохранитьВИсториюЗагрузкиТестовНаСервере(), где выполняется создание объекта обработки. А для 16.000 элементов в дереве для УФ это очень не быстро.
Предлагаю скопировать/перенести код в клиентский метод, т.к. метод объекта СохранитьВИсториюЗагрузкиТестов() работает лишь со структурой и строками.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть xddTestRunner

**Окружение:**
Техническая информация:
	- Версия Vanessa-ADD: 6.6.5
	- Имя конфигурации: УправлениеХолдингомERP
	- Синоним конфигурации: 1С:ERP. Управление холдингом
	- Версия конфигурации: 3.0.2.27
	- Платформа 1С: 8.3.15.1830
	- Тип базы: Клиент-серверная ИБ
	- Режим запуска: Управляемое приложение (Тонкий клиент)
	- Режим совместимости (для TestManager): Версия8_3_12
	- Режим совместимости интерфейса (для TestManager): ТаксиРазрешитьВерсия8_2
 	- Режим синхронности: включен
 	- Защита от опасных действий: выключен
	- Язык (для TestManager): Русский
	- Локализация (для TestManager): ru
	- Операционная система (клиент): Windows x86-64 Microsoft Windows 10 version 10.0  (Build 14393)
	- Операционная система (сервер): Windows x86-64 Microsoft Windows 10 version 10.0  (Build 14393)

**Comment by artbear** [comment]
@GladilovDmitry Спасибо, полезные замечания.

**Comment by artbear** [comment]
>xddTestRunner.Формы.УправляемаяФорма
В клиентсокой процедуре ЗагрузитьТесты() вызывается СохранитьВИсториюЗагрузкиТестовНаСервере(), где выполняется создание объекта обработки. А для 16.000 элементов в дереве для УФ это очень не быстро.
Предлагаю скопировать/перенести код в клиентский метод, т.к. метод объекта СохранитьВИсториюЗагрузкиТестов() работает лишь со структурой и строками.

@GladilovDmitry не вижу, где тут могут быть проблемы.
Метод ЗагрузитьТесты вызывается один раз,
метод СохранитьВИсториюЗагрузкиТестовНаСервере() также вызывается один раз.
и создание объекта обработки выполняется быстро.
откуда связь с количеством объектов?

**Comment by GladilovDmitry** [comment]
Да, указанные методы вызываются ограниченное число раз. Но. На форме
размещено дерево. И оно сериализуется при обращении к серверу и обратно.
Все 16.000 строк.
Таким образом получаем ощутимую задержку (на моём примере 4 сек) на каждом
вызове указанных методов.

пт, 22 мая 2020 г., 19:42 Artur Ayukhanov <notifications@github.com>:

**Comment by artbear** [comment]
@GladilovDmitry Большое спасибо. Сделал по твоим рецептам в https://github.com/vanessa-opensource/add/pull/752
