### ISSUE TITLE
Проверить обработки на устаревшие ссылки

### ISSUE THREAD

**Issue by GladilovDmitry** [silverbulleters/add#745]
**Описание ошибки**
В поле "комментарий" xddTestRunner указано "https://github.com/silverbulleters/add"
Необходимо проверить все обработки проекта на устаревшие ссылки.

**Окружение:**
Техническая информация:
	- Версия Vanessa-ADD: 6.6.5
	- Имя конфигурации: УправлениеХолдингомERP
	- Синоним конфигурации: 1С:ERP. Управление холдингом
	- Версия конфигурации: 3.0.2.27
	- Платформа 1С: 8.3.15.1830
	- Тип базы: Клиент-серверная ИБ
	- Режим запуска: Управляемое приложение (Тонкий клиент)
	- Режим совместимости (для TestManager): Версия8_3_12
	- Режим совместимости интерфейса (для TestManager): ТаксиРазрешитьВерсия8_2
 	- Режим синхронности: включен
 	- Защита от опасных действий: выключен
	- Язык (для TestManager): Русский
	- Локализация (для TestManager): ru
	- Операционная система (клиент): Windows x86-64 Microsoft Windows 10 version 10.0  (Build 14393)
	- Операционная система (сервер): Windows x86-64 Microsoft Windows 10 version 10.0  (Build 14393)

**Comment by artbear** [comment]
Да, эту часть пропустили.
Вроде бы я в ветке девелоп исправил уже.
Еще проверю.

**Comment by artbear** [comment]
исправлено.
