### ISSUE TITLE
Добавить возможность исключения планов обмена из теста командного интерфейса

### ISSUE THREAD

**Issue by GladilovDmitry** [silverbulleters/add#746]
**Существует проблема**
В ЕРПУХ при тестировании командного интерфейса получаем ошибки в большом числе тестов из-за модального окна получаемого при закрытии формы настройки обмена из плана обмена НалоговыйМониторинг: Налоговый мониторинг->Публикация данных налогового мониторинга: проверка элемента командного интерфейса.

**Хотелось бы иметь следующую функциональность**
поддерживаемую секцию "Планы обмена" в vanessaTddConf.json

**Comment by artbear** [comment]
@GladilovDmitry @VladFrost а может быть, научиться такое модальное окно научиться закрывать?
исключения все-таки большое зло.

@GladilovDmitry можешь привести данные по этому модальному окну?
из бдд-режима и Исследователя форм, например?
текст заголовка, имя формы, текст предупреждения, наличие кнопок и т.п.

**Comment by VladFrost** [comment]
Исключения – это зло, но это неизбежное зло. Лучше всего, конечно, баг вендору зарегить, и сослаться на стандарт, который нарушен в модальном диалоге. Стандарты опубликованы https://its.1c.ru/db/v8std

1. Типовые исключения можно прям в коде зашивать, как здесь https://github.com/vanessa-opensource/add/blob/master/tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl#L271

2. В плагине "ТестКлиенты" есть алгоритм, который нажимает подходящую кнопку, можно его попробовать допилить, чтобы и в случае с налоговым мониторингом срабатывал https://github.com/vanessa-opensource/add/blob/master/plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl#L317

**Comment by GladilovDmitry** [comment]
>Лучше всего, конечно, баг вендору зарегить, и сослаться на стандарт, который нарушен в модальном диалоге.

Так стандарт-то вроде не нарушен. Модальный диалог выводится при попытке закрытия формы, т.к. (в вольном изложении) "настройка обмена не завершена. Вы уверены что хотите закрыть?". Или я не нашел нарушенный стандарт?

**Comment by GladilovDmitry** [comment]
> @GladilovDmitry можешь привести данные по этому модальному окну?
> из бдд-режима и Исследователя форм, например?
> текст заголовка, имя формы, текст предупреждения, наличие кнопок и т.п.

![Безымянный](https://user-images.githubusercontent.com/49302260/82310827-8bbd3600-99cd-11ea-997e-98cd505257ed.png)
![Безымянный2](https://user-images.githubusercontent.com/49302260/82310838-8f50bd00-99cd-11ea-9ef5-9aa30bc36a53.png)
![Screenshot_1](https://user-images.githubusercontent.com/49302260/82311164-025a3380-99ce-11ea-8674-5fe16fe8d6fe.png)

**Comment by GladilovDmitry** [comment]
> Типовые исключения можно прям в коде зашивать, как здесь https://github.com/vanessa-opensource/add/blob/master/tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl#L271

Можно-то можно, да только для каждой конфы они разные. Писать вообще все возможные?
Вообще мне не нравится зашивать что-то жестко в код, т.к. тогда нельзя просто "воткнуть"новую версию vanessa, надо где-то хранить свои версии обработок, мержить их. Брр.
Лучше хранить их в том же vanessaTddConf.json. Про что по-сути и идет речь в данном issue. Кстати я бы и уже зашитые исключения вынес в поставляемый vanessaTddConf.json и удалил из кода обработки.

**Comment by artbear** [comment]
вроде бы в 1С-конфах есть типовой вопрос "Завершить работу с помощником?"
в демке БСП часто вижу его.

может быть, нам добавить обработку этого модального окна?

**Comment by VladFrost** [comment]
> может быть, нам добавить обработку этого модального окна?

Да, хороший вариант.
