### ISSUE TITLE
Добавить возможность отключения наборов дымовых тестов в vanessaTddConf.json

### ISSUE THREAD

**Issue by GladilovDmitry** [silverbulleters/add#748]
**Существует проблема**
При отладке запуска тестов удобно отключать некоторые наборы тестов для более быстрого прохождения цикла.
При этом для некоторых наборов тестов нет возможности отключить выполнение в файле настроек, как правило для набора можно только указать массив игнорируемых объектов метаданных.
Немного другой пример - ПроверкаЧтенияНеАдминистраторами: возможно лишь указать какие роли считать "администраторскими" (массив привилегированных ролей); в интерактивном режиме возможность отключения данного набора тестов так же отсутствует.

**Хотелось бы иметь следующую функциональность**
Для каждого узла в файле (набора тестов) предусмотреть возможность установки флага false.

**Comment by GladilovDmitry** [comment]
360 "проблем" на типовых объектах ERP
![Screenshot_5](https://user-images.githubusercontent.com/49302260/82577259-624e0700-9b93-11ea-8d82-c82b6697afcb.png)

**Comment by artbear** [comment]
Реализовано в https://github.com/vanessa-opensource/add/pull/790 и https://github.com/vanessa-opensource/add/pull/783

**Comment by artbear** [comment]
и задокументировано.
