### ISSUE TITLE
Вывод сообщений о прохождении тестов в лог-файл для возможности передачи в консоль, не дожидаясь завершения сеанса 1С

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#75]
При выполнении некоторых тестов могут быть непредвиденное поведение:
- падает 1С
- появляется модальное окно
- слишком долго выполнение тестов, например, зависание
- выполняются еще какие-то странные действия

Для всех этих случае нужно понимать, какой тест виноват в подобном поведении.
Для этого нужно вести лог-журнал запуска/завершения очередного теста и падений тесто

Предлагается реализовать подобное логирование в отдельном лог-файле фреймворка тестирования.

Набор задач:

- [x] Доработать vanessa-runner

- [x] Удобно выделить подобное поведение в отдельный плагин "ВыводВЛогФайл" - например, из VB
- [x] Добавить для ОФ xunit
- [x] Добавить для УФ xunit

- [x] Добавить в xUnit включение вывода в лог-файл из плагина настроек. Ключ `ДелатьЛогВыполненияСценариевВТекстовыйФайл`, как и для VB

- [x] Добавить в xUnit чтение имени лог-файла плагинов настроек. Ключ `ИмяФайлаЛогВыполненияСценариев`, как и для VB

- [x] Добавить удаление файла при начале тестирования

- [x] При записи строки файл должен полностью закрываться

- [x] Вставить сообщения о начале прохождения тестов, как в VB

- [x] Заменить вызовы в VB на вызовы плагина

Vanessa-behavior умеет спамить в лог прямо во время работы, не дожидаясь закрытия окна 1С
Вывод информации в отдельный файл, а vanessa-runner отдельно читает и выводит в стандартный вывод. Пример вывода http://ci.silverbulleters.org/job/ADD%20test/job/develop/17/console

```
[behavior 8310UF] ИНФОРМАЦИЯ - 5%
[behavior 8310UF] ИНФОРМАЦИЯ - Сценарий: Загрузка фичи с секцией Контекст, когда указаны теги фильтры
[behavior 8310UF] 27.03.2018 11:00:33: ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - Сценарий: Загрузка фич когда указаны теги фильтры и теги исключения
[behavior 8310UF] 27.03.2018 11:01:12: ИНФОРМАЦИЯ - ИНФОРМАЦИЯ - Фича: c:\cicd\workspace\p\build\features\Core\FeatureReader\ОтрицательныеЧисла.feature
[behavior 8310UF] ИНФОРМАЦИЯ - 6%
```

Исходная задача https://github.com/xDrivenDevelopment/xUnitFor1C/issues/532

**Comment by artbear** [comment]
@pumbaEO хочу выполнить пункт чек-листа
`Заменить вызовы в VB на вызовы плагина`

уточняю на всякий случай
+ исходники bddRunner меняю, верно?
+ на мерж сильно повлияет?

PS заменю вызов внутри `ЗаписатьЛогВТекстИнформация` и добавлю начальную настройку

**Comment by artbear** [comment]
Остался только этот пункт, остальные выполнены.

**Comment by pumbaEO** [comment]
Ну мы уже начинаем сильно расходится, поэтому что уже на merge смотреть. 
Да, меняешь исходники в управляемой форме.

**Comment by artbear** [comment]
В https://github.com/silverbulleters/add/pull/81 все пункты чек-листа реализованы.
Сапсан рулит :)
