### ISSUE TITLE
Ошибка выполнения шага паузы при закрытом тестовом клиенте

### ISSUE THREAD

**Issue by PashaMak** [silverbulleters/add#756]
**Описание ошибки**
При выполнении шага "И Пауза 5" появляется ошибка "{ВнешняяОбработка.СделатьПаузу.Форма.Форма.Форма(87)}: Значение не является значением объектного типа (НайтиОбъект)". Обработка "C:\Program Files (x86)\OneScript\lib\add\features\libraries\Пауза\step_definitions\СделатьПаузу.epf".
Версия 6.6.0

**Сценарий воспроизведения**
Шаги по воспроизведению:
В первом тесте
1. Выполнить шаг по открытию тестового клиента
Дано Я открыл новый сеанс TestClient или подключил уже существующий		
2. Выполнить шаг по закрытию тестового клиента
И я закрываю сеанс TESTCLIENT
Во втором тесте
3. Выполнить шаг паузы
И Пауза 5

**Скриншоты**
если применимо, приложите скриншоты
![image](https://user-images.githubusercontent.com/24808007/82859119-0fcc6c00-9f40-11ea-8109-89a4359e5384.png)

**Окружение:**

**Дополнительный контекст**
Режим защиты от опасных действий выключен.

**Comment by artbear** [comment]
выполнено в https://github.com/vanessa-opensource/add/pull/764
