### ISSUE TITLE
Записать в FAQ про переход на add из xUnitFor1C и vanessa-behavior

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#77]
Вопрос:
Привет, Артур!
Расскажи, пожалуйста, про https://github.com/silverbulleters/add
относительно https://github.com/xDrivenDevelopment/xUnitFor1C и https://github.com/silverbulleters/vanessa-behavior

1) умеет ли add всё, что умеет иксюнит и вб?
2) как дорабатываются эти 3 продукта, какой приоритет?
3) есть ли смысл переползать на add уже сейчас?)

Ответы:
1) умеет и даже лучше
Совместимость с VB 1.Х и xUnitFor1C 4.Х гарантирована
2) add в максимальном приорите, поддержка VB и xUnitFor1C постепенно прекратится
3) Да, нужно переезжать на add уже сейчас

**Comment by 1cgh** [comment]
@artbear Поддерживается ли add со стороны https://github.com/silverbulleters/vanessa-runner?

**Comment by artbear** [comment]
@1cgh Да, конечно.
Более того
+ полный пакет add можно ставить легко и автоматически при помощи OneScript - команда opm install add
+ при установке vanessa-runner пакет add ставится автоматически :)
+ сразу после установки можно выполнять команды vanessa-runner для запуска браузеров без необходимости указания путей к инструментам
  + `bddTestRunner` (ранее `VB`)- команда `vrunner vanessa`
  + `xddTestRunner` (ранее `xUnitFor1C`) - команд `vrunner xunit`

**Comment by artbear** [comment]
@kuntashov Конечно, в первую очередь нужно читать `прекратится поддержка со стороны SB`.
Продукт-то открытый.

Но я лично очень надеюсь, что постепенно и остальное сообщество переключится на этот единый продукт и поддержка прекратится полностью, т.к. add далеко уйдет от своих предков.

Мы с @pumbaEO уже активно поддерживаем новый продукт, также еще сотрудники SB также подключаются постепенно.

**Comment by artbear** [comment]
Формулировка исключительно моя.
Извините, если прозвучало двусмысленно.

**Comment by nixel2007** [comment]
а откуда она MPL-то стала? на каком основании?

**Comment by pumbaEO** [comment]
https://github.com/silverbulleters/add/blame/master/LICENSE

**Comment by nixel2007** [comment]
@allustin ?

**Comment by artbear** [comment]
>Как дела с обратной совместимостью по лицензиям? Возможно ли будет с этой точки зрения доработки из add переносить в xUnit?

у нас лицензия Mozilla Public License 2.0, нет проблем при указании копирайтов.

@kuntashov Саша, реально не очень бы хотелось раздвоения продуктов

**Comment by artbear** [comment]
Ну и да, ждем @allustin и договоримся по лицензии.

**Comment by allustin** [comment]
пинг видел - отвечу вечером

**Comment by Pr-Mex** [comment]
Народ, объясните на пальцах, что меняется в лицензиях?
Новая лицензия сильнее ограничивает? Слабее?

**Comment by artbear** [comment]
По лицензии мы решим в ближайшее время.
Очень вероятно, что вернемся на Apache :)

**Comment by Pr-Mex** [comment]
У VB сейчас лицензия Free Bsd v3. Она совместима с Apache?

**Comment by allustin** [comment]
Так - давайте я прокоментирую сам ишуз

* add решает 2 боли: удобный контрибьютинг, декомпозиция инструмента на модули

со второй болью мы столкнулись во времена xUnit3 - сторожилы помнят, архрешение с плагинами было очень крутым и докзало свою эффективность.

с первой болью мы столкнулись во время развития vanessa-behavior - очень неудобно контрибьютить

есть 2 дополнительные боли:

* сборка vanessa-behavior идет 8 часов (причины обсуждать не будем, просто примем как факт) - нужно расспаралеливать
*  сборка xUnit4 идет скажем так нерегулярно, а люди пользуются (например на УНФ)

то есть нужно решить все боли, с учетом одной особенности: @Pr-Mex в Пуле не работает и сейчас у него есть свои обязательства перед текущим работодателем и наши боли у него в низком приоритете. 

Отсюда исходный ишуз @artbear о создании группировочного проекта.

Теперь что касается лицензии - MPL выбран как расширение Apache License - у этих двух лицензий существует одно небольшой различие. MPL ставит условием "не закрытие исходников при распространении", соответственно на код xUnit который портирован - действует mpl без условия открытия исходников (закрываете при распространении, за исключением того что будет доработано уже в рамках MPL) - условие используется на всякий случай

Собственно и bsd лицензия также совместима как с apache, так и с mpl

Напомню MPL - в oscript, отличется от Апатча одним пунктом защищяющим от вирусописаталей https://github.com/EvilBeaver/OneScript/blob/develop/LICENSE

@nixel2007 MPL выставлял я в присутствии @artbear ;-)

P.S. А чего случилось то ? Откуда такой тред и с чем связан - по моему мы наконец-то наводим порядок и пошло движение в части старых проблем. Чего вдруг.

```
 прекращать поддержку оригинально репо Vanessa-Behavior я не планирую
```

@Pr-Mex - мы как ты понял планируем и уже делаем. С сентября же работаем над объединением - чего не так то ? Откуда опять холивар нарисовался непонятно - по моему очень круто выходит и понятно и в одном месте.

**Comment by Pr-Mex** [comment]
@allustin 
Буду краток.
С моей стороны это выглядит так:
28 марта Артур написал в скайпе
![image](https://user-images.githubusercontent.com/8627416/38165625-1de3c622-351f-11e8-8ccf-7915874c59da.png)


Я перехожу по ссылке и узнаю, что существует новый проект, который обладает следующими особенностями:
1. Там зачем-то объединены три продукта в одном репо. Что, как минимум, странно. Я бы, например, сделал три репо (VB, xUnit, Плагины), т.к. в этом есть свои плюсы.
2. Там изменена лицензия.
3. Не понятно как мне управлять развитием своего продукта, когда в одном репо - есть ещё два других.
4. Со мной ни один из этих моментов никто не согласовывал и даже не обсуждал. Ни в скайпе, ни в почте, вообще нигде.

Поэтому говорить о переходе на новый проект (с моей стороны) - крайне преждевременно.

**Comment by pumbaEO** [comment]
![default](https://user-images.githubusercontent.com/166003/38165811-39c63174-3522-11e8-87d5-0badce1401b6.png)

**Comment by allustin** [comment]
> Там зачем-то объединены три продукта в одном репо. Что, как минимум, странно

* объяснял я, Артур, Женя начиная с сентября. Лично, в скайпе тестом, по видео связи. vb2 репозиторий живет ОЧЕНЬ давно

> управлять развитием своего продукта

Ну и куда тебя эта формулировка приведет ? в 2014 году уже был холивар - чей продукт, тогда мы мерялись с @artbear.  Продукт не твой, а наш. Валеры на тебя нет (царство небесное).

> Там изменена лицензия.

* я не изменил, а расширил - объяснил выше, 

> Со мной ни один из этих моментов никто не согласовывал и даже не обсуждал. Ни в скайпе, ни в почте, вообще нигде.

Формально это не так. Именно ты просил что до перехода на новый формат разработки и объедненную версию. Если пересчитать в деньги время которое затрачено на убеждение с сентября - получится что мы все могли квартиру в Москве купить. Время уходит в пустоту.

@Pr-Mex можно тебе личную просьбу. Не вводи людей в заблуждение: если я правильно тебя понимаю у тебя нет времени и желания разбиратся в новом способе контрибьютинга и в улучшенном архитектурном решении. Мы это понимаем и принимаем - но блокировать развитие vb, xunit, add это не может. Это не отвечает целям пользователей продуктов и контрибьюторов.

@artbear пожалуйста - закрой задачу как планировали: холивары дороги. Мне 40 лет - я хочу успеть сделать мир прекрасней до своей смерти. И вместо коментов на gitHub успеть покодить, а issues слишком много, а времени слишком мало.

P.S. Раздел форума ADD живет с октября https://xdd.silverbulleters.org/c/razrabotka/vanessa-add

**Comment by allustin** [comment]
@kuntashov - насчет монополизации ты не прав: из сотрудников SB участвует в основном @artbear - остальные люди с правами на репозиторий в SilverBulleters не работают.

**Comment by Pr-Mex** [comment]
>объяснял я, Артур, Женя начиная с сентября. Лично, в скайпе тестом, по видео связи. vb2 репозиторий живет ОЧЕНЬ давно

Проект VB2 не подразумевал добавления туда xUnit. Даже из названия проекта это хорошо заметно )))
Ни в скайпе, ни текстом про добавление в VB2 других проектов не говорилось.

>Продукт не твой, а наш.

В широком смысле он вообще принадлежит человечеству )))
Просто Серебряная пуля за последние три года особо не вкладывалась в разработку Vanessa-Behavior. Коммитов от SB, к сожалению - очень мало.  Это хорошо видно по этой ссылке.
https://github.com/silverbulleters/vanessa-behavior/graphs/contributors
~~Видимо это такой вариант экономии на покупку квартир в мск.~~

>Формально это не так. Именно ты просил что до перехода на новый формат разработки и объедненную версию.

Это не так. Я никогда такого не просил.

>можно тебе личную просьбу. Не вводи людей в заблуждение: если я правильно тебя понимаю у тебя нет времени и желания разбиратся в новом способе контрибьютинга и в улучшенном архитектурном решении. Мы это понимаем и принимаем - но блокировать развитие vb, xunit, add это не может. Это не отвечает целям пользователей продуктов и контрибьюторов.

Мне странно наблюдать такую реакцию. У SB какой-то особый подход - делать готовое решение, а потом ставить перед фактом - что теперь будет вот так. Так уже было с первой итерацией перехода на VB2. Потом вы согласились, что предложенное вами решение было не очень и вы решили его переделать. И вроде бы предыдущие проблемы решены, но теперь добавились новые.
Теперь в одном проекте оказалось несколько проектов. Это и есть "улучшенное" архитектурное решение?

>P.S. Раздел форума ADD живет с октября https://xdd.silverbulleters.org/c/razrabotka/vanessa-add

Это может показаться странным, но я не слежу за всеми публикациями, активностями, проектами SB. Есть скайпы, почты и т.д. Т.е. способов для связи - достаточно (если это кому-то надо).

**Comment by theshadowco** [comment]
Извините что вмешиваюсь, но может все таки в оффлайн/приват?

Неприятно наблюдать за данным извините за откровенность срачем.

**Comment by pumbaEO** [comment]
Та какой срач, обычный холивар. 
1. Есть сложность с коллективной доработкой при использовании precommit1c, соответственно чаще использовался вариант "Скажу Лёне, он исправит", чем сделать форк изменить что-то, а потом с матюками мержить бинарники. 
2. VB2 как эксперемент показал, свою жизнеспособность, но у Лёни были замечания по организации работы. Когда замечания были исправленны, раз в месяц был пинг "найди время, перейдем на новый процесс". Времени не находилось. Теперь  возмущение "делать готовое решение, а потом ставить перед фактом - что теперь будет вот так. "
3. Каждый раз слышу "я тут главный контрибьютер", но и каждый раз объясняю, что с тем процессом который в пункте 1 это естественно. Даже по пункту 2 делал всё лишь бы Лёня был удовлетворен процессом. 

Теперь по поводу замечаний по сути: 
1. Лицензия - да, тут согласен вопрос публично не решили. Я пропустил, что поменялась лицензия, @allustin  надо выносить на голосовалку.
2. Объединение xUnit и vanessa, имхо мне от этого не хололдно ни жарко, но если всех беспокоит, то без проблем разделяем каталоги, но опять таки идея с объединением плагинов отодвинится еще дальше. 
3. Если разделяем на проекты vb2 , xunit2 , то будет ли переходить Леонид или же все также не сможет найти время в размере 30 минут, на клонирование, компиляцию, испраления 1й строки и отправки pull . 

Соответственно, основной вопрос к @Pr-Mex - собираешься переходить на разработку через исходники в **ближайшее будущее** или нет. Я очень, надеюсь, что да и тогда обсуждение этой задачи станет полезным и коллективным решением вырабатаем какое-то решение.

**Comment by pumbaEO** [comment]
@Pr-Mex  давай может все-таки синхронизируемся, сделаем скрипт, который из add сделает коммит в vanessa-behavior (ну или pull request) ? Тогда, легаси живет по старому, разработка по факту тоже по старому, только добавляем две комманды "ПередНачаломРаботы", после окончания работы? Так подойдет?

**Comment by artbear** [comment]
Документировано
