### ISSUE TITLE
Ошибка в журнале регистрации при запуске теста "Тесты_ОткрытиеФормКонфигурации"

### ISSUE THREAD

**Issue by BarmashovAndrey** [silverbulleters/add#772]
## Запрос поддержки

Добрый день, при запуске с командной строки теста "Тесты_ОткрытиеФормКонфигурации", в журнале регистрации фиксируется ошибка
 "{ВнешняяОбработка.Тесты_ОткрытиеФормКонфигурации.Форма.УправляемаяФорма.Форма(1119)}: Value is not of object type (Удалить)
СозданныйОбъект.Удалить();".
У нас несколько тестов последний юнит тест который проверяет изменения в ЖР, и так как там ошибка он считает что тесты пройдены не правильно. 
Хотел спросить эта ошибка должна быть или эта ошибка не корректности выполнения теста?

## Критичность запроса

Чем раньше тем лучше ))

**Comment by BarmashovAndrey** [comment]
Ошибка формировалась при удаления элемента справочника у которого был владелец. В коде вначале происходило удаление владельца далее само удаление элемента справочника. При этом когда удалялся владелец удалялись и подчиненные элементы справочника, а когда доходило до удаление элемента то падала ошибка. Установил условие на владельцев если они есть, то удаляем только основного владельца, он в свою очередь подтянет остальные элементы.

**Comment by artbear** [comment]
выполнено.
