### ISSUE TITLE
в обработке СериализаторMXL из папки плагинов кнопка ЗагрузитьНастройки меняет ДеревоМетаданных

### ISSUE THREAD

**Issue by sulfur17** [silverbulleters/add#773]
**Описание ошибки**
меняется дерево метаданных на форме, и оно уже может не соответствовать дереву метаданных базы

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть СериализаторXML
2. Раскрыть Настройки, там выбрать путь к файлу настроек и нажать Сохранить настройки
3. Перейти в базу с другой конфигурацией (например в базу релиз из базы разработки)
4. Открыть СериализаторXML там
5. Раскрыть Настройки, там выбрать путь к файлу настроек и нажать Загрузить настройки

**Ожидаемое поведение, если бы ошибки не было**
Дерево конфигурации не должно измениться, должны только проставиться галочки и отборы

**Comment by artbear** [comment]
Реализовано в https://github.com/vanessa-opensource/add/pull/775

**Comment by artbear** [comment]
@sulfur17 Большое спасибо!
