### ISSUE TITLE
Таблица формы стала равной: проверка дат и чисел

### ISSUE THREAD

**Issue by shureek** [silverbulleters/add#778]
При проверке значений в таблице формы было бы удобно, если бы даты и числа можно было сравнивать по значению, если это возможно.

Было бы удобно, если бы такая конструкция работала:

```
Тогда таблица "МояТаблица" стала равной:
    | Сумма | Дата       |
    | 500   | 01.01.2020 |
```

Сейчас получаются ошибки после неявного преобразования значений в строку:  
> Таблица МояТаблица. Строка № 1. Колонка Сумма. Ожидали <500>, а получили <500,000>
> Таблица МояТаблица. Строка № 1. Колонка Дата. Ожидали <01.01.2020 0:00:00>, а получили <01.01.2020>

**Comment by artbear** [comment]
@shureek Отлично, принято! Большое спасибо!
