### ISSUE TITLE
Отображение пути к загруженным настройкам в браузере тестов xddTestRunner

### ISSUE THREAD

**Issue by petypen** [silverbulleters/add#784]
**Существует проблема**
работая с браузером тестов xddTestRunner не видно загружены ли настройки и если загружены, то из какого файла?

**Хотелось бы иметь следующую функциональность**
В интерфейсе браузера тестов xddTestRunner добавить поле с отображением пути к файлу с загруженными настройками

**Дополнительный контекст**
Пример дизайна

![2020-10-14_21-24-25](https://user-images.githubusercontent.com/6500075/96023677-d7341d00-0e63-11eb-8fc8-dc06c9699aa2.png)

**Comment by artbear** [comment]
выполнено.
