### ISSUE TITLE
TDD Плагин Настройки Метод ЕстьНастройка работает не в соответствии со своим описанием

### ISSUE THREAD

**Issue by petypen** [silverbulleters/add#793]
**Описание ошибки**
Для экспортного метода ЕстьНастройка плагина Настройки в описании заявлено:

> // Позволяет одним вызовом получить значение из вложенных друг в друга структур
> 
> // Пример:
> // 		Структура = Новый Структура("Ключ1", Новый Структура("Ключ2", Новый Структура("Ключ3", 42)));
> //		РезультатПроверки = ЕстьНастройка("Ключ1.Ключ2.Ключ3", ВремЗнач);
> // В результате получим ВремЗнач == 42

однако, метод всегда возвращает структуру, даже тогда, когда можно вернуть значение элемента структуры.

**Сценарий воспроизведения**
Шаги по воспроизведению:

В обработку -тест добавить плагин Настройки.
Попробовать вызвать метод ЕстьНастройки по коду из примера выше
Ожидаем получить число 42 а получаем Структуру

**Ожидаемое поведение, если бы ошибки не было**

**Скриншоты**
если применимо, приложите скриншоты

**Окружение:**

**Дополнительный контекст**

- Типовая БУХ 30
- Режим защиты от опасных действий выключен

**Comment by petypen** [comment]
Техническая информация:
	- Версия Vanessa-ADD: 6.7.0
	- Имя конфигурации: БухгалтерияПредприятия
	- Синоним конфигурации: Бухгалтерия предприятия, редакция 3.0
	- Версия конфигурации: 3.0.82.34
	- Платформа 1С: 8.3.17.1549
	- Тип базы: Файловая ИБ
	- Режим запуска: Управляемое приложение (Тонкий клиент)
	- Режим совместимости (для TestManager): Версия8_3_14
	- Режим совместимости интерфейса (для TestManager): ТаксиРазрешитьВерсия8_2
 	- Режим синхронности: выключен
 	- Защита от опасных действий: выключен
	- Язык (для TestManager): Русский
	- Локализация (для TestManager): ru
	- Операционная система: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19041)

**Comment by petypen** [comment]
@artbear Артур, я исправил это поведение в плагине Настройка и хотел бы сделать PR
Нужен твой совет.
Сейчас в плагине есть метод ЕстьНастройка, с описанным неправильным поведением. 
Можно изменить его поведение (сигнатура не изменится), но я боюсь, что кто то уже использует этот метод и адаптировал свои тесты к текущему поведению. В результате у человека начнут валиться тесты.
Можно добавить еще один метод, например ЕстьНастройка2 не трогая старый метод.

**Comment by artbear** [comment]
Да. скорее всего, текущее поведение этого метода уже юзается (
предлагаю исправить описание этого метода

**Comment by artbear** [comment]
выполнено
