### ISSUE TITLE
TDD плагин "Настройки". Экспортные методы ДобавитьНастройку, Добавить настройки работают некорректно

### ISSUE THREAD

**Issue by petypen** [silverbulleters/add#795]
**Описание ошибки**
В интерфейсе плагина Настройки объявлены два метода для программной установки коллекции настроек:
`Процедура ДобавитьНастройку(Знач Ключ, Знач Значение) Экспорт`
`Процедура ДобавитьНастройки(Знач ИсточникНастроек) Экспорт`
однако, вызов этих методов из кода теста приводит к ошибке исполнения.

Оба метода пытаются модифицировать существующую коллекцию `Объект.Настройки` с типом `ФиксированнаяСтруктура`, что не разрешено платформой.

**Сценарий воспроизведения**
Шаги по воспроизведению:

В тесте попытаться вызвать проблемные методы

Пример теста для метода `ДобавитьНастройку`, который падает

```bsl
// Не проходной тест. Должен упасть
&НаКлиенте
Процедура ТестДолжен_ПроверитьРаботуФункции_ДобавитьНастройку() Экспорт
	
	ПараметрыМетода = Новый Массив();
	ПараметрыМетода.Добавить("Ключ99"); // Ключ
	ПараметрыМетода.Добавить(99); // Значение
	
	Ожидаем.Что("Метод работает штатно и не выбрасывает исключение при обращении, но это не так.")
		.Метод("ДобавитьНастройку", ПараметрыМетода)
		.Не_().ВыбрасываетИсключение();
		
КонецПроцедуры
```

Пример теста для метода `ДобавитьНастройки`, который падает

```bsl
// Не проходной тест. Должен упасть
&НаКлиенте
Процедура ТестДолжен_ПроверитьРаботуФункции_ДобавитьНастройки() Экспорт
	
	ПараметрМетода = Новый Структура();
	ПараметрМетода.Вставить("Ключ99", 99);
	
	Ожидаем.Что("Метод работает штатно и не выбрасывает исключение при обращении, но это не так.")
		.Метод("ДобавитьНастройки", ПараметрМетода)
		.Не_().ВыбрасываетИсключение();
		
КонецПроцедуры
```

**Ожидаемое поведение, если бы ошибки не было**
Методы `ДобавитьНастройку` и `ДобавитьНастройки` должны отработать без вызова исключений и модифицировать объект `Объект.Настройки` но это не так.

**Скриншоты**
если применимо, приложите скриншоты

**Окружение:**

- Описание окружения 
Техническая информация:
	- Версия Vanessa-ADD: 6.7.0
	- Имя конфигурации: БухгалтерияПредприятия
	- Синоним конфигурации: Бухгалтерия предприятия, редакция 3.0
	- Версия конфигурации: 3.0.82.34
	- Платформа 1С: 8.3.17.1549
	- Тип базы: Файловая ИБ
	- Режим запуска: Управляемое приложение (Тонкий клиент)
	- Режим совместимости (для TestManager): Версия8_3_14
	- Режим совместимости интерфейса (для TestManager): ТаксиРазрешитьВерсия8_2
 	- Режим синхронности: выключен
 	- Защита от опасных действий: выключен
	- Язык (для TestManager): Русский
	- Локализация (для TestManager): ru
	- Операционная система: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19041)

**Comment by petypen** [comment]
Уточнение к описанию

Проблема имеет место только в контексте Клиента и касается методов расположенных на форме

**Comment by artbear** [comment]
выполнено.
