### ISSUE TITLE
XDD Глобально доступный клиентский контекст для модульных тестов

### ISSUE THREAD

**Issue by petypen** [silverbulleters/add#818]
**Существует проблема**
Некоторые объекты, например СертификатКриптографии, не поддерживают передачу с клиента на сервер и обратно. При модульном тестировании клиентских методов между которыми через КонтекстЯдра СохранитьКонтекст() / ПолучитьКонтекст() передаем подобные объекты получаем ошибку отображения.

**Хотелось бы иметь следующую функциональность**
В браузере тестирования xddTestRunner иметь глобальный клиентский контекст, который существует на протяжении всего сеанса работы основной формы xddTestRunner.

Сейчас, на коленке, в модуле основной формы браузера тестирования xddTestRunner добавил экспортную клиентскую переменную `ГлобальноДоступныйКонтекст`  Работа с таким клиентским контекстом в тесте выглядит следующим образом:
`КонтекстЯдра.ГлобальноДоступныйКонтекст = Сертификат;`
`РабочийСертификатУстановить(КонтекстЯдра.ГлобальноДоступныйКонтекст);`

**Вопрос к сообществу**
Нужно ли эту идею причесать, оформить и задокументировать, после чего сделать PR?

**Дополнительный контекст**
Тестирование методов, которые находятся в модуле управляемой формы.

- Версия Vanessa-ADD: 6.7.0
- Имя конфигурации: БухгалтерияПредприятия
- Синоним конфигурации: Бухгалтерия предприятия, редакция 3.0
- Версия конфигурации: 3.0.84.35
- Платформа 1С: 8.3.17.1823
- Тип базы: Файловая ИБ
- Режим запуска: Управляемое приложение (Тонкий клиент)
- Режим совместимости (для TestManager): Версия8_3_14
- Режим совместимости интерфейса (для TestManager): ТаксиРазрешитьВерсия8_2
 - Режим синхронности: выключен
 - Защита от опасных действий: выключен
- Язык (для TestManager): Русский
- Локализация (для TestManager): ru
- Операционная система: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19042)

**Comment by artbear** [comment]
Выполнено!
