### ISSUE TITLE
Сохраниять  allure отчет по мере выполнения фичи

### ISSUE THREAD

**Issue by pumbaEO** [silverbulleters/add#82]
Сейчас сохранение результатов allure происходит в конце теста, когда большой массив структур передаетса с клиента на сервер, потом такой же объем в виде файлов json возвращается обратно и сохраняется на клиенте в файлы. Сам allure2 все результаты ожидает в небольших json файлах по каждому сценарию с уникальным именем, соответственно нет необходимости именно в конце как раньше для xml файла, формировать 1 огромный файл в конце выполнения, а возможно формировать сразу на клиенте после выполнения фичи и перед переходом к другой фиче.

**Comment by artbear** [comment]
выполнено
