### ISSUE TITLE
Плагин Данные / Метод Реквизит() не проверяет существование реквизита

### ISSUE THREAD

**Issue by kuntashov** [silverbulleters/add#824]
**Описание ошибки**

При использовании плагина Данные если первым аргументом метода Реквизит() указать имя несуществующего у объекта реквизита, то он просто игнорируется.

Ожидаю, что будет вызвано исключение, т.к. иначе сложно отлавливать ошибки.

Дано: конфигурация со справочником Номенклатура, у которого есть единственный реквизит "СтавкаНДС", число(2,0) (для примера не играет роли).

В тесте пишу вот такой код:
```bsl
	Номенклатура = Данные.НачатьСоздание("Справочник.Номенклатура")
		.Реквизит("СтакаНДС", 20)
		.Создать();
```

Сейчас такой код выполняется без ошибки, тест ломается из-за незаполненного реквизита "СтавкаНДС" и не сразу понятно, почему.

**Ожидаемое поведение, если бы ошибки не было**

Ожидаю, что такой код упадет с исключением: "У объекта метаданных <Справочник.Номенклатура> отсутствует реквизит <СтакаНДС>".

**Comment by artbear** [comment]
Что-то не подтверждается такой сценарий

написал тест для проверки, он проходит

```
Процедура Тест_НесуществующийРеквизит() Экспорт
	
	ИмяРеквизита = "НесуществующийРеквизит";
	
	ОбъектДанных = Данные.НачатьСоздание("Справочники.Справочник1")
		.Реквизит(ИмяРеквизита);
		
	Утверждения.ПроверитьМетодНеВыполнился(ОбъектДанных, "Создать", 
		СтрШаблон("Поле объекта не обнаружено (%1)", ИмяРеквизита));
	
КонецПроцедуры 
```

@kuntashov Выдай больше информации. Можно в личном чате

**Comment by artbear** [comment]
Интересно, падает именно при указании 2го параметра
`.Реквизит("СтакаНДС", 20)`
