### ISSUE TITLE
Плагин Данные / Переиспользует состояние, если есть вложенные вызовы

### ISSUE THREAD

**Issue by kuntashov** [silverbulleters/add#825]
Есть такой код:

```bsl
	Номенклатура1С = Данные.НачатьСоздание("Справочник.Номенклатура")
		.Реквизит("ВидНоменклатуры", НовыйВидНоменклатуры())
		.Создать(); 
```

Метод `НовыйВидНоменклатуры()` определен так:

```bsl
Функция НовыйВидНоменклатуры()
   	ВидНоменклатуры = Данные.НачатьСоздание("Справочник.ВидыНоменклатуры")
		.Создать();	
	Возврат ВидНоменклатуры;
КонецФункции
```

В результате в переменной Номенклатура1С у нас объект `СправочникСсылка.ВидНоменклатуры`, а ожидал, что будет `СправочникСсылка.Номенклатура`.

Судя по всему, плагин использует единственный экземпляр обработки и все состояние хранит в нем, поэтому вложенные вызовы невозможны.

Это не удобно/не естественно и про такую особенность нужно помнить, а если забыть - сложно отлаживать.

В качестве обхода можно делать так:

```bsl
    ВидНоменклатуры = НовыйВидНоменклатуры();

	Номенклатура1С = Данные.НачатьСоздание("Справочник.Номенклатура")
		.Реквизит("ВидНоменклатуры", ВидНоменклатуры)
		.Создать(); 
```
Но это тоже не всегда удобно (и опять же, про это нужно знать/помнить).

В качестве решения предлагаю рассмотреть возможность сделать так, чтобы метод `НачатьСоздание()` возвращал новый экземпляр плагина "Данные".

**Comment by artbear** [comment]
@kuntashov интересно. 

предложение `метод НачатьСоздание() возвращал новый экземпляр плагина "Данные"`полезно.
но возможно особенности использования создания объектов через КонтекстЯдра.

в серверных тестах проще всего заюзать вариант 
НовыйОбъект = ВнешниеОбработки.Создать("Данные");

особенность работы на сервере

если у плагина Данные имя метаданные Данные

**Comment by artbear** [comment]
@kuntashov в принципе, я с этой проблемой разобрался.
как я и предполагал, так и решается 

одна проблема
теперь нельзя юзать такой код - т.е. отдельно обращаться к методам уже после создания
- особенность текучих интерфейсов
```bsl
Данные.НачатьСоздание("Справочники.Справочник1")
	.Реквизит("СоставнойРеквизит");
ОбъектДанных = Данные.Создать();
```
правильно
```bsl
ОбъектДанных = Данные.НачатьСоздание("Справочники.Справочник1")
	.Реквизит("СоставнойРеквизит")
	.Создать();
```
в тестах был именно такой код, он легко и просто исправлен.

проблема небольшая и легко решаемася, но у кого-то может выстрелить )
