### ISSUE TITLE
Сделать группы настроек и макетов сворачиваемыми

### ISSUE THREAD

**Issue by sulfur17** [silverbulleters/add#828]
Существует проблема.
На основной управляемой форме иногда нужно только редактировать макет, или только настраивать дерево метаданных.
А вторая часть временно только зря занимает место. 

Хотелось бы иметь возможность скрывать ненужную область и разворачивать нужную на весь экран.
Например сделать группы на форме сворачиваемыми.

**Comment by artbear** [comment]
Выполнено.
