### ISSUE TITLE
FAQ: как использовать add после установки через opm install add

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#83]
Вопросы:
>Выполнил opm install add. Сижу медитирую, А что дальше то делать? Где написано?? Вроде не дурак, а чувствую себя ......

Ответы:
>заинтриговал
в либах появилась add и там bddrunner.epf который на первый взгляд есть ванесса
а рядом xunit

>Раньше для запуска тестов с помощью vrunner необходимо обязательно куда-то скачивать ванессу или же подключать с помощь submodule

> а сейчас можно сразу запускать
vrunner xunit ... или vrunner vanessa
без необходимости указания пути к инструментам и их доп.установки/скачивания

**Comment by artbear** [comment]
Дока доработана

**Comment by allustin** [comment]
@artbear плиз посмотри в методичке - там уже неактуальное получается описание

**Comment by artbear** [comment]
@allustin Посмотреть могу, но не понял, что потом нужно сделать, т.е. где предлагаешь исправлять?

**Comment by artbear** [comment]
Выполнено. В методичке отражено.
