### ISSUE TITLE
Поудалять формы из плагинов

### ISSUE THREAD

**Issue by sulfur17** [silverbulleters/add#848]
Говорят раньше они были нужны, но сейчас они не нужны, поэтому лучше их удалить их всех плагинов.

**Comment by sulfur17** [comment]
в функции bddRunner.УправляемаяФорма.Плагин() стоит TODO "добавить поведение при отсутствии управляемой формы у плагина". Пока это не сделано удалять формы нельзя, иначе плагин не будет работать в bddRunner (хотя в tddTestRunner будет)

**Comment by sulfur17** [comment]
и в дальнейшем когда при выполнении шага мы получаем плагин через Ванесса.Плагин("") то мы получаем форму. Так что в форму получается надо дублировать API плагина, иначе он в bddRunner работать не будет.

Так что по Issue надо дополнить документацию, только и всего.

**Comment by artbear** [comment]
@sulfur17 в ТДД-части также можно писать тесты в упр.форме, просто в этом случае сложно делать серверные тесты, т.к. тесты выполняются на клиент-сервере.

**Comment by artbear** [comment]
@sulfur17 я почитал твои комменты к текущему ишузу и не понял, что в итоге ты предлагаешь сделать.

сообщи, пожалуйста.

**Comment by sulfur17** [comment]
я предлагаю в документации по написанию плагинов отразить для чего в них нужна форма

**Comment by sulfur17** [comment]
я не настаиваю, просто я привык действовать по алгоритму: если ты не смог найти ответ на какой-то вопрос, значит надо улучшить документацию.
Но я не против закрыть эту задачу.

**Comment by sulfur17** [comment]
решил что это малозначимо, закрываю
