### ISSUE TITLE
[feat] Плагин "СериализаторMXL". Возможность указания дополнительных свойств объектов при удалении.

### ISSUE THREAD

**Issue by Mity1440** [silverbulleters/add#852]
**Существует проблема**
В текущей реализации плагина - нет возможности установить дополнительные свойства удаляемого объекта.
Речь идет о методе
...
СериализаторMXL.УдалитьСозданныеДанные()
...
Иногда это требуется сделать, например, чтобы не выполнялась регистрация в узлах обмена и прочая функциональность, которая как правило размещается в подписках на события и опирается на наличие определенного доп. свойства у объекта

**Хотелось бы иметь следующую функциональность**
Возможность устанавливать дополнительные свойства для удаляемых объектов, как пакетно так и по отдельности

**Comment by artbear** [comment]
выполнено.
