### ISSUE TITLE
[BUG] Запрещено одновременно задавать ключи --ibconnection и --ibname

### ISSUE THREAD

**Issue by sulfur17** [silverbulleters/add#864]
**Описание ошибки**
по команде opm run init получаю ошибку
```
vanessa-runner v1.10.2
ИНФОРМАЦИЯ - Запускаю обновление конфигурации БД
ИНФОРМАЦИЯ - Обновление конфигурации БД завершено.
04.05.2021 22:37:03: ИНФОРМАЦИЯ - vrunner compileepf ./tools tools --ibname /F./build/ibservice
vanessa-runner v1.10.2
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\vanessa-runner\src\main.os / Ошибка в строке: 207 / Запрещено одновременно задавать ключи --ibconnection и --ibname}
```

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. пройтись по [гайду](https://github.com/vanessa-opensource/add/blob/develop/.github/CONTRIBUTING.md) контрибьютера до шага opm run init

**Comment by maximsamokhval** [comment]
Возьму в работу, судя по всему, нужно исправить старый ключ --ibname на --ibconnection

**Comment by artbear** [comment]
@maximsamokhval Большое спасибо!
