### ISSUE TITLE
Расширение инструмента "Управление дымовыми тестами"

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#883]
**Существует проблема**

Есть замечательный репозиторий https://github.com/leobrn/ones-smoke-allure
В нем доработан инструмент "Управление дымовыми тестами"

**Хотелось бы иметь следующую функциональность**

Хотелось бы включения этой доработки в основной код Ванесса-АДД

ждем ответа от автора @leobrn

**Comment by leobrn** [comment]
принял в работу)

**Comment by leobrn** [comment]
@artbear добавил начальный ПР https://github.com/vanessa-opensource/add/pull/892

**Comment by leobrn** [comment]
@artbear работы завершил

**Comment by artbear** [comment]
Выполнено.
