### ISSUE TITLE
Для тестов расположенных в общих модулях вызов инициализации теста должен быть необязательным

### ISSUE THREAD

**Issue by yukon39** [silverbulleters/add#885]
Дополняет #873 

Для общего модуля в расширении содержащего xDD тесты вызов метода `Инициализация` необходимо сделать необязательным.

Т.к. у общих модулей отсутствует собственный контекст, то вызов его инициализации не имеет смысла. Однако, для отдельных сценариев использования, возможно размещение в нем предварительных действий общих для всех тестов этого модуля.

**Comment by artbear** [comment]
Предлагаю вообще сделать метод Инициализация необязательным для всех тестов, а не только для тестов из расширения.
