### ISSUE TITLE
Добавить генератор отчета для SonarQube (Generic Execution)

### ISSUE THREAD

**Issue by yukon39** [silverbulleters/add#890]
Для импорта в SonarQube результатов исполнения Unit-тестов добавить генератор отчета в формате Generic Execution. 

Документация по формату расположена тут: https://docs.sonarqube.org/latest/analysis/generic-test/#header-2)

**Comment by artbear** [comment]
Связанный ишуз https://github.com/vanessa-opensource/add/issues/65

**Comment by artbear** [comment]
Нужна пост-обработка.
подробности в https://github.com/vanessa-opensource/add/pull/891#issuecomment-910410076
