### ISSUE TITLE
xUnit: Не работает опция ДобавлятьИмяПользователяВПредставлениеТеста с ЕстьПоддержкаАсинхронныхВызовов

### ISSUE THREAD

**Issue by otymko** [silverbulleters/add#893]
**Описание ошибки**

Опция в xUnit `ДобавлятьИмяПользователяВПредставлениеТеста`  не работает (не реализована) в режиме `ЕстьПоддержкаАсинхронныхВызовов`.

**Сценарий воспроизведения**

Запустить xunit из пакетного режима на платформе, например, 8.3.16, с включенной опцией `ДобавлятьИмяПользователяВПредставлениеТеста` в конфигурационном файле.

На выходе имеем тесты в allure2 без префикса `- <ЮЗЕР>` в конце.

**Ожидаемое поведение, если бы ошибки не было**

При указании опции `ДобавлятьИмяПользователяВПредставлениеТеста` к представлению тестов должно добавляться `- <ЮЗЕР>` в конце.

**Скриншоты**

Это не работает:
![image](https://user-images.githubusercontent.com/11651847/132135973-22f94a0b-a729-4a29-9b81-234bbdb6845d.png)

**Окружение:**

Техническая информация:
	- Версия Vanessa-ADD: 6.7.0
	- Имя конфигурации: 
	- Синоним конфигурации: 
	- Версия конфигурации: 
	- Платформа 1С: 8.3.16.1659
	- Тип базы: Файловая ИБ
	- Режим запуска: Управляемое приложение (Тонкий клиент)
	- Режим совместимости (для TestManager): Версия8_3_12
	- Режим совместимости интерфейса (для TestManager): Такси
 	- Режим синхронности: включен
 	- Защита от опасных действий: включен
	- Язык (для TestManager): Русский
	- Локализация (для TestManager): ru
	- Операционная система: Windows x86 Microsoft Windows 10 version 10.0  (Build 19043)
	- Активные расширения:

**Дополнительный контекст**

**Comment by artbear** [comment]
Что-то не подтверждается )
![image](https://user-images.githubusercontent.com/2920817/134704767-139f86c4-a0ab-412f-8644-1a4365e949e9.png)

проблема была только при нажатии кнопки Перегрузить в интерактивном режиме, в этом режиме действительно настройки неверно подгружались.

коммит делаю

а в остальном работает.
вот только что проверил
например, командная строка в репо ванесса-адд - vrunner xunit tests\smoke\тесты_КомандныйИнтерфейс.epf --xddConfig spec/fixtures/smoke-include-from-support.json

![image](https://user-images.githubusercontent.com/2920817/134704998-3491502f-738f-4021-96dc-95c5e7a13349.png)

**Comment by otymko** [comment]
@artbear синхронность и версия платформы выше, чем 8.3.10

**Comment by artbear** [comment]
@otymko исправления внесены.

проверяй. на скриншоте видно, что в асинхронном режиме представления имени пользователя появились.

![image](https://user-images.githubusercontent.com/2920817/134711866-104203cb-aefc-490b-8294-b397520f8bf5.png)

В аллюре они также есть

**Comment by artbear** [comment]
Выполнено.
