### ISSUE TITLE
Добавить описание новых дымовых тестов из https://github.com/SidnevAV/SmokeTests1C

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#898]
**Хотелось бы иметь следующую функциональность**

Добавить описание новых дымовых тестов из https://github.com/SidnevAV/SmokeTests1C

**Дополнительный контекст**

**Comment by artbear** [comment]
@SidnevAV

**Comment by SidnevAV** [comment]
@artbear Подскажи куда лучше положить это описание.

**Comment by artbear** [comment]
@SidnevAV можно 
- или как подкаталог в tests/smoke, как и другая дока по дымовым
- или как подкаталог в doc/smoke

и обязательно добавить ссылку на доку где-то в начале доки по дымовым
