### ISSUE TITLE
Добавить имя базы в отчет allure 

### ISSUE THREAD

**Issue by LazarenkoA** [silverbulleters/add#916]
**Существует проблема**
при наличии нескольких конфигураций нужно прогонять тесты на разных базах, в таком случае дымовые тесты в алюр все в одной куче 
![image](https://user-images.githubusercontent.com/15386101/139466093-94125854-90d2-4abd-8624-234de624bdc2.png)

**Хотелось бы иметь следующую функциональность**
хотелось бы в алюр видеть разбивку по базам
![image](https://user-images.githubusercontent.com/15386101/139466164-a9ac6a54-4b1c-4143-a6b9-ac7a847a1f6f.png)

**Дополнительный контекст**

в принципе я у себя сделал это изменив одну строку кода в плагине ГенераторОтчетаAllureXML в процедуре ВывестиДанныеОтчетаТестированияРекурсивно 
```
Контейнер.name = СтрШаблон("%1 - %2", СтрокаСоединенияИнформационнойБазы(), РезультатыТестирования.Имя);
```
а с ГенераторОтчетаAllureXMLВерсия2 не разобрался

**Comment by artbear** [comment]
Можно так сделать, а можно добавить параметр ИмяСборки аналогично настройкам из бдд-части.
