### ISSUE TITLE
[BUG] Не обрабатываются имена исключений для теста тесты_ПроверкаМакетовСКД из файла smoke.json

### ISSUE THREAD

**Issue by maximsamokhval** [silverbulleters/add#964]
**Описание ошибки**
Некорректно обрабатываются имена исключений из файла настроек smoke.json

**Сценарий воспроизведения**

Шаги описаны на видео

**Ожидаемое поведение, если бы ошибки не было**
- После перезагрузки тестов с указанными настройками, исключаемые макеты, должны быть исключены

**Скриншоты**

https://user-images.githubusercontent.com/24194977/142604480-dcc308f7-adbf-4836-915b-015cdecd7311.mp4

**Окружение:**

Техническая информация:
	- Версия Vanessa-ADD: 6.8.0
	- Имя конфигурации: ДемонстрационноеПриложение
	- Синоним конфигурации: Демонстрационное приложение
	- Версия конфигурации: 1.0.32.3
	- Платформа 1С: 8.3.18.1334
	- Тип базы: Клиент-серверная ИБ
	- Режим запуска: Управляемое приложение (Тонкий клиент)
	- Режим совместимости (для TestManager): НеИспользовать
	- Режим совместимости интерфейса (для TestManager): Такси
 	- Режим синхронности: выключен
 	- Защита от опасных действий: включен
	- Язык (для TestManager): Русский
	- Локализация (для TestManager): ru_RU
	- Операционная система (клиент): Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)
	- Операционная система (сервер): Windows x86-64 Microsoft Windows 10 version 10.0  (Build 19043)
	- Активные расширения:
	- - Расширение: ВесТоваров -- Вес товаров - Безопасный режим не задан
	- - Расширение: Колонтитулы -- Колонтитулы - Безопасный режим включен

**Дополнительный контекст**

[Демонстрационная конфигурация](https://its.1c.ru/db/metod8dev/content/5028/hdoc)

Сгенерированный json файл

``` json 
{
    "smoke": {
        "Используется": true,
        "ОткрываемФормыНаКлиентеТестирования": false
    },
    "МодальныеОкна": {
        "ШаблонПомощника": {
            "Поля": [
                "*Закрыть *?"
            ],
            "Заголовки": [
                "* Шаблон *"
            ],
            "Кнопка": 0
        }
    },
    "CommandInterface": {
        "Используется": false,
        "СтрогийПорядокВыполнения": true,
        "ОбщиеКоманды": [
            "Удалить*",
            "ЗагрузитьДанныеИзФайла",
            "СверткаИнформационнойБазы",
            "УдалениеПомеченныхОбъектов"
        ],
        "Разделы": [
            "Настройки и администрирование"
        ]
    },
    "МакетыСКД": {
        "Используется": true,
        "ИсключенияОбщихМакетов": [],
        "ИсключенияПоИмениМетаданных": [
            "ДинамикаПродаж",
            "ДокументыОплата",
            "ОстаткиТоваровНаСкладах",
            "ОтчетПоВзаиморасчетам",
            "ПрайсЛист"
        ]
    },
    "ПроведениеДокументов": {
        "Используется": true,
        "КоличествоДокументов": 2,
        "Исключения": []
    },
    "ФормированиеПечатныхФорм": {
        "Используется": false,
        "КоличествоДокументов": 2,
        "ИсключенияПоОбъекту": [],
        "ИсключенияПоИдентификатору": [
            "Комплект*"
        ]
    }
}

```

Общение в чате по этой проблеме https://t.me/vanessa_opensource_chat/3248

**Comment by leobrn** [comment]
А можете попробовать собрать обработку для теста макетов отсюда https://github.com/leobrn/ones-smoke-allure/tree/main/src%2Ftests%2F%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0%D0%9C%D0%B0%D0%BA%D0%B5%D1%82%D0%BE%D0%B2%D0%A1%D0%9A%D0%94

Я в своем тестовом репо https://github.com/leobrn/ones-smoke-allure
корректировал вывод тестов при исключениях 

Интересно поможет ли для вашего случая

**Comment by maximsamokhval** [comment]
@leobrn 
Попробовал, но пока ничего не получилось. Результат тот же.
Сделал скринкаст с новой обработкой (подменил ее)

https://user-images.githubusercontent.com/24194977/142674798-6a2eeaea-ce1e-4a68-ae84-5e8c019bf53a.mp4

**Comment by maximsamokhval** [comment]
> А можете попробовать собрать обработку для теста макетов отсюда https://github.com/leobrn/ones-smoke-allure/tree/main/src%2Ftests%2F%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0%D0%9C%D0%B0%D0%BA%D0%B5%D1%82%D0%BE%D0%B2%D0%A1%D0%9A%D0%94
> 
> Я в своем тестовом репо https://github.com/leobrn/ones-smoke-allure корректировал вывод тестов при исключениях
> 
> Интересно поможет ли для вашего случая

Сейчас проверю еще раз, есть подозрение, что предыдущий раз некачественно проверил или сохранил Вашу обработку. Если я правильно заметил, то у Вас есть метод ЕстьВИсключаемойКоллекцииНастроек, который и должен обрабатывать исключения.

**Comment by maximsamokhval** [comment]
@leobrn Ваш вариант обработки [тесты_ПроверкаМакетовСКД](https://github.com/leobrn/ones-smoke-allure/tree/main/src%2Ftests%2F%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0%D0%9C%D0%B0%D0%BA%D0%B5%D1%82%D0%BE%D0%B2%D0%A1%D0%9A%D0%94) работает корректно и читает настройки из файла smoke.json

Я могу сделать ПР и взять из Вашего кода метод, который выполняет проверку? 

![image](https://user-images.githubusercontent.com/24194977/142873048-4702f02c-601a-45e4-a287-8670e5f0520d.png)

![image](https://user-images.githubusercontent.com/24194977/142873100-3ded2839-ef67-444c-8710-75128b6ae0ff.png)

**Comment by leobrn** [comment]
> @leobrn Ваш вариант обработки [тесты_ПроверкаМакетовСКД](https://github.com/leobrn/ones-smoke-allure/tree/main/src%2Ftests%2F%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0%D0%9C%D0%B0%D0%BA%D0%B5%D1%82%D0%BE%D0%B2%D0%A1%D0%9A%D0%94) работает корректно и читает настройки из файла smoke.json
> 
> Я могу сделать ПР и взять из Вашего кода метод, который выполняет проверку? 
> 
> ![image](https://user-images.githubusercontent.com/24194977/142873048-4702f02c-601a-45e4-a287-8670e5f0520d.png)
> 
> ![image](https://user-images.githubusercontent.com/24194977/142873100-3ded2839-ef67-444c-8710-75128b6ae0ff.png)
> 

Да. Я в прошлый раз не стал это переносить т.к не было обратной связи по этому исправлению . Я в нескольких тестах вывод правил.
