### ISSUE TITLE
Исправить неверные/устаревшие ссылки

### ISSUE THREAD

**Issue by artbear** [silverbulleters/add#97]
Обнаружил коллега:
+ Правильно ли оставить старую ссылку в комментарии обработки xddTestRunner из пакета ADD?
Лучше указать https://github.com/silverbulleters/add?
![image](https://user-images.githubusercontent.com/2920817/38353221-78e5db12-38be-11e8-8f94-bdbac4d85c25.png)

+ Не работает ссылка в документе https://github.com/silverbulleters/add/blob/master/doc/README.md

![image](https://user-images.githubusercontent.com/2920817/38353264-9db60390-38be-11e8-9a02-2af8288159a3.png)

**Comment by allustin** [comment]
Назначаю на себя

**Comment by artbear** [comment]
Выполнено
