### ISSUE TITLE
Релиз 6.8.0 Преобразование значения к типу Число не может быть выполнено

### ISSUE THREAD

**Issue by a-sitnikov** [silverbulleters/add#976]
При открытии xddtestRunner и при запуске тестов выходит ошибка
Преобразование значения к типу Число не может быть выполнено
{ВнешняяОбработка.xddTestRunner.МодульОбъекта(1120)}:		Если Число(Элем2) > Число(Элем1) Тогда
{ВнешняяОбработка.xddTestRunner.МодульОбъекта(1139)}:	Возврат ВерсияПриложенияБольшеИлиРавнаЧемЗаданная(ВерсияРежимаСовместимости, НеобходимаяВерсияПриложения);
{ВнешняяОбработка.Информатор.Форма.Форма.Форма(245)}:	ПроверятьАктивностьРасширений = КонтекстЯдра.ПодходящийРежимСовместимостиПлатформы("8.3.12");
{ВнешняяОбработка.Информатор.Форма.Форма.Форма(232)}:	Для Каждого ЭлементСписка Из СписокРасширений(КонтекстЯдра) Цикл
{ВнешняяОбработка.Информатор.Форма.Форма.Форма(136)}:	Данные.Вставить("Расширения", ИнформацияОбАктивныхРасширенияхСервер(КонтекстЯдра));
{ВнешняяОбработка.Информатор.Форма.Форма.Форма(41)}:	Возврат ТехническаяИнформацияСервер(Данные);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(2457)}:	ВывестиСообщениеВЛогФайл(Плагин("Информатор").ТехническаяИнформация());
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(152)}:		ПервичнаяНастройка();
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(176)}:		ВыполнитьТестыНаКлиенте(Фильтр);

Платформа 8.3.19.1417 без режима совместимости
add - 6.8.0 из релиза

**Comment by a-sitnikov** [comment]
Пытается сравнить "НеИспользовать" и "8"

**Comment by maximsamokhval** [comment]
@a-sitnikov Уже исправлено, в develop версии, ишуз #936

**Comment by artbear** [comment]
Уже исправлено, ссылка указана. закрываю
