### ISSUE TITLE
[BUG] Функция ВерсияПриложенияБольшеИлиРавнаЧемЗаданная

### ISSUE THREAD

**Issue by forsaled** [silverbulleters/add#991]
**Описание ошибки**
Функция ВерсияПриложенияБольшеИлиРавнаЧемЗаданная валится, если в конфигурации стоит режим совместимости "НеИспользовать", потому что принимает только числа.
Вызов в моём случае идёт из плагина ЗагрузчикРасширения, строка 137.

Версия АДД 6.8.0.

**Comment by Vovqa412** [comment]
Коллеги, приветствую!

**Позитивный кейс**
Платформа 8.3.21.1302, конфигурация в режиме совместимости 8.3.20.
1) В менеджере тестирования открываю ADD
2) Интерактивно открываю файл с тестом, выполняю - всё ок.

**Негативный кейс**
Платформа 8.3.21.1302, конфигурация с отключенным режимом совместимости.
1) В менеджере тестирования открываю ADD
Получаю ошибку:
_Возникла ошибка при загрузке плагина: D:\Program Files\OneScript\lib\add\plugins\ЗагрузчикРасширения.epf
Преобразование значения к типу Число не может быть выполнено
{ВнешняяОбработка.xddTestRunner.МодульОбъекта(1120)}:Если Число(Элем2) > Число(Элем1) Тогда
{ВнешняяОбработка.xddTestRunner.МодульОбъекта(1139)}:Возврат ВерсияПриложенияБольшеИлиРавнаЧемЗаданная(ВерсияРежимаСовместимости, НеобходимаяВерсияПриложения);
{ВнешняяОбработка.ЗагрузчикРасширения.МодульОбъекта(137)}:Если Не КонтекстЯдра.ПодходящийРежимСовместимостиПлатформы("8.3.13") Тогда
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(400)}:ОписаниеПлагина = ОбъектОбработки.ОписаниеПлагина(ЭтотОбъектНаСервере, Объект.ТипыПлагинов);

[ОшибкаВоВремяВыполненияВстроенногоЯзыка, ОшибкаИспользованияВстроенногоЯзыка]_

2) Интерактивно открываю файл с тестом, выполняю - получаю ошибку

_Преобразование значения к типу Число не может быть выполнено
{ВнешняяОбработка.xddTestRunner.МодульОбъекта(1120)}:Если Число(Элем2) > Число(Элем1) Тогда
{ВнешняяОбработка.xddTestRunner.МодульОбъекта(1139)}:Возврат ВерсияПриложенияБольшеИлиРавнаЧемЗаданная(ВерсияРежимаСовместимости, НеобходимаяВерсияПриложения);
{ВнешняяОбработка.Информатор.Форма.Форма.Форма(245)}:ПроверятьАктивностьРасширений = КонтекстЯдра.ПодходящийРежимСовместимостиПлатформы("8.3.12");
{ВнешняяОбработка.Информатор.Форма.Форма.Форма(232)}:Для Каждого ЭлементСписка Из СписокРасширений(КонтекстЯдра) Цикл
{ВнешняяОбработка.Информатор.Форма.Форма.Форма(136)}:Данные.Вставить("Расширения", ИнформацияОбАктивныхРасширенияхСервер(КонтекстЯдра));
{ВнешняяОбработка.Информатор.Форма.Форма.Форма(41)}:Возврат ТехническаяИнформацияСервер(Данные);
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(2457)}:ВывестиСообщениеВЛогФайл(Плагин("Информатор").ТехническаяИнформация());
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(152)}:ПервичнаяНастройка();
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(176)}:ВыполнитьТестыНаКлиенте(Фильтр);

[ОшибкаВоВремяВыполненияВстроенногоЯзыка, ОшибкаИспользованияВстроенногоЯзыка]_

Полагаю ошибка в интерпретации результата функции ВерсияПриложенияБольшеИлиРавнаЧемЗаданная()
Функция ПодходящийРежимСовместимостиПлатформы(Знач НеобходимаяВерсияПриложения) Экспорт

	// СистемнаяИнформация.ВерсияПриложения - 8.3.21
	// НеобходимаяВерсияПриложения 			- 8.3.12
	//
	// Функция ВерсияПриложенияБольшеИлиРавнаЧемЗаданная() возвращает Истина
	
	СистемнаяИнформация = Новый СистемнаяИнформация;
	Если Не ВерсияПриложенияБольшеИлиРавнаЧемЗаданная(СистемнаяИнформация.ВерсияПриложения, НеобходимаяВерсияПриложения) Тогда
		Возврат Ложь;
	КонецЕсли;

	ВерсияРежимаСовместимости = ВерсияРежимаСовместимости();

	// ВерсияРежимаСовместимости - НеИспользовать
	//
	// ВерсияПриложенияБольшеИлиРавнаЧемЗаданная - падает
	
	Возврат ВерсияПриложенияБольшеИлиРавнаЧемЗаданная(ВерсияРежимаСовместимости, НеобходимаяВерсияПриложения);

КонецФункции

**Comment by artbear** [comment]
Исправлено в девелоп-ветке в рамках https://github.com/vanessa-opensource/add/pull/938
